### ISSUE TITLE
参数配置化呗~

### ISSUE THREAD

**Issue by okoala** [shalldie/vscode-background#1]
比如说：

1. 图片url配置~
2. background position， background size, opacity 神马的~
3. 图片本地cache~

**Comment by shalldie** [comment]
之前考虑过这个，但是，vscode的输入框，太过于复杂的配置，输入起来不方便。

现在有了一些新的想法，我会接下来试着去解决这个问题。

**Comment by be5invis** [comment]
用 settings 啊……
ps. 要不要去 fork 一个版本去支持 custom css and js

**Comment by shalldie** [comment]
嗯，，，家里网不好啊艹。
听您的意思，似乎可以用配置文件  0.0 
我去翻翻资料

**Comment by jianzhichun** [comment]
是可以用的 vscode.workspace.getConfiguration(?).get(?) 就能取到settings的配置

**Comment by shalldie** [comment]
谢谢楼上。   因为本身并不是一个复杂的插件，所以还在考虑是否用setting。

**Comment by jianzhichun** [comment]
话说，因为公司vscode版本是比较底 所以加css那里并没有one-editor-silo:nth-child(1) 得改成[id='workbench.parts.editor']>.content>.editor-left ...
[id='workbench.parts.editor']>.content>.editor-center ....
[id='workbench.parts.editor']>.content>.editor-right ...
才能work，新版本只能通过这样选择吗。

**Comment by shalldie** [comment]
汗，你用的估计是1.3以前的。
还是更新一下吧，，，

**Comment by atian25** [comment]
支持配置化吧... 现在用的好麻烦:
- 切换到外面, **找到图片的完整 URL..**
- F1 调出命令行, 选择 background
- 黏贴 URL
- ** 重启 **

期望:
- 通过配置文件直接配置, 这样能节省不少时间
- 不用重启

**Comment by shalldie** [comment]
好好好，配置一下。
不过这样也这是把粘贴url路径这里换掉  0.0

打算手头上事情搞完之后去做。 稍等一段时间。 :dango:

**Comment by atian25** [comment]
对 vscode 不是很熟悉, 这个 css 变更后必须重启么?
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css

**Comment by atian25** [comment]
另外发现写入 workbench.main.css 的方式, 当 vscode 升级后就被干掉了.

**Comment by shalldie** [comment]
已经参数化配置。在 setttings.json 中可以设置。
css变更后，需要重启。  还没有找到直接替换新css的方式。

**Comment by atian25** [comment]
这个插件是否存在 vscode 升级后被覆盖的问题? 之前遇到过, 然后就换了 https://github.com/be5invis/vscode-custom-css

**Comment by shalldie** [comment]
目前是监听配置文件settings.json改变，然后判断是否需要重置。
升级会被覆盖，确实是个问题。我会尽快解决这个问题。

**Comment by atian25** [comment]
可以参考下上面给的那个链接, 它解决了这个问题

**Comment by shalldie** [comment]
已经解决， 请更新至 1.1.6
