### ISSUE TITLE
默认的三个图片在哪里  怎么修改默认图片的次序

### ISSUE THREAD

**Issue by dopping** [shalldie/vscode-background#101]
默认图片在哪里 我想更换默认的那三个图片的次序

**Comment by shalldie** [comment]
默认的图片在插件里面我封的base64，顺序改不了。

如果有这种需求，建议用自定义图片来控制顺序。

**Comment by shalldie** [comment]
@jiangjihui 
地址在这里： https://github.com/shalldie/vscode-background/issues/31
