### ISSUE TITLE
激活扩展失败

### ISSUE THREAD

**Issue by KaierChou** [shalldie/vscode-background#102]
![2018-05-07 11 03 13](https://user-images.githubusercontent.com/24623866/39683113-52c683f0-51e6-11e8-93ce-04702792faf2.png)
win 下 和osx下都一样.. 不知怎么回事~~ win用的管理员运行. osx下我文件的权限全开'读与写'.
咋回事呢~ rua

**Comment by shalldie** [comment]
确保你运行的vscode是你添加权限的那个。有时候会不小心装了多个。

根据图中所示，你的osx中，在运行的这个vscode安装的目录是：`/private/var/folders/h1/b_v1p2bd633_wg_13k93nhkw0000gn/T/A.....balabala.../d/Visual Studio Code.app` 

好长，好奇怪。

**Comment by ifzm** [comment]
现在就是这个样子的目录，加载插件失败，提示没有文件写权限
