### ISSUE TITLE
mac端安装插件以后显示code安装似乎损坏，请重新安装

### ISSUE THREAD

**Issue by scoyzhao** [shalldie/vscode-background#103]
![image](https://user-images.githubusercontent.com/26707590/39968206-133368be-56fc-11e8-84c7-50843a1505f0.png)
mac版本10.3.4，vscode版本1.23.1

**Comment by shalldie** [comment]
https://github.com/shalldie/vscode-background#warns-%E8%AD%A6%E5%91%8A

是这样子的。
