### ISSUE TITLE
Insiders版本的VSCode插件失效，显示不了背景图片

### ISSUE THREAD

**Issue by Xu-Angel** [shalldie/vscode-background#113]

**Comment by Xu-Angel** [comment]
管理员权限已开的

**Comment by shalldie** [comment]
不好意思目前不支持insider版本。因为精力有限，只能保证正式版上的使用 😂

**Comment by Xu-Angel** [comment]
![image](https://user-images.githubusercontent.com/25033729/42435578-9478ef3e-8389-11e8-8540-0660a2af5ae2.png)

 可以了 1.26.0内测版

**Comment by shalldie** [comment]
侥幸侥幸，，，hhh
