### ISSUE TITLE
升级1.25.0版本后不能显示

### ISSUE THREAD

**Issue by ZDZN** [shalldie/vscode-background#114]
版本: 1.25.0
提交: 0f080e5267e829de46638128001aeb7ca2d6d50e
日期: 2018-07-05T13:11:58.697Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
架构: x64

已经是管理员身份运行

**Comment by shalldie** [comment]
修复中

**Comment by shalldie** [comment]
已重新发布，ver.1.1.19
但是手头上只有mac，就只测了这个 😂😂

**Comment by UncleQitian** [comment]
win10 更新插件到ver1.1.19后插件不能显示

**Comment by shalldie** [comment]
win 下已测试。

**Comment by ZDZN** [comment]
可以了，谢谢
