### ISSUE TITLE
今早上更新VSCODE之后，背景图片没了

### ISSUE THREAD

**Issue by Ztachi** [shalldie/vscode-background#115]
![image](https://user-images.githubusercontent.com/6995332/42355848-cc0dfad2-8101-11e8-9c3b-d6868f433ea7.png)
这是当前版本

**Comment by shalldie** [comment]
修复中

**Comment by t496971418** [comment]
做等LZ修复,给个🍗

**Comment by shalldie** [comment]
@t496971418

**Comment by shalldie** [comment]
@t496971418 

已重新发布，ver.1.1.19
但是手头上只有mac，就只测了这个 😂😂

**Comment by Ztachi** [comment]
已经修复了:thumbsup::thumbsup::thumbsup:
ps.貌似我才是LZ吧
