### ISSUE TITLE
关于卸载(How to remove this extension)

### ISSUE THREAD

**Issue by clChenLiang** [shalldie/vscode-background#119]
按照文档中所说，在未设置 **`background.enable` ** 的情况下，进行了卸载，会出现卸载不干净的情况。
但并不需要重新安装 `vscode`。 只需要将插件重新安装，再正确步骤卸载即可。

**Comment by shalldie** [comment]
是这样没错。

**Comment by clChenLiang** [comment]
嗯嗯

**Comment by Roc136** [comment]
请问是在哪个 `settings.json` 里面添加

**Comment by shalldie** [comment]
`settings.json` 是vscode的配置文件，在很多issue里面回复过打开方式，但是一些朋友找不到，这里聚拢下：

<img width="508" alt="image" src="https://user-images.githubusercontent.com/9987486/168024807-f6d80616-ccc9-466c-b2f5-1d00ab24790a.png">

win：`文件` -> `首选项` -> `设置` -> `右上角 打开设置（json）`
mac：`Code` -> `首选项` -> `设置` -> `右上角 打开设置（json）`

mac下打开设置的快捷键： `command` + `,`

<img width="281" alt="image" src="https://user-images.githubusercontent.com/9987486/168024939-ee2d63e2-2620-482f-aea9-0a7a45a24e2f.png">

vscode左下角也有个icon可以打开【设置】

**Comment by shalldie** [comment]
卸载方式： 同 [README](https://github.com/shalldie/vscode-background#uninstall-%E5%8D%B8%E8%BD%BD)

```
Set the config  {"background.enabled": false}  in settings.json, then uninstall the plugin.

需要在 settings.json 中设置 {"background.enabled": false} ，然后再删除插件。如果直接删除插件会有遗留，就需要重装vscode，或者把插件装回来再执行该步骤。
```
