### ISSUE TITLE
如何添加权限

### ISSUE THREAD

**Issue by shalldie** [shalldie/vscode-background#120]
本插件是通过修改vscode样式文件的方式更改背景，所以需要有对该样式文件的读写权限。

**Comment by Sway007** [comment]
我补充一个ubuntu上添加权限的方法把
```bash
sudo chmod a-x $(find /usr/share/code -iname "workbench.main.css")
```
> 另外好像code每次更新后都得添加一些写权限，不然插件好像无法正常工作，大佬解决一下？

**Comment by kungfulon** [comment]
MacOS EROFS:

在vscode所在的目录，运行shell：
`sudo xattr -d -r -s com.apple.quarantine Visual\ Studio\ Code.app`

**Comment by lhwjsj** [comment]
我装上插件之后正常配置，然后重启vs code没有出现背景图片(windows电脑，也右键管理员运行了)

**Comment by lightmon233** [comment]
求一个ubuntu的解决方案，我按照上面那个的方法来不行，及时修改了这个文件的读写权限还是汇报同样的错

**Comment by NoDocCat** [comment]
@lightmon233 是否使用 Snap 安装? 如果是, 请参考: #382

**Comment by shalldie** [comment]
常见问题现在可以参考：[常见问题](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.zh-CN.md)

如果遇到困难可以新开issue
