### ISSUE TITLE
Random image selection

### ISSUE THREAD

**Issue by TheBird956** [shalldie/vscode-background#121]
It would be nice to have an option to enable random custom images

**Comment by shalldie** [comment]
This extension works by edit vscode's css file.
By this way, every time to open the vscode, the images have been ordered already.

I'll think about any good way to achieve it.

**Comment by FredZeng** [comment]
可以参考一下另一款插件 https://marketplace.visualstudio.com/items?itemName=manasxx.background-cover&ssr=false#qna ，主要是觉得随机图片显示以及图片cover整个vscode，这两个功能比较好。

**Comment by ak1raxyz** [comment]
```python
# coding: utf-8
# 既然 VS Code Background 没有提供 shuffle 功能, 只好咱自己来了.

import os
import json
import pathlib
import random

p = pathlib.Path(os.environ["appdata"]).joinpath("Code/User/settings.json")

with open(p, "r+") as f:
    settings = json.loads(f.read())
    random.shuffle(settings.get("background.customImages"))
    f.seek(0)
    f.write(json.dumps(settings, indent=4, ensure_ascii=False))
```

**Comment by dbshch** [comment]
I made a [commit](https://github.com/dbshch/vscode-background/commit/3c5e9955ab4aec2619d0c48387fa67fdc16c014f) that supports using image folder and shuffling the image order.
The mechanism refers to the background-cover extension. So it just shuffles the image order and use that order when the window is reloaded (i.e. for the next use). It doesn't need admin priviledge for that after extension enabled.
It still can't randomly set background on demand for now. If you reopen a closed split view the background is still the closed one.
Hope it works.
