### ISSUE TITLE
更改自定义图片后仍然是默认图片

### ISSUE THREAD

**Issue by tangdingga1** [shalldie/vscode-background#123]
## 问题
`在进行用户设置自定义图片之后，背景图片仍然是默认的东方`
# 用户设置
"background.useDefault": false,
    "background.customImages": [
        "file:///C:/Users/ChinaHp/.vscode/extensions/shalldie.background-1.1.19/aaa.jpg"
    ],
    "background.useFront": true
# 平台情况
- `系统`:win10
- `vs code`:1.25.1
- `background`:1.1.19

**Comment by TankRyze** [comment]
"background.enabled": true,//卸载插件开启
    "background.useDefault": false,
    "background.customImages": [
        "file:///Users/jianyuehudong/Desktop/vscode/img/vscodebg.jpg"
    ],
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "0% 0%",
        "background-size": "cover",
        "background-repeat": "no-repeat",
        "opacity": 0.1
    }
你的是不是 opacity:1  啊改成  0.1  试试

**Comment by dadaa1** [comment]
我的也是这样，设置opacity也不行

**Comment by yuguansu** [comment]
一样的问题，windows10

**Comment by g8up** [comment]
这样设置即可：
```json
{
  "background.useDefault": false,
  "background.customImages": [
    "C:/Users/ChinaHp/.vscode/extensions/shalldie.background-1.1.19/aaa.jpg"
  ],
}
```

**Comment by gonefuture** [comment]
您的邮件已发送到钱伟健的邮箱。
