### ISSUE TITLE
VsCode 提示扩展不受支持

### ISSUE THREAD

**Issue by DaiZero** [shalldie/vscode-background#124]
![image](https://user-images.githubusercontent.com/13118354/43692974-09f402e6-995e-11e8-9ba4-777643c15d43.png)

**Comment by wzhqwq** [comment]
[不受支持]是说VSCode的CSS被改了破坏了完整性所以VSCode不受支持

**Comment by shalldie** [comment]
sorry，才看到，最近太忙了。

关于这个在readme中有说明，是vscode的文件被修改所以产生：
 https://github.com/shalldie/vscode-background#warns-%E8%AD%A6%E5%91%8A

**Comment by DaiZero** [comment]
看到了，谢谢啊！
