### ISSUE TITLE
mac 已经获取权限 但背景还是没有显示

### ISSUE THREAD

**Issue by jsliu27** [shalldie/vscode-background#130]
"background.enabled": true,//卸载插件开启
    "background.useDefault": false,
    "background.customImages": [
        "file:///Users/jianyuehudong/Desktop/vscode/img/vscodebg.jpg"
    ],
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "0% 0%",
        "background-size": "cover",
        "background-repeat": "no-repeat",
        "opacity": 0.1
    }

图片地址是从url上面取得，求大神指导

**Comment by shalldie** [comment]
vscode ver 1.27.2 在mac上测试木有问题。

是不是你的透明度太低了呢？

**Comment by TankRyze** [comment]
> vscode ver 1.27.2 在mac上测试木有问题。
> 
> 是不是你的透明度太低了呢？

不是我改了，还是不行麻烦把你的粘出来我试一下

**Comment by shalldie** [comment]
@TankRyze  用默认的就行，你把 `background.style` 删掉看看

**Comment by TankRyze** [comment]
默认是空的没有样式，尝试了，还是不可以

**Comment by panyiliang** [comment]
> @TankRyze 用默认的就行，你把 `background.style` 删掉看看

mac设置本地文件路径一直提示定位不到。。
文件路径：/Users/pandabo/Documents/栗山未来.jpeg
配置项："background.customImages": ["file://⁩/⁨Users/pandabo/Documents/栗山未来.jpeg"],

**Comment by TankRyze** [comment]
{
    "explorer.confirmDragAndDrop": false,
    "explorer.confirmDelete": false,
    "window.zoomLevel": 1,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "workbench.colorTheme": "Dracula",
    "background.customImages": [
        "file:///Users/jianyuehudong/Desktop/vscode/img/vscodebg.jpg"
    ],
    "workbench.startupEditor": "welcomePage",
    "cssrem.rootFontSize": 37.5
}
这样还是不行的，哎😔

**Comment by shalldie** [comment]
@TankRyze 
要加上 `"background.useDefault": false`

**Comment by TankRyze** [comment]
@shalldie 感谢您的提醒，现在加上了还是没有显示背景，很是纠结😖
{
    "explorer.confirmDragAndDrop": false,
    "explorer.confirmDelete": false,
    "window.zoomLevel": 1,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "workbench.colorTheme": "Dracula",
    "background.useDefault": false,
    "background.customImages": [
        "file:///Users/jianyuehudong/Desktop/vscode/img/vscodebg.jpg"
    ],
    "workbench.startupEditor": "welcomePage",
    "cssrem.rootFontSize": 37.5
}
麻烦您有时间再给看一下

**Comment by TankRyze** [comment]
激活扩展“shalldie.background”失败: EROFS: read-only file system, open '/private/var/folders/m3/1f1msw0s5dj1t967fqn796tc0000gn/T/AppTranslocation/E1CBD478-220F-407B-BACF-41300B895D7A/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css'。

**Comment by TankRyze** [comment]
> 激活扩展“shalldie.background”失败: EROFS: read-only file system, open '/private/var/folders/m3/1f1msw0s5dj1t967fqn796tc0000gn/T/AppTranslocation/E1CBD478-220F-407B-BACF-41300B895D7A/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css'。

@shalldie 爽哥，找到这个文件了，需要怎么修改呢

**Comment by babydada** [comment]
我mac也是

**Comment by StevenJokes** [comment]
hh
![image](https://user-images.githubusercontent.com/25657787/91552987-4068db00-e95f-11ea-9e05-8d5969ab2ce0.png)
Win10

**Comment by shalldie** [comment]
，，，时隔蛮久，可以参考这个：https://github.com/shalldie/vscode-background/issues/252
