### ISSUE TITLE
一个窗口一张图片

### ISSUE THREAD

**Issue by piumnl** [shalldie/vscode-background#136]
是否可以添加一个配置：一个 vscode窗口仅一张背景图片。

因为我比较喜欢整个窗口一张图片居中，如果一个编辑器就一张图片，拆分编辑器的时候容易分散注意力。

**Comment by shalldie** [comment]
目前是一个tab一个图片，图片依赖于tab存在。
如果想只要第一个tab有图片，可以设置 `background.customImage` 为  `["xxxx.png","",""]`
即后两个为空。

如果想以vscode编辑器为单元可以看看这个插件： https://github.com/AShujiao/vscode-background-cover

**Comment by piumnl** [comment]
@shalldie 完美解决问题
