### ISSUE TITLE
background extension is not uninstallable

### ISSUE THREAD

**Issue by sean-mcmanus** [shalldie/vscode-background#14]
I can't uninstall the background extension. It says it's uninstalled, but the background still has the picture. The settings are gone though.

**Comment by shalldie** [comment]
You can only remove the picture in settings.json.
I'm looking for a way/method to add event listener to watch while the extension is being uninstalled.

**Comment by zhengxiaoyao0716** [comment]
Before you uninstall this extension, you can add `"background.enabled": false` in your user setting.json, then restart the editor, and the background will been removed. Then you can install this extension and your vscode will be restored.

**Comment by sean-mcmanus** [comment]
Okay, thanks. Yeah, I don't know how to do actions on uninstall, but changing the settings is a workaround.
