### ISSUE TITLE
UI 設定搜尋框也被加上背景了...

### ISSUE THREAD

**Issue by maple3142** [shalldie/vscode-background#140]
![image](https://user-images.githubusercontent.com/9370547/48129600-f794ed80-e2c4-11e8-8607-0b2fbf6ddcee.png)

**Comment by shalldie** [comment]
>_<#@!  

好的，我周末改改

**Comment by shalldie** [comment]
很不好意思忙成🐶了，有时候想起来就想拖到周末弄，结果周末又忘了。

这次标记下，找时间改改，，，

**Comment by OkazakiNagisa** [comment]
已经十二月辣老弟

**Comment by maple3142** [comment]
居然已經超過一年了，我都忘記有這個issue了

**Comment by shalldie** [comment]
😂😂  今天，，今天，，，不拖了

**Comment by shalldie** [comment]
done
