### ISSUE TITLE
mac 系统下  背景图片请求的路径不对

### ISSUE THREAD

**Issue by nikomal** [shalldie/vscode-background#141]
大佬,
配置的信息是
![image](https://user-images.githubusercontent.com/18556302/48179812-e6e38680-e35b-11e8-8007-5eee83c4286c.png)
然后打开控制台看到请求的路径是那样的
![image](https://user-images.githubusercontent.com/18556302/48179804-d8956a80-e35b-11e8-95a9-453c68e78c1d.png)
就导致找不到文件资源  了
![image](https://user-images.githubusercontent.com/18556302/48179861-198d7f00-e35c-11e8-8894-1107757b6f9f.png)

**Comment by shalldie** [comment]
试了好几次，并没有重现这种情况。

更换一张图片路径试试？

**Comment by nikomal** [comment]
@shalldie 换了也没用  我感觉可能和我装的vscode的有关系 不过我直接改的插件的代码 解决了....
