### ISSUE TITLE
设置了权限也不行

### ISSUE THREAD

**Issue by xinyiPig** [shalldie/vscode-background#142]
![image](https://user-images.githubusercontent.com/30715127/48251016-3b116800-e43b-11e8-96b0-0dd75677ae20.png)

**Comment by xinyiPig** [comment]
![image](https://user-images.githubusercontent.com/30715127/48256486-b6c6e100-e44a-11e8-88b8-8a6ccb604d1a.png)

**Comment by shalldie** [comment]
兄弟不好意思，因为各种各样的原因，反正现在才看到这个issue =。=

你打开的这个vscode，安装在  `private/var...` 目录下，插件尝试运行发现没有权限。
你看一下红字，是这个路径。

然后你添加权限的这个文件，应该是别的目录。

---

以前也发现过这种，不清楚为啥，，，
就是软件安装的目录，在运行的时候复制一份到另一个目录去运行？

**Comment by hoyong6** [comment]
mac，他不是软件目录安装，根本不进程序坞，类似 实时 运行 在 /private/var/folders/4s/... 后面还有一堆。导致我根本没有权限，
$ sudo chmod -R 777 workbench.desktop.main.css
Password:
chmod: Unable to change file mode on workbench.desktop.main.css: Read-only file system

它实时就是只读的。。。。擦

**Comment by hoyong6** [comment]
我和这位兄弟报错一样，莫得权限。

**Comment by hoyong6** [comment]
我这里给出的强改方法还是这位仁兄的

https://www.jianshu.com/p/b2e372a96271

mac 不是直接下载出来一个压缩包，解压出来vscode图标，直接在解压出来的vscode 图标上，打开包文件，然后一路找到文件地址，改下去。然后重启亲测有效，别去改什么  /private/var/folders/4s/...

运行文件了，无效的

**Comment by shalldie** [comment]
时隔蛮久，可以参考这个：
https://github.com/shalldie/vscode-background/issues/252
