### ISSUE TITLE
将width和height设置为200%后，vscode客户端崩溃了，重启都没用

### ISSUE THREAD

**Issue by dujinyu** [shalldie/vscode-background#144]

**Comment by dujinyu** [comment]
![image](https://user-images.githubusercontent.com/33440141/48660357-47c93800-ea9b-11e8-9aac-36b9b3e9748c.png)

**Comment by shalldie** [comment]
=。=  重装vscode吧。

看来是在写入的时候遇到问题，导致css文件丢失。
会考虑做一个备份。
