### ISSUE TITLE
mac设置单个图片样式导致vscode样式混乱

### ISSUE THREAD

**Issue by myjyixi** [shalldie/vscode-background#145]
使用calc()设置单个图片的background-position: calc(100% + 200px) 100% ，结果。。
![image](https://user-images.githubusercontent.com/31266885/50649120-f8da5200-0fb7-11e9-8c15-fe04c8f7c5b8.png)

**Comment by shalldie** [comment]
该问题的原因是写入文件发生未知错误导致样式文件丢失，重装一下吧。

等空闲下来我找找其它更安全的方式。

**Comment by myjyixi** [comment]
> 该问题的原因是写入文件发生未知错误导致样式文件丢失，重装一下吧。
> 
> 等空闲下来我找找其它更安全的方式。

昨天重装了，重复了一样的操作 然后vscode表现正常

**Comment by shalldie** [comment]
objk
