### ISSUE TITLE
这个插件怎么卸载了图片还显示

### ISSUE THREAD

**Issue by polaris-dxz** [shalldie/vscode-background#146]
操作系统：macOS Mojave 10.14.1
VSCode版本：1.30.1
描述：无效配置都删了，重启vscode背景图还在。。

**Comment by higker** [comment]
........谁用谁知道。。。。我直接卸载vscode了。。。👎

**Comment by zhangzhiqiangcs** [comment]
目前最新安装的仍然有这个问题
