### ISSUE TITLE
默認的背景能換順序嗎？

### ISSUE THREAD

**Issue by tkmmot321** [shalldie/vscode-background#149]

**Comment by shalldie** [comment]
这种需求可以用自定义图片，按照喜欢的顺序添加配置。

插件内含有的图片在：https://github.com/shalldie/vscode-background/issues/106

**Comment by UserNameYSH** [comment]
设置顺序如截图：[图片]

**Comment by UserNameYSH** [comment]
![J{0MTD5C2F$%F4YOSW4OW)3](https://user-images.githubusercontent.com/46313429/54861286-b415ba00-4d61-11e9-819d-02394aa7e83a.png)

**Comment by shalldie** [comment]
不明白你的意思，这个就按你想要的顺序放进去就行。

另，你上面有个报错红线应该处理一下。
