### ISSUE TITLE
默认的图片可以生效，但是自定义的就不行了

### ISSUE THREAD

**Issue by YuArtian** [shalldie/vscode-background#151]
![image](https://user-images.githubusercontent.com/16103819/56074073-dd64bb80-5dde-11e9-8459-60248efe1ab1.png)
![image](https://user-images.githubusercontent.com/16103819/56074081-09803c80-5ddf-11e9-8543-21e9de8a78df.png)

**Comment by shalldie** [comment]
自定义图片的路径有点问题，你看编辑器都标红了。

你可以把图片拖到浏览器里面，然后从地址栏复制下来。

**Comment by YuArtian** [comment]
@shalldie 啊！果然。。。多谢！
