### ISSUE TITLE
插件不受支持

### ISSUE THREAD

**Issue by yoohohoho** [shalldie/vscode-background#154]
![image](https://user-images.githubusercontent.com/42197115/56723426-85816980-677b-11e9-9442-73692ad83fee.png)
![image](https://user-images.githubusercontent.com/42197115/56723466-97630c80-677b-11e9-9587-aa7b1b0fda6a.png)

**Comment by shalldie** [comment]
请看这里： https://github.com/shalldie/vscode-background#warns-%E8%AD%A6%E5%91%8A

**Comment by maple3142** [comment]
這可以用 https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums 來讓那個文字消失

**Comment by shalldie** [comment]
原因如上述，现在readme的 Q&A 中也添加了解决 [不受支持] 的这个链接。这个issue就关闭啦
