### ISSUE TITLE
windows上默认图片都不显示

### ISSUE THREAD

**Issue by ikimiler** [shalldie/vscode-background#155]
![image](https://user-images.githubusercontent.com/13508482/56731366-e36a7d00-678c-11e9-949f-6ce1d09c426f.png)
是什么情况啊

**Comment by shalldie** [comment]
应该是木有权限吧，第一次打开vscode用【右键】-【以管理员身份运行】

https://github.com/shalldie/vscode-background/issues/120

**Comment by ikimiler** [comment]
> 应该是木有权限吧，第一次打开vscode用【右键】-【以管理员身份运行】
> 
> #120
果真是哦，谢谢拉
