### ISSUE TITLE
After uninstalling the plugin the background image left

### ISSUE THREAD

**Issue by Riim** [shalldie/vscode-background#16]
After uninstalling the plugin the background image left. How to remove it?

**Comment by shalldie** [comment]
Before you uninstall this extension, you can add "background.enabled": false in your user setting.json, then restart the editor, and the background will been removed. Now you can uninstall this extension and your vscode will be restored.

It's a way,but not feel good.

I‘m looking for a way to addeventlistener while the extension is being uninstalled.

**Comment by Riim** [comment]
Thanks.

**Comment by vitorsmends** [comment]
Where can i found this archive(setting.json)? @shalldie
