### ISSUE TITLE
[Ubuntu 18.04] Extension doesn't work

### ISSUE THREAD

**Issue by ichirou2910** [shalldie/vscode-background#162]
I'm using vscode 1.35.1 and downloaded extension ver 1.1.19. When i executed chmod/chown command it said "read-only file system". Is there anyway to fix this? The ext. works fine in windows.
Here's the screenshot: https://imgur.com/Qc3U6Ou

**Comment by shalldie** [comment]
try this: https://github.com/shalldie/vscode-background/issues/120#issuecomment-472355120

**Comment by ichirou2910** [comment]
![image](https://user-images.githubusercontent.com/51302893/60418739-e612a400-9c0d-11e9-917e-1652384fdeec.png)
sadly it didnt work :(

**Comment by shalldie** [comment]
Sry i've never used vscode in ubuntu 😂😂

there's some way to make it work in ubuntu, hope it can help you.

https://github.com/shalldie/vscode-background/issues/6

**Comment by ichirou2910** [comment]
I read through that before i commit this issue, so sad i cannot use this ext in ubuntu, still great ext tho.

**Comment by Pioneer-Linzi** [comment]
需要把  useDefault 改为 false 就可以了

**Comment by ichirou2910** [comment]
Ok so the problem lies in the location of vscode. I reinstalled it to another location and it worked. Tks to #6

**Comment by fauzan-radji** [comment]
> Ok so the problem lies in the location of vscode. I reinstalled it to another location and it worked. Tks to #6

How do you do that?
