### ISSUE TITLE
安装后 vscode 崩溃

### ISSUE THREAD

**Issue by yuicer** [shalldie/vscode-background#165]
![image](https://user-images.githubusercontent.com/23371475/62451276-7f4e5080-b7a0-11e9-911b-e36aaa7adb71.png)
安装完插件后重启就这样了

macos mojave 10.14.15
language: english

**Comment by yuicer** [comment]
我好难受啊。。。

**Comment by shalldie** [comment]
不好意思，你可以重新安装一下vscode来解决这个问题。

产生该问题的原因大概是写入的时候发生错误，概率非常非常低所以我就没加 try catch =。=

下个版本加上这个吧

**Comment by yuicer** [comment]
。。。。。重装 vs code 成本也太大了。。。。。。。。。。。。。。。。

黑了

**Comment by shalldie** [comment]
好的吧，我感觉mac上装软件挺方便的，拖一下就好，，配置也不会丢失。

不好意思带来不好的体验。

**Comment by yuicer** [comment]
并没有。。。我重装依然是这个bug，感觉要清配置文件

**Comment by shalldie** [comment]
我的重装，指的是，把[vscode]这个应用程序删掉，然后打开安装包把这个应用再拖出来。

这个时候打开vscode是全新的，没有受到任何更改。

此时你可以参考 [uninstall](https://github.com/shalldie/vscode-background#uninstall-%E5%8D%B8%E8%BD%BD) 来进行卸载

**Comment by yuicer** [comment]
是我没正确删除 vscode ，正确删除再安装之后 vscode 已经正常了。

不过挺好奇我蹦的原因，看 166k 下载和其他衍生项目都没这个问题。我去翻翻代码

**Comment by shalldie** [comment]
时隔多年，，，找到了崩溃的原因并fix之。 https://github.com/shalldie/vscode-background/issues/329
