### ISSUE TITLE
关于图片style的配置说明文档欠缺

### ISSUE THREAD

**Issue by sfc9982** [shalldie/vscode-background#166]

**Comment by shalldie** [comment]
这个style是css样式，如果是fe的话应该都知道吧，其他方向的程序员大概要查一下。

**Comment by tangyefei** [comment]
只给个示例就好，不然以为是用别的语法写的。

**Comment by tangyefei** [comment]
"background.useDefault": false,
    "background.customImages": ["https://cn.bing.com/th?id=OHR.WorldOctopus_ZH-CN2670477302_UHD.jpg"],
    "background.styles": [{"background-size":"cover"}],

**Comment by tangyefei** [comment]
A sample in setting.json: 
```
"background.useDefault": false,
"background.customImages": ["https://cn.bing.com/th?id=OHR.WorldOctopus_ZH-CN2670477302_UHD.jpg"],
"background.styles": [{"background-size":"cover"}],
```
