### ISSUE TITLE
1.38 Insiders版本更改了css文件名称

### ISSUE THREAD

**Issue by AShujiao** [shalldie/vscode-background#167]
抽时间同步下吧看你好久都没更新了。。
 [Update css path for vscode 1.38](https://github.com/vscode-extension/vscode-background-cover/pull/20)

**Comment by shalldie** [comment]
嗯好的多谢。
因为一直能用所以一直没更新，，，这个我明天看一哈

**Comment by shalldie** [comment]
已经发布 :tada::tada:
