### ISSUE TITLE
行号背景和文本背景不一致

### ISSUE THREAD

**Issue by leomikezee** [shalldie/vscode-background#17]
换用Atom主题后，行号背景和文本背景不一样，而且Atom主题的背景被覆盖了
如图
<img width="1440" alt="screen shot 2016-10-09 at 1 53 49 pm" src="https://cloud.githubusercontent.com/assets/7655600/19222490/d302285a-8e27-11e6-8658-e165f361ad27.png">

**Comment by shalldie** [comment]
这个主题的全称是什么呢？ 我去看一下

**Comment by leomikezee** [comment]
@shalldie 市场里有三个 One Dark 主题，每个都有这种情况。VSCode 自带的部分主题，像 Solarized 也是这样。

**Comment by shalldie** [comment]
确实是有这种情况。
代码区域是一个遮罩层，这个不去掉背景显示不出来，，，

目前还没有好的想法，我会尝试去寻求解决方式

**Comment by shalldie** [comment]
刚刚翻到这个issue，现在使用前景图，已经木有问题了
