### ISSUE TITLE
vscode现已支持最多拆分8个窗口

### ISSUE THREAD

**Issue by LiarOnce** [shalldie/vscode-background#171]
![image](https://user-images.githubusercontent.com/11171892/64758497-4ce5ff00-d567-11e9-95c0-0e7b35a109a2.png)

所以自定义图片什么时候支持更多自定义图片😂

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/65295539-4b828b00-db94-11e9-8c9a-c48a5d26dfd1.png)

这是18年7月的截图，蛮早就能切割成超多窗口了。
但是觉得切割太多没有必要加图片，因为多了窗口就小了，图会影响正常观看。
其次跟前3张搭配的默认图也不好找。
最后，因为这些不常用，包括婵模式啊balabala的，，，
，，，综上所述，就懒得弄了 hhh

**Comment by LiarOnce** [comment]
确实是我火星了😂
