### ISSUE TITLE
terminal会把图片顶上去

### ISSUE THREAD

**Issue by Eve-1995** [shalldie/vscode-background#172]
VSC一般都要开一个底部的terminal, terminal有时候还要调整高度看不同的内容. 

这个时候背景图就会被顶上去了, 能不能让terminal直接遮挡图片而不是顶上去呢

**Comment by shalldie** [comment]
这个插件的定义就是代码编辑区域背景图。

如果想要整个编辑器背景图可以看看这个： https://github.com/vscode-extension/vscode-background-cover
