### ISSUE TITLE
It's still there

### ISSUE THREAD

**Issue by Mustafa-Hayati** [shalldie/vscode-background#173]
Hi, I uninstalled this extension, but it's still there. How can I remove it permanently?

**Comment by shalldie** [comment]
@Mustafa-Hayati 

Pls see here: 

[Why ?](https://github.com/shalldie/vscode-background#warns-%E8%AD%A6%E5%91%8A)

[How to uninstall](https://github.com/shalldie/vscode-background#uninstall-%E5%8D%B8%E8%BD%BD)

I suggest that:
1. install this extension.
2. set the config  {"background.enabled": false}  in settings.json
3. uninstall the extension.

**Comment by Mustafa-Hayati** [comment]
thanks for answering but how can I change the true to false. Because it says cannot edit in read only editor. can you suggest an article or something?
thanks

**Comment by shalldie** [comment]
emm,,, if in a read only editor, this extension can't work at the first time :D

Here is [How to add authority](https://github.com/shalldie/vscode-background/issues/120)

But i suggest that, the easiest way to resolve it is that, <strong> reinstall vscode </strong>.
Which won't waste some time, please use this way.

**Comment by Mustafa-Hayati** [comment]
Thank you so much
