### ISSUE TITLE
need compatible with web platform

### ISSUE THREAD

**Issue by Luoyayu** [shalldie/vscode-background#175]
The current version is not compatible with web platform.
In web  platform, the css file hacked may be `workbench.web.api.css`, I test with **code-server**, update the css path is enough, so regex may be a better choice.

**Comment by shalldie** [comment]
😂😂  considering

**Comment by snowme34** [comment]
The said modification to the js file still works for [coder server 3.4.1](https://github.com/cdr/code-server).

Also if the code is open as a chrome app, may need to use developer tool to clear the cache for the css file.

For reference, the one line to change is in `code-server/extensions/shalldie.background-1.1.23/out/vscodePath.js`
