### ISSUE TITLE
Background Wont GO AWAY

### ISSUE THREAD

**Issue by altimmons** [shalldie/vscode-background#177]
Once Disabled, the background stays.  In other workspaces where the extension isnt used then background comes on.  When uninstalled the background stays.

And the DEFAULT PICTURE IS HORRIBLE.  If it were more normal then it would be tolerable.  But I cant have some underage hentai girl always popping up in the background.  Please make it behave.

**Comment by altimmons** [comment]
Seriously.  Even after uninstalling, it stays.  Im gonna have to delete the entire application

**Comment by shalldie** [comment]
https://github.com/shalldie/vscode-background/issues/173

Sry, but u can find why and how to fix it in readme. 
Perhaps it help u.

**Comment by altimmons** [comment]
I tried that. Set background to false. Even changing user data directory to an entirely new one`code —user-data-dir <new dir>` it remains.  Even deleting one of the images - it remains. 

Where is it pulling the other images from?  I’ve searched for https links. It’s a persistent little bastard. I’ll give you that.  There appears no way to undo the extension. Even reinstalling the extension and supplying other images- which used to work - fails.

**Comment by willstocks** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/43744514/68682038-63570980-055c-11ea-82cd-e77ea980aeba.png)

I have run as admin, I have uninstalled the extension, I have restarted VSCode numerous times... I don't understand how this image can persist if the extension is uninstalled...

**Comment by willstocks** [comment]
I just started VSCode with DevTools open and on the Network tab and I can see that this is a data url (base64 png) that is being cached by VSCode...
![image](https://user-images.githubusercontent.com/43744514/68682837-ae255100-055d-11ea-88b0-11be6268d6e5.png)

I tried clearing _all_ VSCode caches... nothing! I'd prefer to not have to fully uninstall and reinstall VSCode where possible.

@shalldie - what can we do to remove this image? I use VSCode in both a personal and professional environment and this image is **not** professional.

**Comment by shalldie** [comment]
### Case1: when extension installed
steps:
1. set `"background.enabled": false` 
2.  then uninstall the extension

### Case2: when extension uninstalled before set the config
there's two ways:
1. install this extension, then goto Case1.
2. reinstall vscode.

**Comment by willstocks** [comment]
Hi @shalldie 
What do you do when you complete Case1, but it still does not work?
I set `"background.enabled": false` before uninstall and still I'm seeing the background.
Do I just have to do Case2 item 2? Is that the _only_ option?

**Comment by shalldie** [comment]
It's strange, i've tried macos and windows just now, it works.

when set `"background.enabled": false` , then save ,it should notice u to restart, like this:

![clearbg](https://user-images.githubusercontent.com/9987486/68692497-932ffc80-05b0-11ea-99e2-3ec88322723d.gif)

@willstocks is there any message in DevTools's console panel?

---

If you don't wan't to reinstall (i think reinstall is the fastest way,,,which waste only 1 minute.), you can edit `Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css`, 

delete code from `/*css-background-start*/` to `/*css-background-end*/`

**Comment by Mustafa-Hayati** [comment]
It's the same problem that I had . I think I solved it this way: Search the `workbench.desktop.main.css` file in the folder that you've installed the vscode, open it in vscode and then using `Ctrl + F` find `/*css-background-start*/` then select it and delete all the lines until `/*css-background-end*/` . Then **reinstall vscode**. I think it worked for me, but I'm not sure if this was the solution or not.

**Comment by Korywon** [comment]
I don't understand the design decision, but when you uninstall the extension, it doesn't truly get uninstalled. I assumed that when you uninstall the extension, it removes everything, but the moment I remove the `"background.enabled"` line, the extension suddenly pops up, even after uninstall.

So, what I had to do was set `"background.enabled": false`, navigated to my `.vscode/extensions`, and then deleted the extension (starts with shalldie, or something similar) folder, and then restarted.

**Comment by shalldie** [comment]
@Korywon 

This extension works by hooking the vscode's system css file, so when extension uninstalled, the css file is still been edited.
U can find how it works and how to uninstall in README.md.

The right way to uninstall is to set `"background.enabled": false` at first, then uninstall the extension.

**Comment by Fensterbank** [comment]
Just wondering, isn't there an "extension uninstall event" or "extension disable event" in VS Code, so the extension could clean up and revert all changes in the css file it has done?
Otherwise issues like this won't stop to come up.

**Comment by mewabm** [comment]
this is BS man, it stuck like fly on a s@#$

**Comment by altimmons** [comment]
yea, I had to uninstall AND delete every shred of cached data and blow out everything. 
I really don't know where the damn thing hides.  I've looked and looked.  But I just threw away all my settings and started over months ago.  I had a really nice custom setup, but anime girls very much aren't my thing and it wasn't tolerable that my family might walk by.
I no longer mess with customizing the look of my VS code.
I am positive I even tried the way he said,  Re installing, disabling, and then whatever-  Then it seems you now have 2 copies.  The one that turns off and on, and the one that is there underneath that one. So you know...

**Comment by NoDocCat** [comment]
@altimmons 
If vscode provides related api, this plugin will not use hack method.
If this plugin is malware, no warning will be issued in README.md.

> This extension works by editting the vscode's css file

At the same time, the author also reminded that the modification is only in workbench.desktop.main.css

**Comment by Fensterbank** [comment]
> I had a really nice custom setup, but anime girls very much aren't my thing and it wasn't tolerable that my family might walk by.

But the images are customizable. The first thing I did was replacing these anime girls by Son Goku, Piccolo, Cell and other DBZ characters so I would look serious and professional for my customers and colleagues. 👨‍💼

> I really don't know where the damn thing hides

I manually removed it by editing the specific css file `workbench.desktop.main.css` manually . Wasn't difficult and VS Code users (which mostly are Tech-savvy) should be able to do something like this without format c and reinstallt Windows or something 😉

**Comment by joelbarranteswins** [comment]
Default picture is horrible, i had to come to solve my problem...
Can't be empty default image?

**Comment by Mohammad-Noor-debug** [comment]
So if you scroll down it shows you how to uninstall it, press f1 to activate the command palette and then write background uninstall extension, it just uninstalls it, all you need to do afterwards is restart vs code

**Comment by AndRad07** [comment]
the following worked for me:
1) make sure it's installed
2) Go to Extension --> select "background"  --> small settings icon --> Extension Settings
3) Unselect Background: Enabled and Background: Use Default
4) Reload

**Comment by Rubay3t** [comment]
This is how I solved mine. But first make sure it's installed. If you got annoyed and deleted the extension then install it again. Then follow the steps below.

Steps : 
1. In VS code editor open up the settings. (Ctrl+,)
2. In the "user" tab you will see "extensions".
3. From there go to "background". Uncheck the box named "Plugin background enabled".
4. You will be asked to restart vs code. Click on restart and your background image will be removed.

**Comment by shalldie** [comment]
> This is how I solved mine. But first make sure it's installed. If you got annoyed and deleted the extension then install it again. Then follow the steps below.
> 
> Steps :
> 
> 1. In VS code editor open up the settings. (Ctrl+,)
> 2. In the "user" tab you will see "extensions".
> 3. From there go to "background". Uncheck the box named "Plugin background enabled".
> 4. You will be asked to restart vs code. Click on restart and your background image will be removed.

@Rubay3t 
Yeeh,  as described in the doc: https://github.com/shalldie/vscode-background#uninstall
If deleted the extension, you can follow this:

> 3. An unfriendly way:
> 
> If you uninstall this plugin directly, don't worry.
> Exit vscode completely, then open, then reload. Now it's clean :D
> (I know it's strange... Because of the limit of vscode)

**Comment by technoadnan** [comment]
Hello guys, I figure out a way to delete the background Image. I used this extension [background by Katsute](https://marketplace.visualstudio.com/items?itemName=Katsute.code-background)

**Steps**

- ctrl/cmd + shift + p
- Background configuration
![image](https://github.com/shalldie/vscode-background/assets/73870020/176953de-d2da-4473-9003-8fe070983383)
-  click uninstall background
![image](https://github.com/shalldie/vscode-background/assets/73870020/1f0250ea-d134-4636-94ee-5aa3f4203c9a)
- close and open the vscode again

**Comment by shalldie** [comment]
All friends who come here can view the documents here：[Disable/Uninstall doesn't remove background images](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.md#disableuninstall-doesnt-remove-background-images)
