### ISSUE TITLE
"background.customImages":Array<String>里面是要填一个什么东西的说QAQ

### ISSUE THREAD

**Issue by CharlotteFallices** [shalldie/vscode-background#178]

**Comment by shalldie** [comment]
这是一个字符串数组，自定义图片的路径，比如：

```json
"background.customImages": [
    "https://xxx1.jpg",
    "https://xxx2.jpg",
    "https://xxx3.png"
]
```

**Comment by CharlotteFallices** [comment]
诶?
可是......
![捕获](https://user-images.githubusercontent.com/47619464/69341968-82b10d80-0ca5-11ea-9286-a239c6d0579b.PNG)
emmmmmm......

**Comment by CharlotteFallices** [comment]
嘤!

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/69342074-bf7d0480-0ca5-11ea-819c-0c1464a4c7cd.png)

默认是使用默认图片，需要设置为false

**Comment by CharlotteFallices** [comment]
哇呜......QAQ
![捕获1](https://user-images.githubusercontent.com/47619464/69342722-2353fd00-0ca7-11ea-945f-7f2c1f4a080b.PNG)

**Comment by shalldie** [comment]
enabled:false 表示不启用插件 QAQ  文档在 README.md

**Comment by CharlotteFallices** [comment]
emmmmmm......
![捕获2](https://user-images.githubusercontent.com/47619464/69346054-1d611a80-0cad-11ea-8bd3-d50e3d9e00cb.PNG)
打扰了吖QAQ
