### ISSUE TITLE
Candidate as official feature

### ISSUE THREAD

**Issue by Siccity** [shalldie/vscode-background#182]
Hello. I'm writing here since this is the most popular plugin for adding custom images to VSCode.

Just recently, official support for this feature has become a possibility. If 20 people upvote this issue https://github.com/microsoft/vscode/issues/84120 it will be added to the backlog.

**Comment by shalldie** [comment]
Happy to get the message 💕  

There must be lots of people who are glad to see this ~

**Comment by Siccity** [comment]
Good news! It moved to the backlog. Thanks for the support :)
