### ISSUE TITLE
请问作者有考虑添加“随机加载图片”这一功能么？

### ISSUE THREAD

**Issue by happysky-12** [shalldie/vscode-background#184]
打扰了。插件用着挺好的，只是好奇问下。因为图片最多可以加载三张，但顺序是固定的。所以想问问有没有什么办法能使得每次启动时能显示不同的图片。

**Comment by shalldie** [comment]
目前没有打算添加这个功能。

你可以看看这个项目：https://github.com/JeniTurtle/vscode-background-auto-switch

**Comment by happysky-12** [comment]
谢谢。那个项目我用过，可惜在图片的设置上只能更改透明度。最后自己搞了个调换文件名的批处理文件，算是解决了吧。
