### ISSUE TITLE
默认背景存在未抠去的白色背景

### ISSUE THREAD

**Issue by Lutalli** [shalldie/vscode-background#185]
默认背景的第一张 (魔理沙的那一张) 下面有一部分似乎没有抠掉, 希望能改一改!

![image](https://user-images.githubusercontent.com/47910890/74402593-a8425300-4e5f-11ea-968f-36b7c6ab67b8.png)

**Comment by shalldie** [comment]
啊是的，下次上线的时候带上去

**Comment by shalldie** [comment]
不骗你这段时间忙成狗。
今天找了个美工朋友帮忙把图扣了，看着还挺ok的

**Comment by Lutalli** [comment]
十分感谢☆
