### ISSUE TITLE
怎么调透明度啊

### ISSUE THREAD

**Issue by Lewis-312** [shalldie/vscode-background#186]
怎么调缩放啊
![DKX6HOJ1AP2G T)%S{CKU5E](https://user-images.githubusercontent.com/52613453/74520626-e9675f80-4f52-11ea-8121-57d95227a901.png)

**Comment by shalldie** [comment]
使用的 css 样式，可以参考：
```json
"background.style": {
    ...
   "background-position": "100% 100%", // 图片位置
   "background-repeat": "no-repeat", // 是否重复
   "opacity": 0.6, // 透明度
   "background-size": "300px 434px" // 大小
}
```

感觉你的 `background.style` 的配置有些乱，可以删了重新写

**Comment by shalldie** [comment]
没有其它问题我就关了哈

**Comment by Lewis-312** [comment]
okok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xieshuang"<notifications@github.com&gt;; 
发送时间: 2020年3月25日(星期三) 中午12:11
收件人: "shalldie/vscode-background"<vscode-background@noreply.github.com&gt;; 
抄送: "2644685501"<2644685501@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shalldie/vscode-background] 怎么调透明度啊 (#186)





 
没有其它问题我就关了哈
