### ISSUE TITLE
请问有“一张图片重复N次，铺满整个背景”的设置或者功能么？

### ISSUE THREAD

**Issue by yumindeckard** [shalldie/vscode-background#187]
可能需要一张小图片，但要求此图片重复无数次，直到铺满整个background

谢谢

**Comment by shalldie** [comment]
配置使用的css样式，可以使用 `background-repeat: repeat`

```json
"background.style": {
     ...
    "background-repeat": "repeat"
}
```

https://developer.mozilla.org/zh-CN/docs/Web/CSS/background-repeat

**Comment by yumindeckard** [comment]
Thanks
