### ISSUE TITLE
全屏背景

### ISSUE THREAD

**Issue by Redcxx** [shalldie/vscode-background#189]
感觉非常好用啊，能自己调css就很开心。
如果有办法做成除了标题栏以外都覆盖的背景就更好了，像jetbrains那种。
十分感谢。

**Comment by shalldie** [comment]
有另外一个插件支持该功能，你可以先看看是否满足需求：
https://github.com/vscode-extension/vscode-background-cover

**Comment by Redcxx** [comment]
的确是那种效果，不过感觉那个插件没有这个灵活。。

**Comment by shalldie** [comment]
谢谢称赞 😂😂

那种全屏模式跟现在的配置差异比较大，相当于另外一个插件了。
所以目前没有兼容全屏模式的打算。

**Comment by Redcxx** [comment]
好的没问题，其实现在已经很好了。
