### ISSUE TITLE
vscode1.6开始会提示Your Code installation appears to be corrupt. Please reinstall

### ISSUE THREAD

**Issue by grasssand** [shalldie/vscode-background#19]
测试win10 x32 vscode1.6.1 全新安装环境
![ashampoo_snap_2016 10 14_08h59m03s_002_untitled-1 - visual studio code- -](https://cloud.githubusercontent.com/assets/11460505/19372244/a63f48f2-91ec-11e6-8cb1-10213c5ac3bb.jpg)

**Comment by moonou** [comment]
macOs 也会出现

**Comment by shalldie** [comment]
刚刚去官网看了一下，新版本的vscode，会检测自身文件是否修改过。
当前使用的是代码注入的方式修改背景。

建议先点击【不再显示】，我会尽快尝试解决这个问题。

**Comment by grasssand** [comment]
@shalldie 好的 感谢

**Comment by vsTianhao** [comment]
我也遇到这个问题，请问现在还是以代码注入的方式修改背景吗，可能影响了vscode[此次更新](https://code.visualstudio.com/updates/v1_30)的[新特性](https://code.visualstudio.com/updates/v1_30#_html-custom-tags-attributes-support)

**Comment by GpingFeng** [comment]
试了一下，可以用这个插件解决

https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums

来源：https://stackoverflow.com/questions/61028032/installation-appears-to-be-corrupt-unsupported-visual-studio-code
