### ISSUE TITLE
安装后导致vscode崩溃

### ISSUE THREAD

**Issue by 707250131** [shalldie/vscode-background#190]
安装后  vscode崩溃了 ,  打开vscode  页面全是乱的;

**Comment by shalldie** [comment]
不好意思，你需要重新安装一下vscode。

在一年多前也有人遇到过，这个概率太低了，，，我无法重现  😂😂

**Comment by 707250131** [comment]
我找到原因了，安装后，workbench.desktop.main.css 这个文件被修改了  #， 变成了一大堆字母拼音组成的玩意；     我从其他同事拷了一份这个文件后 就恢复了  ； @shalldie

**Comment by shalldie** [comment]
嗯，，能解决就好。

**Comment by 707250131** [comment]
这算不算是个bug   希望早日修复吧

**Comment by shalldie** [comment]
@RickyLiu0w0 
重装最稳，，，放仓库里我也很难及时同步版本，还要区分web还是客户端。

实在难以复现，不过这部分考虑过可能的原因，这两天会再发一版本
