### ISSUE TITLE
修改settings后导致其他设置出现问题

### ISSUE THREAD

**Issue by Petrichor-x** [shalldie/vscode-background#191]
![微信截图_20200312223550](https://user-images.githubusercontent.com/41455101/76532829-23744480-64b2-11ea-9cba-ec8496dc265a.png)
修改settings.json后,再修改其它设置，比如说修改主题，就会出现：**Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.**
在vscode官网查询原因如下：
if you try to change a setting (for example turning on Auto Save or selecting a new Color Theme) and you see "Unable to write settings. Please open User Settings to correct errors/warnings in the file and try again.", it means your settings.json file is ill-formed or has errors. The errors can be as simple as a missing comma or setting value. Open the Settings editor File > Preferences > Settings (Code > Preferences > Settings on macOS) (Ctrl+,) and you should see the error highlighted with red squiggles.
如图settings.json中background相关代码总会出现红色波浪线，这个怎么解决

**Comment by shalldie** [comment]
红色波浪线的那行代码不是这个插件的。

看样子好像是配置文件中，某地方语法错误，比如逗号，双引号之类，检查一下是否是漏了或者用了中文标点。

**Comment by shalldie** [comment]
红线部分的词儿虽然有 `background` ，但不是本插件但配置，这个我先关了哈
