### ISSUE TITLE
Background.Images Config

### ISSUE THREAD

**Issue by StefanGreve** [shalldie/vscode-background#194]
Documentation says that `Background.Images` accepts up to three background images, but only the first two will be displayed (the second one repeats infinitely). This is a new error and did not happen before, could be the newest update from VS Code that broke something?

Out of curiosity, how come that only three images can be accepted by this property?

**Comment by shalldie** [comment]
U mean `the 2rd` repeat, and `the 3rd` can't be displayed?

I review it in `ver 1.43.2` and it works well,  can u show your config ?

> Out of curiosity, how come that only three images can be accepted by this property?

Because the max number that tab can be split is 3 in the past，now the number grows， but i think there's no need to add, for most people it's enough.

**Comment by StefanGreve** [comment]
First things first, here are my settings for this extension:
```json
    "background.useDefault": false,
    "background.useFront": false,
    "background.customImages": [
        "D:/画像/VSCodeBackgroundImage/eight.jpg",
        "D:/画像/VSCodeBackgroundImage/nine.png",
        "D:/画像/VSCodeBackgroundImage/six.jpg"        
    ],
        "background.style": {
        "background-position": "center",
        "background-size": "cover",
        "opacity": 0.4
    },
```
What I mean is that only the first two pictures are currently used as background images. I also tried other samples and changed the order of occurrences within the array but as far as I can tell, only the first two images are displayed. Picture this: the first window uses the first background image, and the third (and fourth, etc.) image in repetition. 

|  Window #  |  Image #  |
| ---- | ---- |
|  1  |  1  |
|  2  |  2  |
|  3  |  2  |
|  4  |  2  |
|  5  |  2  |

On a similar note I think I'd be nice to change the selection in a different way

**Comment by shalldie** [comment]
![ddd](https://user-images.githubusercontent.com/9987486/77618514-697cde00-6f71-11ea-903d-9235dfc014a7.jpeg)

---

The version i mean is that:

**vscode version** :   `1.43.2`
**extension background** :   `1.1.23`

---

See the image above, i tried your config and it's my display.

**Comment by StefanGreve** [comment]
Alright, updating VS Code from `v1.43.1` to `v1.43.2` resolves my issue. Thanks for guiding me to a solution! In hindsight, I should have been trying to update the IDE from the very beginning. Well, lesson learned, I guess :)

**Comment by shalldie** [comment]
Nice to hear that.

But i think it should work from `1.42.x` to `lastest` version ... hahaha
Because it was published a long time ago, every time vscode updated, it worked well.
