### ISSUE TITLE
mac上安装插件后，重启vscode，没有生效

### ISSUE THREAD

**Issue by SkyMing1024** [shalldie/vscode-background#195]
系统版本：macOS 10.15.3
vscode版本：1.44.0
安装后，没有反应，重启后插件也没有生效。用的默认配置。

**Comment by shalldie** [comment]
不好意思这段时间忙的跟🐶一样。
我跟我的朋友用着都ok，所以建议你试试以下方案。

1. 可能是权限问题。
参考一下 https://github.com/shalldie/vscode-background/issues/120

2. vscode不要放在下载目录，换个地方(比如你放工具的文件夹，或者 application 目录之类)

**Comment by shalldie** [comment]
这个后来搞定了吗？

**Comment by SkyMing1024** [comment]
你好，感谢回复！
抱歉一直忘记回复。
之前按照[#120 ](https://github.com/shalldie/vscode-background/issues/120)的方法配置了，当时没有生效，这几天看了下居然生效了。哭笑不得
再次**感谢回复**！

**Comment by shalldie** [comment]
👌
