### ISSUE TITLE
自定义图片只设置一张时, 拆分窗口不显示背景图

### ISSUE THREAD

**Issue by NoDocCat** [shalldie/vscode-background#196]
插件版本: 1.1.23

![image](https://user-images.githubusercontent.com/20502666/81187794-14f46600-8fe7-11ea-8241-873a6d7427a7.png)

**Comment by shalldie** [comment]
对啊，只设置一张，就只显示一个，符合预期。

如果想让她重复，就设置3张一样的吧。

**Comment by NoDocCat** [comment]
难道不是应该在这个列表里顺序循环使用吗? 还没那个神奇的三张限制是什么鬼😂

**Comment by NoDocCat** [comment]
而且拆窗口超过三个, 也没背景了啊.

**Comment by NoDocCat** [comment]
简单读了一遍源码, 发现问题了nth-child是可以实现多图循环出现的. 
你看一下我写的demo: https://codesandbox.io/s/hungry-silence-o1y5w?file=/index.html
根据图片数量动态生成一下css就行了, 我先fork一份, 周日写完给你提pr吧.

**Comment by shalldie** [comment]
只设置一张当然不能循环使用啊，如果只想要第一个有图，不想循环怎么办。

3张限制是因为vscode此前只支持最多分3屏，后来才开放了更多分屏。
插件没有跟着升级是因为，一般情况下3屏也够了，也没人有进一步的需求。这个可以加上。

**Comment by NoDocCat** [comment]
PR已提 https://github.com/shalldie/vscode-background/pull/197
加了一个配置项, 开启后才会循环使用图片, 默认情况下与原版相同
