### ISSUE TITLE
code升级之后爆炸

### ISSUE THREAD

**Issue by manageryzy** [shalldie/vscode-background#20]
升级到1.6.1之后背景坏了

**Comment by shalldie** [comment]
会提示vscode文件损坏，，，

询问过vscode团队，目前不推荐修改样式文件，每次运行vscode会检测文件是否呗修改过。

如果要继续使用本插件，可以在提示损坏的时候，选择【不再提示】。

我打算把这个插件转型成主题  =。=

**Comment by KNCheung** [comment]
无意中找到一个方法：
设置中加入一行："css.validate": false,

**Comment by shalldie** [comment]
可以在 settings.json 中添加： 
"css.validate": false

**Comment by Jackiemmmmm** [comment]
升级1.7.1的vscode后，setting.json设置后，没有任何效果，也没有1.6.1的 文件损坏 的提示。

**Comment by shalldie** [comment]
请试试开启管理员权限，我这里mac跟win下没问题
