### ISSUE TITLE
[Ubuntu 20.4 LTS] Extension doesn't work

### ISSUE THREAD

**Issue by TyNguyen2k1** [shalldie/vscode-background#202]
I tried #6, the command works but vscode-background doesn't seem to work. Thanks for the help!
![Screenshot from 2020-06-27 14-59-47](https://user-images.githubusercontent.com/64082226/85917734-e6786600-b886-11ea-9118-9a9054510ee9.png)

**Comment by jacekgajek** [comment]
Same here

**Comment by TyNguyen2k1** [comment]
> You have to install vscode via download page as a deb package. The extension works by modifying a css file inside installation directory, but Snaps are read-only.

So how can I authorize it? Thanks you !

**Comment by jacekgajek** [comment]
You cannot modify files inside a snap - they are like sealed archives. You need to install vscode as a normal application. If you did, then you have to grant access to .css file to yourself 
First, find the file:
`find / -name "workbench.desktop.main.css"`
Then
`sudo chown ${whoami} [location of the css file]`

**Comment by TyNguyen2k1** [comment]
> You cannot modify files inside a snap - they are like sealed archives. You need to remove snap and reinstall vscode as a normal application from a .deb package (https://code.visualstudio.com/download)
> 
> If you already did, then you have to grant access to .css file to yourself
> First, find the file:
> `sudo find / -name "workbench.desktop.main.css"`
> Then
> `sudo chown ${whoami} [location of the css file]`

Am I doing it right?
![Screenshot from 2020-09-27 22-50-12](https://user-images.githubusercontent.com/64082226/94369473-092f4a80-0114-11eb-9a14-afe5e34a482e.png)

**Comment by jacekgajek** [comment]
Well I guess not :) I'm not on linux now so I cannot tell more. `sudo chown ty "path"` should work...

**Comment by TyNguyen2k1** [comment]
> Well I guess not :) I'm not on linux now so I cannot tell more. `sudo chown ty "path"` should work...

Anyway, it still works, thank you !!!
![Screenshot from 2020-09-28 00-34-27](https://user-images.githubusercontent.com/64082226/94371674-67632a00-0122-11eb-8b27-1943c84ab131.png)

**Comment by GladeCant** [comment]
It works fine, thank you !
