### ISSUE TITLE
question: does this extension works with any theme?

### ISSUE THREAD

**Issue by jpmolinamatute** [shalldie/vscode-background#204]
Hello!

I think this is a must to have extension. however, I think I'm missing a setting in my config file because it's not working for me :-(
this is what I have so far, what am I missing? BTW: I have restarted vscode every time I changed the setting file just in case
```
 "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "100% 100%",
        "background-repeat": "no-repeat",
        "opacity": 0.5,
        "background.useDefault": false,
    },
    "background.customImages": [
        "https://lumiere-a.akamaihd.net/v1/images/ahsoka-shattered_562021ce.jpeg?region=0%2C0%2C1280%2C544"
    ]
```

**Comment by shalldie** [comment]
Sry for late response,too busy for my work these days.

Your `"background.useDefault": false,` shouldn't be inside `background.style`.

`"background.useDefault": false,` means you can use yourself customImages, `background.style` is for custom style of images.

**Comment by jpmolinamatute** [comment]
Hey @shalldie ! no worries, Thanks for the help, I totally appreciate it, I have been busy as well.

 I updated my settings.json file and then I started getting this error 

```
Activating extension 'shalldie.background' failed: EACCES: permission denied, open '/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.css'. abstractExtensionService.ts:411
```

**Comment by shalldie** [comment]
Please see here: 

[how to add authority](https://github.com/shalldie/vscode-background/issues/120)

[Why need authority](https://github.com/shalldie/vscode-background#warns-%E8%AD%A6%E5%91%8A)
