### ISSUE TITLE
Mac下Vscode安装之后，插件不起作用；

### ISSUE THREAD

**Issue by hyrlh** [shalldie/vscode-background#207]
配置：
![image](https://user-images.githubusercontent.com/13246225/88764540-b71b8880-d1a7-11ea-8eeb-ef667756dc39.png)

权限问题（已执行）：
如果vscode版本>=1.38：
chmod +rw "Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css"

**Comment by LCAR979** [comment]
customImages的路径从/Users开始试一下

**Comment by shalldie** [comment]
可以把图片拖到浏览器，然后从地址栏复制图片地址。
