### ISSUE TITLE
Adjusting Picture

### ISSUE THREAD

**Issue by peacendlovu** [shalldie/vscode-background#208]
my picture only shows the centre, how can i resize to show full size

**Comment by RogerLan1998** [comment]
"background-size":"cove",

**Comment by peacendlovu** [comment]
still doesn't work, here are my settings

**Comment by RogerLan1998** [comment]
Sorry, I returned a few more words
This is right

"background-size":"cover",

**Comment by abhinavG37** [comment]
Any way to make the background extend to fit the whole window rather than the editor workspace? I lose the background if I split the editor left/right etc. Thanks!

**Comment by RogerLan1998** [comment]
Try this configuration

    "background.style": {
        "content":"''",
        "pointer-events":"none",
        "position":"absolute",//图片位置
        "width":"100%",
        "height":"100%",
        "z-index":"99999",
        "background.repeat":"no-repeat",
        "background-size":"cover",//图片大小
        "opacity":0.4 //透明度
    },
    "background.useFront": true,
    "background.useDefault": false,
    //是否使用默认图片
    "powermode.enabled": true,
    "update.mode": "start",
    "tabout.disableByDefault": true

**Comment by abhinavG37** [comment]
Works well!

**Comment by shalldie** [comment]
@peacendlovu have a try?
