### ISSUE TITLE
Mac每次VSCode更新后都要重新设置读写权限

### ISSUE THREAD

**Issue by GanahaHibiki** [shalldie/vscode-background#209]
Mac上每次VSCode版本更新后都会默认恢复只读，需要重新添加写权限
有没有什么一次性解决的方法？
OS X版本10.15.6

**Comment by shalldie** [comment]
说实话我没遇到过，，，

vscode是否是放在【下载目录】呢？可以移到【application】里面。
参考：https://github.com/shalldie/vscode-background/issues/252
