### ISSUE TITLE
背景图片在代码预览那里不显示啊

### ISSUE THREAD

**Issue by JingxinLee** [shalldie/vscode-background#212]
背景图片只在代码区有, 代码预览那一栏没有呢,请问作者应该怎么设置呢?谢谢

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/92461857-5054aa80-f1fc-11ea-8af3-62715db28fe5.png)

`"background.useFront": true` 默认 true，
表示在代码上方，也在 minimap 上方。
如果是 `false` 的话就可能被 minimap 遮住

**Comment by JingxinLee** [comment]
非常感谢
