### ISSUE TITLE
这个bug是真服了

### ISSUE THREAD

**Issue by hzq-up** [shalldie/vscode-background#217]
如果没有node环境，需要在 settings.json 中设置 {"background.enabled": false} ，然后再删除插件。如果直接删除插件会有遗留，就需要重装vscode了。

还没看到这个提示，就卸载了，然后再装这个插件背景图片就换不了了，卧槽了，作者可以想办法修复这个bug不

**Comment by shalldie** [comment]
可以再次安装这个插件，然后对图片进行调整，或者设置 {"background.enabled": false} 进行删除。

**Comment by hzq-up** [comment]
试了，不起作用

**Comment by NorthaHuang** [comment]
剛剛遇到同樣的問題，不過我測試過了．

**Comment by NoDocCat** [comment]
> 试了，不起作用

可以考虑从安装包里提取未被修改的 `workbench.desktop.main.css` 手动替换一下

**Comment by higker** [comment]
一样，恶心
