### ISSUE TITLE
mac 下split 之后没有显示

### ISSUE THREAD

**Issue by qiaouchicago** [shalldie/vscode-background#219]
![Screen Shot 2020-10-28 at 9 31 46 AM](https://user-images.githubusercontent.com/68757394/97450144-68919d80-1900-11eb-901d-6fbbeed7287f.png)

**Comment by shalldie** [comment]
`customImages` 是一个数组，如果只包含一张图就只有第一个tab有图。

可以使用 `background.loop` 来使里面的图循环使用。

**Comment by qiaouchicago** [comment]
有没有办法变成这个样子？一张图cover 多个tab？

![Screen Shot 2020-11-04 at 8 08 39 AM](https://user-images.githubusercontent.com/68757394/98121636-2d015100-1e75-11eb-9291-945da437cc58.png)
