### ISSUE TITLE
manjaro下无法使用

### ISSUE THREAD

**Issue by porte233** [shalldie/vscode-background#221]
用**chmod**给予权限后**仍没反应**，不知道是不是我输入的代码有问题

**Comment by NIL-zhuang** [comment]
Manjaro 20.2 Nibia是可行的

**Comment by JunerLee** [comment]
+1 
版本Manjaro 20.2 Nibia

**Comment by JunerLee** [comment]
sudo chmod o+w /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.css
@porte233
