### ISSUE TITLE
Can You Add An Option To Make The Opacity Less For Fonts And SideBy Making More Opacity For Image ?

### ISSUE THREAD

**Issue by RajvirSingh1313** [shalldie/vscode-background#222]

**Comment by RajvirSingh1313** [comment]
I want your reply fast !

**Comment by shalldie** [comment]
Sry for late replay, u don't know how long I work every day...

What you mean is, make image opacity more, and not influence the code?
maybe this can help you:
```json
"background.style": {
        "opacity": 0.5
}
```

**Comment by RajvirSingh1313** [comment]
It helped !
Do you have discord Id I want to talk with you by seeing your efforts and creavity.

**Comment by shalldie** [comment]
I've no discord Id, people use WeChat or QQ in China.
U can tell me your idea or suggestion here.

**Comment by RajvirSingh1313** [comment]
No problem. it is okay
