### ISSUE TITLE
安装插件后vscode的侧边栏样式出现问题

### ISSUE THREAD

**Issue by iamwelk** [shalldie/vscode-background#225]
![image](https://user-images.githubusercontent.com/6983075/101133002-e6a13c80-3642-11eb-8528-208e19985aa2.png)

**Comment by NoDocCat** [comment]
使用的不是默认主题吧, 能够提供一下使用的是哪个主题吗? 
另外请附上关于插件的所有配置,(最好是用设置的 json 视图)

**Comment by zoiiiiii** [comment]
我的是插件禁用按钮样式出错，然后卸载background插件后重启背景图案还是存在

**Comment by NoDocCat** [comment]
> 我的是插件禁用按钮样式出错，然后卸载background插件后重启背景图案还是存在

提交问题请尽量提供配置文件, 并尝试在排除其他插件影响的情况下提供复现方案.

**Comment by zoiiiiii** [comment]
我把vscode重装了，使用了最新版本vscode，使用原装主题还是出现插件禁用按钮样式出错，[如图所示](https://i.loli.net/2021/03/05/Q15zJuMd3mTXnLU.png)，就算卸载background插件背景还是存在并且禁用按钮样式依旧出错。
