### ISSUE TITLE
mac os 安装完不起作用

### ISSUE THREAD

**Issue by bytearth** [shalldie/vscode-background#226]
1. 已经给css添加了权限
chmod +rw /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css

2. 已经使用root打开vscode
sudo /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron 

3. vscode版本
1.52.1

4. 使用开发者工具初步定位
![image](https://user-images.githubusercontent.com/73961492/102710370-c0d79100-42ec-11eb-94e2-195d20b3c337.png)
no such file or directory, open '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css'.
看起来是某个地方使用了错误的地址， 应该是workbench.desktop.main.css, 而不是workbench.main.css

请问我应该如何修改

**Comment by NoDocCat** [comment]
路径判断在 src/vscodePath.ts 里, workbench.main.css是旧版本使用的路径.

**Comment by zhengger** [comment]
> 路径判断在 src/vscodePath.ts 里, workbench.main.css是旧版本使用的路径.

请问OSX完整的配置命令是什么呢？

**Comment by shalldie** [comment]
请看这个，在2楼： https://github.com/shalldie/vscode-background/issues/120

@zhengger

**Comment by zhengger** [comment]
> 请看这个，在2楼： #120
> 
> @zhengger

谢谢，已经设置好了运行正常。
