### ISSUE TITLE
似乎不支持vscode web？

### ISSUE THREAD

**Issue by poor-circle** [shalldie/vscode-background#229]
在code-server的web环境下，似乎无法显示背景图，是这个插件还没有支持吗

**Comment by poor-circle** [comment]
可以手动修复，解决如下：
1.参考 #175 ，修改 扩展插件 中……/code-server/extensions/shalldie.background-1.1.26/out/vscodePath.js，用`workbench.web.api.css`代替'workbench.desktop.main.css'
2.正常配置background
3.清空浏览器缓存，然后再重新打开vscode web，否则不会显示背景图

**Comment by ljcucc** [comment]
會顯示背景，但是永遠是預設的，自訂的圖片網址都不會生效⋯⋯清空Cache後重開網頁也沒用⋯⋯
```json
    "background.enabled": true, 
    "background.useDefault": false,
    "background.customImages": [
        "https://images.unsplash.com/photo-1614253551757-b44ed51c5c50?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1934&q=80",
    ],
    "background.style": {
        "background-position": "center center",
        "background-size": "cover",
        "opacity": 0.2,
    },
    "background.useFront": false,
```

**Comment by shalldie** [comment]
当前版本已经支持了 `code-server`，抱歉来晚了，，，

## 安装

因为code-server的插件市场不更新，所以建议把插件从 vscode market下载下来，再上传到code-server上本地安装。

可以在 [shalldie.background](https://marketplace.visualstudio.com/items?itemName=shalldie.background) 的 [Version History] 下载各个版本。

## 缓存

background 应用后，需要强刷下，避免缓存。

## 权限

这个问题应该都会遇到（初次安装、镜像tag更换、pod重启等），控制台找到报错的文件一路 `cd` 过去，`chmod +w` 之
