### ISSUE TITLE
无法禁用

### ISSUE THREAD

**Issue by tabooc** [shalldie/vscode-background#23]
禁用后依旧是会显示背景图的,除非重装或者找到原始文件workbench.main.css改回去.

**Comment by shalldie** [comment]
需要在【settings.json】中，使用用户配置来禁用：
{
...
"background.enabled": false,
...
}
请确保有管理员权限  :D

**Comment by tabooc** [comment]
如果用vscode自带的禁用是不行的,禁用后settings.json里面的配置项已经被删除了,但是对应改掉过的css并没有替换掉,我个人是手动删除了workbench.main.css里面新增的样式..建议这个插件还是改为主题合适一些.
