### ISSUE TITLE
我想修改vs code输出窗口的字体大小，和控制台窗口不是一回事哟，好像不可行啊

### ISSUE THREAD

**Issue by gitQqqHs** [shalldie/vscode-background#230]
对的，就是vs code的那个输出窗口的文字，文字大小总是和编辑器的字体大小一样，对于信息输出来说，字体很显然太大了。
我需要改下字体，但是试了很多方法都不行，所以就到这里来了。
希望看到作者的回复。
或者，有解决方法的都可以回复哟！！

**Comment by NoDocCat** [comment]
@gitQqqHs 
请善用搜索引擎, 并且不要发与项目无关的 issue
