### ISSUE TITLE
Ubuntu 16.04 安装完不起作用

### ISSUE THREAD

**Issue by wangr-x** [shalldie/vscode-background#231]
vscode 好像不能以管理员权限打开

**Comment by chilin0525** [comment]
ubuntu 20.04 也沒有作用

**Comment by wangr-x** [comment]
我看了下，好像这样就可以用 root 权限打开
`sudo code --user-data-dir /home/user_name/.config/Code/ `
之后在 root 权限下下载，配置插件即可

**Comment by wangr-x** [comment]
总之就是
[一个在Ubuntu（Linux）上解决权限问题的奇怪方法 #131](https://github.com/shalldie/vscode-background/issues/131)

**Comment by chilin0525** [comment]
我這邊照上面的作法也可以了～ Thx

**Comment by chilin0525** [comment]
備註一下:
如果需要更改其他設定也需要在有權限下進行設定

**Comment by nidhoggfgg** [comment]
在 linux 上无需以 root 运行，打开 帮助 --> 开发者工具 --> sources 然后找到 workbench.desktop.main.css ，应该在类似于 /usr/share/code/resources/app/out/vs/workbench/ 的目录下。最后修改该 css 文件权限即可，是在不行直接 chmod 777
