### ISSUE TITLE
Not able to use custom background

### ISSUE THREAD

**Issue by Theirry** [shalldie/vscode-background#232]
Hey there, 
So this is my code of the settings:
![image](https://user-images.githubusercontent.com/47889594/108100763-a3256e80-7086-11eb-86b3-61a6bbdcba29.png)

If I am not mistaken this should be working, right? But it doesn't, and I don't know why. 
The links are working perfectly. If I ask VS code to follow it, it shows me the right image.

Could you help me with this?

**Comment by shalldie** [comment]
`Published shalldie.background@1.1.27`

A new version has been published to solved this question, try it.

**Comment by liuzifengsjtu** [comment]
I still can't use custom background with the release shalldie.background@1.1.27

**Comment by hentai-chan** [comment]
I can confirm that even with the latest update to `v1.2.27` I still run into the same issue.

**Comment by shalldie** [comment]
@liuzifengsjtu @hentai-chan 

1. Drag pictures to browser
2. Copy from address bar，
3. You'll get the file protocol image path as config, which may starts with `file:///`， try it as custom image path.

**Comment by hentai-chan** [comment]
@shalldie Thanks, this resolved my issue. It now works again~
