### ISSUE TITLE
无法添加多张图片

### ISSUE THREAD

**Issue by LvYixuan-0** [shalldie/vscode-background#233]
添加一张以上的图片时除了第一张图片外的图都没有显示`    "background.enabled": true,
    "background.useDefault": false,
    "background.customImages": [
        "D:/Personal/Pictures/bilibili2233.png",
        "D:/Personal/Pictures/bilibiliTV.png"
    ],
    "background.useFront": true,
    "background.styles": [
        {
            "content": "''",
            "pointer-events": "none",
            "position": "absolute",
            "z-index": "99999",
            "width": "100%",
            "height": "100%",
            "background-position": "90% 50%",
            "background-repeat": "no-repeat",
            "background-size": "contain",
            "opacity": 0.2
        },
        {
            "content": "''",
            "pointer-events": "none",
            "position": "absolute",
            "z-index": "99999",
            "width": "100%",
            "height": "100%",
            "background-position": "bottom left",
            "background-repeat": "no-repeat",
            "background-size": "5% %d",
            "opacity": 0.2
        }
    ]`
设置如上

**Comment by NoDocCat** [comment]
`"background-size": "5% %d"` 不是合法的 css 代码

**Comment by LvYixuan-0** [comment]
> `"background-size": "5% %d"` 不是合法的 css 代码
改了以后还是不行qwq

**Comment by LvYixuan-0** [comment]
> `"background-size": "5% %d"` 不是合法的 css 代码

改了以后还是不行qwq

**Comment by NoDocCat** [comment]
![image](https://user-images.githubusercontent.com/20502666/108926407-53900580-7679-11eb-8573-f006d859bbb1.png)

我这里测试是没问题的, 就是按照你的 css 设置显示过小.

尝试在 devtools 中执行: `document.querySelectorAll('.overflow-guard>.monaco-scrollable-element')` 并审查元素的 `::before` 或 `::after`. 看一下是否存在错误.

另外设置中的 style 不要添加全量的, 覆盖你需要修改的就可以了.

**Comment by LvYixuan-0** [comment]
> ![image](https://user-images.githubusercontent.com/20502666/108926407-53900580-7679-11eb-8573-f006d859bbb1.png)
> 
> 我这里测试是没问题的, 就是按照你的 css 设置显示过小.
> 
> 尝试在 devtools 中执行: `document.querySelectorAll('.overflow-guard>.monaco-scrollable-element')` 并审查元素的 `::before` 或 `::after`. 看一下是否存在错误.
> 
> 另外设置中的 style 不要添加全量的, 覆盖你需要修改的就可以了.

我试试

**Comment by LvYixuan-0** [comment]
> ![image](https://user-images.githubusercontent.com/20502666/108926407-53900580-7679-11eb-8573-f006d859bbb1.png)
> 
> 我这里测试是没问题的, 就是按照你的 css 设置显示过小.
> 
> 尝试在 devtools 中执行: `document.querySelectorAll('.overflow-guard>.monaco-scrollable-element')` 并审查元素的 `::before` 或 `::after`. 看一下是否存在错误.
> 
> 另外设置中的 style 不要添加全量的, 覆盖你需要修改的就可以了.

老哥我是设置了两张不一样的图

**Comment by LvYixuan-0** [comment]
> ![image](https://user-images.githubusercontent.com/20502666/108926407-53900580-7679-11eb-8573-f006d859bbb1.png)
> 
> 我这里测试是没问题的, 就是按照你的 css 设置显示过小.
> 
> 尝试在 devtools 中执行: `document.querySelectorAll('.overflow-guard>.monaco-scrollable-element')` 并审查元素的 `::before` 或 `::after`. 看一下是否存在错误.
> 
> 另外设置中的 style 不要添加全量的, 覆盖你需要修改的就可以了.

老哥,我是设置了两张不一样的图

**Comment by NoDocCat** [comment]
问题和图片路径是否重复无关, 每个 url 都是单独生成的. 只要保证 vscode 能通过 url 访问到图片就行.
请提供修改后的配置, 并仔细检查到底是没有显示图片还是 css 设置造成的视觉不可见.

另外不要滥用引用功能, 会对他人造成阅读困难, 而且还会触发邮件通知.

**Comment by LvYixuan-0** [comment]
那么我的问题得改成:如何在一个页面上显示多张照片.
我想在不分列的情况下同时在不同位置显示多张背景

**Comment by NoDocCat** [comment]
插件目前不支持这个功能, 无法从配置让插件生成多 url 的 `background-image`.
目前的工作方式是 url -> bgi: url(${url}).
如果要实现的话, 需要让 `background.customImages` 支持 array item, 并在生成时生成 `bgi: url(${item1}), url(${item2})`, 同时附加其他的样式也需要同步适配.
可以问一下作者有没有支持这个 feature 的意向, 或者你实现后提个 pr.

**Comment by NoDocCat** [comment]
目前来看大概率不会去实现这个 feature, 你可以通过手动修改 `workbench.desktop.main.css` 来实现
参考: https://developer.mozilla.org/en-US/docs/Web/CSS/background-image

**Comment by LvYixuan-0** [comment]
@NoDocCat 俺奉上两张自己抠的图![image](https://github.com/LvYixuan-0/Temp/blob/main/bilibili2233.png)![image](https://github.com/LvYixuan-0/Temp/blob/main/bilibiliTV.png)麻烦你了.
这两张图我抠得挺久的

**Comment by LvYixuan-0** [comment]
@NoDocCat 俺奉上两张自己抠的图![Image](https://imgtu.com/i/yO9siT)![Image](https://imgtu.com/i/yO9DoV)
麻烦你了
这两张图我抠得挺久的

**Comment by LvYixuan-0** [comment]
> @NoDocCat 俺奉上两张自己抠的图![Image](https://camo.githubusercontent.com/b4e063642e40a77890ef854f4eedd58ef13f0b1c060c47e2dd44a78298070f35/68747470733a2f2f696d6774752e636f6d2f692f794f39736954)![Image](https://camo.githubusercontent.com/123c4f07381a4bcfa51697a98b9accd106b8ac8d33e7ca53927b24bbee7029b4/68747470733a2f2f696d6774752e636f6d2f692f794f39446f56)
> 麻烦你了
> 这两张图我抠得挺久的

![Image](https://s3.ax1x.com/2021/02/24/yO9siT.png)
![Image](https://s3.ax1x.com/2021/02/24/yO9DoV.png)

**Comment by LvYixuan-0** [comment]
> > @NoDocCat 俺奉上两张自己抠的图![Image](https://camo.githubusercontent.com/b4e063642e40a77890ef854f4eedd58ef13f0b1c060c47e2dd44a78298070f35/68747470733a2f2f696d6774752e636f6d2f692f794f39736954)![Image](https://camo.githubusercontent.com/123c4f07381a4bcfa51697a98b9accd106b8ac8d33e7ca53927b24bbee7029b4/68747470733a2f2f696d6774752e636f6d2f692f794f39446f56)
> > 麻烦你了
> > 这两张图我抠得挺久的
> 
> ![Image](https://camo.githubusercontent.com/c3f6416a51c88cd68605511d83ba0d1ca5555de1dfd0869387f8cdcf5e18d7b3/68747470733a2f2f73332e617831782e636f6d2f323032312f30322f32342f794f397369542e706e67)
> ![Image](https://camo.githubusercontent.com/70fcab265234c89e21b9c16df8583d7ac668b0808ccc3907cedcdbd5a0dd4230/68747470733a2f2f73332e617831782e636f6d2f323032312f30322f32342f794f39446f562e706e67)

有一张是白色的,可能网页上看不到

**Comment by NoDocCat** [comment]
我这边暂时没有太多精力去做这个 feature, 而且要不要实现还需要找 @shalldie 确认.
我建议你不要使用 `background.customImages` 来配置图片 url, 而是传入一个空字符串用来占位.
然后用 `background.style` 来配置背景.

demo: 
![image](https://user-images.githubusercontent.com/20502666/108935474-b6d56400-7688-11eb-842f-6d30dea0bf83.png)

**Comment by NoDocCat** [comment]
`background.style` 是全量复制到生成结果中的, 可以传入所有合法的 css.

**Comment by LvYixuan-0** [comment]
好的

**Comment by NoDocCat** [comment]
@LvYixuan-0 已解决问题的话请关闭 issue
