### ISSUE TITLE
vscode更新到最新版本(1.54.0)后， 之前设置的背景图不可用l(不显示)

### ISSUE THREAD

**Issue by webxmsj** [shalldie/vscode-background#234]
vscode更新到最新版本后， 之前设置的背景图不可用l(不显示)

版本: 1.54.0 (Universal)
提交: 42e27fe5cdc58539dad9867970326a297eb8cacf
日期: 2021-03-03T02:17:59.499Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by LuSuguru** [comment]
同问

**Comment by gk-shi** [comment]
+1

**Comment by Awei-coder** [comment]
确实失效了

**Comment by Sherlock-Homles** [comment]
是本地图片设置失效了，网络图片还是可以设置的。

**Comment by cshenger** [comment]
我也是这个问题

**Comment by gk-shi** [comment]
的确是这样的...



> 是本地图片设置失效了，网络图片还是可以设置的。

**Comment by NoDocCat** [comment]
在分析了，在分析了(指打开电脑)🐶

**Comment by cshenger** [comment]
> 的确是这样的...
> 
> > 是本地图片设置失效了，网络图片还是可以设置的。

可能是vscode更新了什么方法导致读取相对路径的方法不行了吧

**Comment by NoDocCat** [comment]
> 可能是vscode更新了什么方法导致读取相对路径的方法不行了吧

现在发现可能存在本地路径白名单, 比如图中的这两个链接, 第二个链接就可以正常使用:
![image](https://user-images.githubusercontent.com/20502666/110087892-2fe26300-7dcf-11eb-9e65-48b6e9427704.png)

**Comment by NoDocCat** [comment]
@webxmsj @shalldie 白名单确认, 图片放到 `~/.vscode/extensions` 下可以正常使用, 但是放到 '~/.vscode' 中就无法显示

**Comment by cshenger** [comment]
> @webxmsj @shalldie 白名单确认, 图片放到 `~/.vscode/extensions` 下可以正常使用, 但是放到 `~/.vscode` 中就无法显示

这样确实可以了
![image](https://user-images.githubusercontent.com/5855865/110091779-ca44a580-7dd3-11eb-887c-b5b9562ef13f.png)

**Comment by NoDocCat** [comment]
简单的读了一下 vscode 的源码, 原因估计是新版本把 vscode 的工作区放到electron sandbox 里了.
同时好像拦掉了 file 协议: https://github.com/microsoft/vscode/blob/main/src/vs/code/electron-main/protocol.ts#L44
(这段没有看太懂, 我对 electron 不是太熟悉, 好像是为了安全, 要做一个 vscode-file 的自定义协议)

理了一下思路, 在生成 css 阶段判断一下图片路径, 如果是 file 协议的话, 直接把图片转成 base64 塞进去. 今天晚上回去试一下, 成功的话我提 PR

**Comment by NoDocCat** [comment]
PR 已提, 请大家耐心等待鸽王回归 @shalldie

**Comment by hentai-chan** [comment]
拡張をアップグレードした後に、同じバグを見つけた。もうバグを直してくれてありがとう！

**Comment by NoDocCat** [comment]
周六和作者联系了一下, 作者那边最近比较忙, 暂时没法处理 PR 和发版.
我从 Fork 上打包了一份, 可供临时使用. 版本号没有变动. 应该可以在下次发版后自动更新.
建议先卸载原版本, 然后解压得到 `vsix` 导入.

[background-1.1.26.vsix.zip](https://github.com/shalldie/vscode-background/files/6101629/background-1.1.26.vsix.zip)

**Comment by shalldie** [comment]
最近因为工作上一些事情比较忙，没能及时处理。
明天会赶往一个有外网的地方，处理、验证 pr 并发版 =。=

**Comment by SEELE0** [comment]
> > 可能是vscode更新了什么方法导致相对路径的方法不行了吧
> 
> 现在发现可能存在本地路径白名单，如图所示的这两个链接，第二个链接就可以正常使用：
> ![图像](https://user-images.githubusercontent.com/20502666/110087892-2fe26300-7dcf-11eb-9e65-48b6e9427704.png)

**Comment by xuejianxianzun** [comment]
看最新一个提交修复了这个问题，不过插件商店里似乎还没更新。用上面的方法（图片放到 `~/.vscode/extensions` 里）先用着了

**Comment by shalldie** [comment]
`Published shalldie.background@1.1.27`

感谢各位的等待，感谢 @NoDocCat 的 pr。
已经发布新版本修复了这个问题。

**Comment by tangdingga1** [comment]
> 拡張をアップグレードした後に、同じバグを見つけた。もうバグを直してくれてありがとう！

もう直しましたよ。アップグレードしてね。
