### ISSUE TITLE
卸载bug

### ISSUE THREAD

**Issue by higker** [shalldie/vscode-background#238]

**Comment by higker** [comment]
卸载有bug真是恶心！！！

**Comment by shalldie** [comment]
不好意思让你感到不适，这方面在 readme 有说明：

[原因](https://github.com/shalldie/vscode-background#warns-%E8%AD%A6%E5%91%8A)
[方案](https://github.com/shalldie/vscode-background#uninstall-%E5%8D%B8%E8%BD%BD)

**Comment by higker** [comment]
> 不好意思让你感到不适，这方面在 readme 有说明：
> 
> [原因](https://github.com/shalldie/vscode-background#warns-%E8%AD%A6%E5%91%8A)
> [方案](https://github.com/shalldie/vscode-background#uninstall-%E5%8D%B8%E8%BD%BD)

看到了，你这个步骤有问题，我自己研究出来了，每操作一步重启一次vscode才行，如果是一次性操作重启就有问题。没事了。
