### ISSUE TITLE
设置背景图片无效

### ISSUE THREAD

**Issue by PLUTO06210331** [shalldie/vscode-background#239]
"background.enabled": true,
  "background.useDefault": false,
  "background.loop": true,
  "background.customImages": ["file:///C:/Users/NATSU/Desktop/bqb/.vscode/extensions/GT3RS/1.png"],
  "background.style": {
    "content": "''",
    "pointer-events": "none",
    "position": "absolute",
    "z-index": "99999",
    "width": "100%",
    "height": "100%",
    "background-position": "100% 100%",
    "background-repeat": "no-repeat",
    "opacity": 0.5
  },
  "workbench.colorTheme": "Noctis Hibernus"

**Comment by PLUTO06210331** [comment]
点击链接可以看到图片的，但是背景不显示

**Comment by NoDocCat** [comment]
请参考 #234

**Comment by shalldie** [comment]
`Published shalldie.background@1.1.27`

已经发布新版本修复了这个问题。

**Comment by liuzifengsjtu** [comment]
shalldie.background@1.1.27依旧无法显示自定义图片

**Comment by tangdingga1** [comment]
> shalldie.background@1.1.27依旧无法显示自定义图片

我也是同样的问题。我看了下issue的讨论，是因为vscode开启了文件白名单设置，所以是两个解决方式：
1. 图片放到vscode的白名单路径下。
2. 路径带上file协议，`file://${yourpath}`有file协议头，最新的更改会把图片转换为base64载入。

如果路径是诸如我这种`/Users/tang/Desktop/background.jpg`，实际上还是无法加载的

**Comment by shalldie** [comment]
@liuzifengsjtu
可以把图片拖到浏览器中，然后从地址栏复制url作为自定义图片地址。

@tangdingga1 
因为地址有多样性，目前只支持 https 或者 file 协议格式的路径。
对于各os自己的路径格式没有支持

**Comment by liuzifengsjtu** [comment]
@shalldie 收到啦，谢谢你啦

**Comment by AllenHee** [comment]
> @liuzifengsjtu
> 可以把图片拖到浏览器中，然后从地址栏复制url作为自定义图片地址。
> 
> @tangdingga1
> 因为地址有多样性，目前只支持 https 或者 file 协议格式的路径。
> 对于各os自己的路径格式没有支持

第一种方法Mac还是不行，有什么其他方法吗

**Comment by shalldie** [comment]
@AllenHee

**Comment by shalldie** [comment]
如果默认或者自定义都不行，可以试试这种方式：https://github.com/shalldie/vscode-background/issues/252
