### ISSUE TITLE
老是提示code损坏，不敢用~~

### ISSUE THREAD

**Issue by 5977862** [shalldie/vscode-background#24]
感觉不安全。。。这个提示太恐怖

**Comment by shalldie** [comment]
哈哈哈，那我这段时间，把这个插件改成主题算了。
不过这样的话，就不能自定义图片了

**Comment by 5977862** [comment]
如果改成不能自定义图片，那就失去了这个插件的意义了。

**Comment by hellcoldby** [comment]
突然 code 就损坏了。。难道和图片有关系？、？

**Comment by shalldie** [comment]
@hellcoldby 
请选择【不再提示】，插件修改了vscode的文件，会有这个提示

**Comment by Morningstar1217** [comment]
感觉也还好  喜欢自定义的就继续用这个    不过我觉得默认的图片就挺好的

**Comment by Ehco1996** [comment]
我也觉得 默认图片挺好的，不然就再出一个主题的版本吧

**Comment by czmecho** [comment]
https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt

希望作者改为其它的方式修改背景呗。

**Comment by xzxldl55** [comment]
code损坏？无所谓。。。
