### ISSUE TITLE
Custom Image does not work

### ISSUE THREAD

**Issue by Crosser1919** [shalldie/vscode-background#240]
Custom image used to work for me then just stopped all of a sudden. Checked all previous issues and tried to compare but nothing is fixing. Default image works if I enable it but second I set it to false and try to go for a custom image it does not matter which one I pick it will not load.

Here is what the settings are currently set as
 "background.enabled": true,

    "background.useDefault": false,

    "background.style": {

    "content": "''",

    "pointer-events": "none",

    "position": "absolute",

    "z-index": "99999",

    "width": "100%",

    "height": "100%",

    "background-position": "center",

    "background-repeat": "no-repeat",

    "background-size": "100%,100%",

    "opacity": 0.1

    },
    "background.customImages": [
        "D:/Pictures/picture1.png",
        ],

**Comment by NachtgeistW** [comment]
This problem has been solved in issue #234 . You can check it.
Besides, people participating in that issue discussed in Chinese, so you may need a translator.

**Comment by shalldie** [comment]
`Published shalldie.background@1.1.27`

A new version has been published which solved this question.
