### ISSUE TITLE
设置了图片整个vscode都不行了

### ISSUE THREAD

**Issue by AllenHee** [shalldie/vscode-background#243]
更新了最新版本的，设置了图片然后整个vscode都不行了

**Comment by NoDocCat** [comment]
请提供具体问题描述, 同时最好提供完整复现方法, thx.

**Comment by AllenHee** [comment]
今天早上来的时候就设置了一个自定义的图片，然后就不行了，整个vscode全部乱掉了，Mac系统的

**Comment by AllenHee** [comment]
![image](https://user-images.githubusercontent.com/16890350/111928512-ceb8d000-8aee-11eb-9b3f-91801e9a025d.png)

**Comment by AllenHee** [comment]
可以的话请尽快回复，因为实在不想重装app，很多插件都形成习惯了

**Comment by AllenHee** [comment]
抱歉，弄错了，vscode自身的问题

**Comment by NoDocCat** [comment]
问题解决请关闭 issus
