### ISSUE TITLE
How to set-up background image 

### ISSUE THREAD

**Issue by alvinseville7cf** [shalldie/vscode-background#244]
Hello! I have the following settings.json:
```json
{
    "workbench.colorTheme": "Default Light+",
    "window.zoomLevel": 1,
    "editor.fontSize": 16,
    "debug.console.fontSize": 16,
    "terminal.integrated.fontSize": 16,
    "markdown.preview.fontSize": 16,
    "terminal.integrated.shell.windows": "C:\\tools\\cygwin\\bin\\bash.exe",
    // Use this to keep bash from doing a `cd $HOME`
    "terminal.integrated.env.windows": { "CHERE_INVOKING": "1" },
    "terminal.integrated.shellArgs.windows": [ "--login" ],
    "terminal.integrated.automationShell.linux": "",
    "workbench.editor.wrapTabs": true,
    "octave-formatter.pythonPath": "C:\\tools\\cygwin\\bin\\python3.8.exe",
    "octave-formatter.separateBlocks": false,
    "workbench.startupEditor": "newUntitledFile",
    "workbench.settings.editor": "json",
    "background.customImages": [
        "C:\\Users\\Alvin\\Documents\\windows terminal background.png"
    ],
    "background.style": {
        "background.useDefault": false,
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "100% 100%",
        "background-repeat": "no-repeat",
        "opacity": 0.3
    },
}
```
But VS Code shows standard background instead my custom image:
![image](https://user-images.githubusercontent.com/42812113/112798601-75354000-90b0-11eb-89f8-f52dcd67ef20.png)

How to fix it? I want my background image fit code editor size and be placed in the right corner like in Visual Studio:
![image](https://user-images.githubusercontent.com/42812113/112798807-c9402480-90b0-11eb-998a-ce17a85a3029.png)

**Comment by NoDocCat** [comment]
1. you must use `https://` or `file://`
2. `background.useDefault` should be on the outer layer.
3. Please read the document carefully, thx.

**Comment by alvinseville7cf** [comment]
@NoDocCat, thanks, now background is shown, but it really big:
![image](https://user-images.githubusercontent.com/42812113/112807473-496b8780-90bb-11eb-8587-570ca6160797.png)
I don't understand how to resize it to editor code size.

**Comment by NoDocCat** [comment]
1. open the dev tools in vscode
2. run `document.querySelectorAll('.overflow-guard>.monaco-scrollable-element')`
3. click the result jump to Elements tab and  expand the element
4. you can find a `::before` or `::after`, styles on right.

tips: `background.style` value is compliant css, you can look over MDN.
