### ISSUE TITLE
更新1.55.0后全部失效https/file都不行,

### ISSUE THREAD

**Issue by secondar** [shalldie/vscode-background#246]
TR
且在deepinV20下自始至终无效从1.54.1起,插件均更新到最新版本了

**Comment by NoDocCat** [comment]
Win10 下未能复现，请检查是否有足够的权限读写 ` workbench.desktop.main.css`. 且文件没有被标记为只读

**Comment by secondar** [comment]
workbench.desktop.main.css 可读可写 试过管理员身份一样无效
win10专业版
![20210402112915](https://user-images.githubusercontent.com/45650501/113377445-df96fa80-93a6-11eb-9eb5-5238fe311c04.png)
![20210402112934](https://user-images.githubusercontent.com/45650501/113377448-e0c82780-93a6-11eb-9999-bff5119ed05f.png)

**Comment by secondar** [comment]
查看workbench.desktop.main.css 文件,背景文件路径最终指向 ~\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\file,也就是安装目录下的resources\app\out\vs\workbench\file文件夹,最终使用 file///背景图片文件路径可解决
