### ISSUE TITLE
Not Work.

### ISSUE THREAD

**Issue by OtakoidTony** [shalldie/vscode-background#247]
![20210406_175323](https://user-images.githubusercontent.com/36785562/113685300-10f22c00-9701-11eb-997d-08030d34756b.png)
Even though I installed shalldie.background v1.1.27 and set background.customImages with file:///, not work for me.

How can I use this plugin?

**VSCode Info:**
```
Version: 1.55.0 (system setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by NoDocCat** [comment]
If your use `system setup`, you must run vscode of `Administrator`. Because the plugin will change vscode program file.
And the `background.style` config only add your need css.

If everything is ok, you will see a pop to remind you to restart vscode.

**Comment by NoDocCat** [comment]
a long long time ago, vscode recommend use `user setup`

**Comment by OtakoidTony** [comment]
I tried reinstall vscode and run vscode as administrator. it worked. Thanks.
