### ISSUE TITLE
上下左右拆分时图片重复

### ISSUE THREAD

**Issue by banzhe** [shalldie/vscode-background#248]
拆分成四个时只会用到两张图片
![image](https://user-images.githubusercontent.com/30437113/114005049-c522bc80-9891-11eb-9911-e99159a765d7.png)
拆分成九个时只会用到三张图片
![image](https://user-images.githubusercontent.com/30437113/114005357-0b781b80-9892-11eb-8c4f-c2769df127c0.png)
请问有什么方法可以让每个窗口都显示不同的图片吗

**Comment by shalldie** [comment]
😂😂  没考虑过上下的情况，这种使用情况太少了

有想过去支持，但是复杂度比较高成本挺大，收益较小就搁置了。
欢迎 pr ～
