### ISSUE TITLE
不同服务器设置不同的背景

### ISSUE THREAD

**Issue by DanielZ98** [shalldie/vscode-background#250]
两个不同的远程服务器，想设置不同的背景，在vscode-serve中设置了两张不同的图片，但是打开后是相同的图片。这个是个bug吗

**Comment by DanielZ98** [comment]
不同项目也不能设置不同的背景？

**Comment by NoDocCat** [comment]
严格来说应该属于未定义行为, 因为插件根本没考虑 code-server 这样的特殊环境.

**Comment by DanielZ98** [comment]
> 严格来说应该属于未定义行为, 因为插件根本没考虑 code-server 这样的特殊环境.
