### ISSUE TITLE
是否可以只在终端显示背景图片

### ISSUE THREAD

**Issue by movead123** [shalldie/vscode-background#251]
请问是否可以配置，只在终端区域显示背景图片，而不是在编辑区域。

**Comment by shalldie** [comment]
没有这种设置，插件主要用于在代码区域设置背景。

**Comment by dianbaiyizhong** [comment]
如果能支持终端就好了

**Comment by shalldie** [comment]
> 如果能支持终端就好了

@dianbaiyizhong 
也有这个想法，会考虑支持。就是时间节点上还没能保证
