### ISSUE TITLE
关于macOS无法正常显示图片的一个可能原因 - case in macOS

### ISSUE THREAD

**Issue by pingxinwen** [shalldie/vscode-background#252]
可能是在官网下载程序后，没有放在Application文件夹里而是直接在Download文件夹里打开了，这样vscode会处在一个类似于只读模式，无法自己读取设置、获取更新，参考[Code won't update on macOS](https://github.com/microsoft/vscode/issues/7426)

需要将程序拷贝到Application文件夹里，之后每次从这里启动就可以正常使用插件了

**Comment by yeswhos** [comment]
牛逼，亲测答主方法有用！

**Comment by shalldie** [comment]
抽空细读一下，晚点补充到文档中

**Comment by shalldie** [comment]
pinned ，改了下标题，让其他人更快看到
