### ISSUE TITLE
关于背景图片透明的问题

### ISSUE THREAD

**Issue by matrix-zyh** [shalldie/vscode-background#253]
作者，您好：
        想向您请教一下，我下载了您的这个插件之后，根据文档，设置了 background.style 的样式，其中设置了一项背景透明，我使用的是 “opacity” 属性，但是这个 css 属性会导致文字也透明化了，我想改用 rgba，但是我发现，在 background.style 中编写 rgba，是不生效的。百度了好久，都没有解决这个问题。
        所以想请教一下作者您，对于这种只想让背景透明，但是又不影响到文字的，我该怎么做。感谢！

**Comment by shalldie** [comment]
试试设置 `background.useFront: false` ，把背景放在代码下面。一般大图可以选这种。

这样应该可以让背景透明，不影响文字。

**Comment by matrix-zyh** [comment]
作者，您好：
        我发现了一个问题，我将 background.style 中的 position 由 absolute 改为 fixed，文字就变透明了，但是这样的话，图片是铺满整个vscode 编译器，如果改为 absolute，的确，背景透明不影响文字了，但是这样的话，图片只能铺满右侧代码编辑区域，而不能铺满整个编译器。请问这是一种限制嘛现在？？？

**Comment by shalldie** [comment]
`background.style` 提供了能力去自定义背景的样式，比较灵活。
fixed 一般要跟 `left`、`top`、`width`、`height` 一起用，属于css的内容，这些可以决定 `位置` 和 `大小`。

推荐使用 https://github.com/shalldie/vscode-background/issues/253#issuecomment-851014314 的方式也可以让背景透明。

**Comment by matrix-zyh** [comment]
作者，您好：
        是的，您说的没错，我的确是搭配的 `left`、 `top`、 `width`、 `height`一起使用的，这是我的 [配置文件](https://www.zouyinghao.com/images/background-fix.png)，如果不麻烦的话，还望作者能看一下，是哪里配置的不对嘛，我觉得是因为 `fixed` 是针对浏览器窗口进行定位，所以导致影响了整个IDE。但是又不知道这部分应该怎么解决，如果作者有好的想法，还希望提点建议，实在不行，我在使用 [#253 (commit)](https://github.com/shalldie/vscode-background/issues/253#issuecomment-851140957) 这种方式，因为还是喜欢铺满整个 IDE 的背景看起来舒服一些。感激！

**Comment by NoDocCat** [comment]
t0, r0, b0, l0 可以使定位元素撑满相对元素。
记得承载背景图的伪元素父级就是编辑器窗口

**Comment by shalldie** [comment]
### 先说一下原因：

铺满就要让层级在最外层，也就是 z-index 最大，否则可能会被 `代码`、`header菜单`、`左侧菜单栏`、`右侧 mini-map` 遮挡。

而 `代码` 的层级是在 `header菜单`、`左侧菜单栏`、`右侧 mini-map` 之下的。

也就是说，`background` 如果想全屏，务必要遮挡 `代码`，这样的半透明可能会影响代码的观看感官。

### 综合建议：
写代码其实不适合大图，如果要大图也最好让图片处于代码下方（即设置 `background.useFront: false` 来避免对代码查看的影响）
小图的话对代码查看影响比较小，可以用 `background.useFront: false` 或者 `fixed` 来调整到喜欢的位置。

**Comment by matrix-zyh** [comment]
好的好的，麻烦您了，您说意思我都明白了，我在研究一下。感谢！
