### ISSUE TITLE
background.style parameters

### ISSUE THREAD

**Issue by ALLterago** [shalldie/vscode-background#254]
Is there any documentation about all background.style parameters that can be changed like horizontal flip or image scale?

**Comment by NoDocCat** [comment]
`background.style` value is compliant css, you can look over MDN.

**Comment by NoDocCat** [comment]
you can use transform and transform-function to do it.
![image](https://user-images.githubusercontent.com/20502666/121469419-06992a80-c9ef-11eb-94ae-86e7877c00cc.png)
