### ISSUE TITLE
png files seem not to work

### ISSUE THREAD

**Issue by TheirryEHB** [shalldie/vscode-background#256]
Hello Shalldie,
I have had this issue for a while now. But it seems that png file are not shown as png's. 
How can I fix this?
This is my current configuration together with the background:
![image](https://user-images.githubusercontent.com/80406706/121811775-a9f37500-cc65-11eb-9296-353449d4f3ae.png)

**Comment by shalldie** [comment]
In my experience，the big probability is that the picture itself is like this...
Try another png file ~

I like huihui's `Explosion` >_<#@!

**Comment by TheirryEHB** [comment]
Alright thank mate, it worked!

**Comment by TheirryEHB** [comment]
Closed #256
