### ISSUE TITLE
background 配置跟随 workspace

### ISSUE THREAD

**Issue by g8up** [shalldie/vscode-background#257]
如此便可在 workspace setting 里设置 background，并纳入项目内的 git 跟踪了。

**Comment by shalldie** [comment]
这个需要在 runtime 阶段去修改 background，需要注入 js 的能力，
当前是在 安装后、 每次打开vscode 的时候修改css文件，比较硬核。

两者在设计上挺难兼容，
这想法我挺喜欢的，后面看看有没有缘分把这个加进去

**Comment by whenk7** [comment]
项目内建一个.vscode，里面建个setting.json，写上这个插件的配置，记得把图片放到项目里，就可以了啊

**Comment by g8up** [comment]
@whenk7 ，当时体验过你说的设置，好像多个 workspace 的背景配置会冲突。

**Comment by NoDocCat** [comment]
@g8up 因为 vscode 不允许插件访问视图(进程隔离), 所以当前插件的实现方式是根据配置生成 css, 追加到 vscode 的样式文件里. 所以目前没有任何动态修改的能力. 如果想要动态的修改能力, 实现上就得想办法向 vscode 的视图进程里注入 javascript.
