### ISSUE TITLE
Trying to delete but it's not working

### ISSUE THREAD

**Issue by vitorsmends** [shalldie/vscode-background#258]
I'm trying to delete this extesion, but when i uninstall it's not working the image still here. 
I saw in another issue that supposed to set the "background.enable" = false in the settings.json, but i'm not fiding this archive.
If you can help me please. i'm just seeing this archive here.

![image](https://user-images.githubusercontent.com/71814309/124675932-02e4b080-de94-11eb-82ed-91a7d91a4b21.png)

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/125056287-a8896100-e0da-11eb-9ab7-cc0c7d5e8aab.png)

After this extension installed, you can edit the setting in `ui` or `json`.

The path is `code` - `Preference` - `Settings`.

**Comment by thanhnguyen001** [comment]
it's not working. The image still there.

**Comment by NoDocCat** [comment]
> it's not working. The image still there.

Please try the following procedure:
1. Edit settings.json, set `background.enabled: false`.
2. Save the file. At this time, a prompt will pop up in the lower right corner.
3. Click `Restart vscode`, VSCode will restart, the background image should disappear.
4. Uninstall this plugin and clean plugin config in settings.json
