### ISSUE TITLE
VSCode升级之后，新版本似乎不好用>。<

### ISSUE THREAD

**Issue by huoshizhe** [shalldie/vscode-background#259]
不知道哪里出了错

 "background.customImages": [
        "D:/workspace/settings/leisen.jpg",
        "D:/workspace/settings/sakuya.jpg",
        "D:/workspace/settings/leimu.jpg",
    ],
    "background.style": {
        "pointer-events": "none",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-size": "cover",
        "background-repeat": "no-repeat",
        "background-position": "top right",
        "opacity": 0.2
    },

**Comment by NoDocCat** [comment]
请使用 file 或 https 协议

**Comment by huoshizhe** [comment]
好用了，感谢！
"background.customImages": [
        "file:///D://workspace/settings/leisen.jpg",
        "file:///D://workspace/settings/sakuya.jpg",
        "file:///D://workspace/settings/leimu.jpg"
    ],
    "background.style": {
        "pointer-events": "none",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-size": "cover",
        "background-repeat": "no-repeat",
        "background-position": "top right",
        "opacity": 0.2
    },
