### ISSUE TITLE
Full size vs code-only

### ISSUE THREAD

**Issue by zThana** [shalldie/vscode-background#260]
Hi,

I'm trying to get the background to appear throughout the whole IDE instead of just the code box. Is that possible?

Thanks,
Thana

**Comment by justforuse** [comment]
I use `Custom CSS and JS` to load local css file, and it seems work well.

here is my css file:

```
body::after {
    content: '';
    pointer-events: none;
    background: url(YOUR_IMAGE) no-repeat;
    background-size: cover;
    opacity: .15;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
}
```

**Comment by justforuse** [comment]
Can we add a new option to set the background image to append after <body>？

**Comment by zThana** [comment]
> I use `Custom CSS and JS` to load local css file, and it seems work well.
> 
> here is my css file:
> 
> ```
> body::after {
>     content: '';
>     pointer-events: none;
>     background: url(YOUR_IMAGE) no-repeat;
>     background-size: cover;
>     opacity: .15;
>     position: absolute;
>     top: 0;
>     left: 0;
>     width: 100%;
>     height: 100%;
>     z-index: 1;
> }
> ```

This also only sets it for the code box

**Comment by shalldie** [comment]
This extension is designed to change the background of code panel, 
what you want may be a feature.

I'm busy with promotion recently, I'll add it when all done.

**Comment by NoDocCat** [comment]
You can experiment `position: fixed`, It allows element to be free from parent (out of document flow).

like this:
![image](https://user-images.githubusercontent.com/20502666/128624060-af9f47c1-fffd-4f47-b9a8-64a63f24b274.png)

**Comment by zThana** [comment]
> You can experiment `position: fixed`, It allows element to be free from parent (out of document flow).
> 
> like this:
> ![image](https://user-images.githubusercontent.com/20502666/128624060-af9f47c1-fffd-4f47-b9a8-64a63f24b274.png)

Doesn't seem to do the trick for me:
`    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "fixed",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "100% 100%",
        "background-repeat": "no-repeat",
        "opacity": 0.7
    }`



> This extension is designed to change the background of code panel,
> what you want may be a feature.
> 
> I'm busy with promotion recently, I'll add it when all done.

Thanks a lot and good luck with your promotion!

**Comment by NoDocCat** [comment]
@zThana https://developer.mozilla.org/en-US/docs/Web/CSS/background-position

**Comment by zThana** [comment]
I feel like my changes aren't saved properly. I changed the height and width to 1% and background position to 1% each but it didn't change anything, even after restarting VSC

**Comment by NoDocCat** [comment]
Please refer to this:
![image](https://user-images.githubusercontent.com/20502666/128651952-fa047001-4e1c-4beb-a437-bab24d167f36.png)

**Comment by zThana** [comment]
That did the trick for me, thanks a lot! All buttons have become grayed out/transparent to the point where I can't click anything within my IDE other than the buttons on the toolbar

**Comment by NoDocCat** [comment]
@zThana `background.useFront: false`
By default, The background image will be overlaid on top of the actual elements. This is the css rule.

**Comment by NoDocCat** [comment]
> That did the trick for me, thanks a lot! All buttons have become grayed out/transparent to the point where I can't click anything within my IDE other than the buttons on the toolbar

I'm sorry, i overlooked the issue of coverage. This issue can be solved by css: `pointer-events: none`.
like this:
![image](https://user-images.githubusercontent.com/20502666/128717712-d777a86c-f13e-4557-87eb-064178c3f700.png)

But I found another issue, add the css in `background.style` not work, It seems that this rule is filtered out. 
I don't know the reason, need further debug.

**Comment by NoDocCat** [comment]
At this: https://github.com/shalldie/vscode-background/blob/dc4bbd97161715ff4e48dffa7677ddd6cdff057d/src/getCss.ts#L13-L27

If use front, filter out `pointer-events` when generated. I don't know why, need help of @shalldie

**Comment by zThana** [comment]
Good find! I'm sure it'll help
