### ISSUE TITLE
Image does not appear if the path contains "#" or "%"

### ISSUE THREAD

**Issue by 8NAF** [shalldie/vscode-background#263]
### **The folder containing my images:**

![image](https://user-images.githubusercontent.com/62730599/131701483-947f7eda-af04-4736-ae92-c417466e09e7.png)

### **My settings:**
```
"background.enabled": true,
"background.useDefault": false,
"background.style": {
    "content": "''",
    "pointer-events": "none",
    "position": "absolute",
    "right": "1%",
    "bottom": "0",
    "width": "100%",
    "height": "100%",
    "z-index": "9999",
    "background-size": "contain",
    "opacity": 0.5,
},
"background.customImages": [
    "file:///E:/Image/Gawr_Gura%11.png",
    "file:///E:/Image/Nachoneko#10.webp",		
],
```

### **And nothing happened, (─‿‿─)**

![image](https://user-images.githubusercontent.com/62730599/131703342-cd95347a-fd2f-4958-9a53-64132e16f136.png)

**Comment by shalldie** [comment]
1. drag the picture to a browser
2. copy the link from `url`, paste it to your config.

All strange chars may be encoded.
