### ISSUE TITLE
自定义图片的数组中如何实现随机展示图片集，而不是固定的展示顺序

### ISSUE THREAD

**Issue by mounwater** [shalldie/vscode-background#264]
每次打开窗口都是按照数组顺序默认展示从前往后的图片，可以实现随机展示图片吗？

**Comment by NoDocCat** [comment]
由于 vscode 插件 api 的限制, 具体实现是根据你的配置去生成 css 然后追加到 vscode 的 css 中的.
也就是说只有你修改配置的时候才会去修改 css 文件. 其他时候插件的逻辑是不执行了.
而 css 没有随机机制, 所以没办法实现.
