### ISSUE TITLE
如何使照片固定在右下角?

### ISSUE THREAD

**Issue by JieHong-Liu** [shalldie/vscode-background#265]
我想要像Default的圖片乖乖待在右下角，
而不是一直卡在左上角QQ
我用其他圖片的時候都會像是被斷頭一樣
我的設定擷圖在這裡:
![](https://i.imgur.com/8THrSZB.png)
剛好背景就是被斷頭的樣子QQ
請問我的style要怎麼改才可以像default相同?

**Comment by shalldie** [comment]
看起来你修改了默认的 style ，其中的 `background-position` 可以修改为： `"100% 100%"`，表示右下方
这些都是纯 css 规则

**Comment by JieHong-Liu** [comment]
非常感謝><
