### ISSUE TITLE
Custom Images not working... 

### ISSUE THREAD

**Issue by crhodes2** [shalldie/vscode-background#266]
Hi,

So this is based on a similar issue at https://github.com/shalldie/vscode-background/issues/75; where my custom images aren't working.  I know this is a repeat to that question but I have tried most of the solutions listed on there and I am still not having much luck. Can anyone help me figure out what I'm doing wrong? I am really stumped.

Here is my settings:
    // VS Code Background
    "background.enabled": true,
    "background.useDefault": false,
    "background.useFront": true,
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-repeat": "no-repeat",
        "opacity": 1
    },
    "background.customImages": [
        "C:/Users/miiwo/Dropbox/DEVIANTaRT/ArtBOOK/Color/CTFTO1 - Book of Wonders Full Cast of Characters (Live Action).png"
    ],

**Comment by NoDocCat** [comment]
File url must use `https` or `file` protocol.

**Comment by shalldie** [comment]
@crhodes2 
1. drag the image to browser
2.  copy the url and paste to `background.customImages`

**Comment by shalldie** [comment]
Is that work?
