### ISSUE TITLE
如何设置为全屏背景图片

### ISSUE THREAD

**Issue by eblamlac** [shalldie/vscode-background#268]
`难道只能在工作区显示吗`
![aa](https://user-images.githubusercontent.com/58626606/137619307-6b96f161-dcc6-4177-a825-b0f4e22f6fc2.png)

**Comment by BoltLi** [comment]
`"background-size": "cover",`
`"position": "fixed",`
通过上面两个配置就可以了

**Comment by shalldie** [comment]
> `"background-size": "cover",` `"position": "fixed",` 通过上面两个配置就可以了

hhh 好像确实可以，niubility。

**Comment by bushnerd** [comment]
> > `"background-size": "cover",` `"position": "fixed",` 通过上面两个配置就可以了
> 
> hhh 好像确实可以，niubility。

现在使用这个方法已经不能设置为全窗口背景了。

**Comment by myotsuki** [comment]
> > > `"background-size": "cover",` `"position": "fixed",` 通过上面两个配置就可以了
> > 
> > 
> > hhh 好像确实可以，niubility。
> 
> 现在使用这个方法已经不能设置为全窗口背景了。

的确无法生效。。

**Comment by shalldie** [comment]
在考虑添加个专门的配置项

**Comment by 1493468110** [comment]
请问现在还有办法吗

**Comment by shalldie** [comment]
@1493468110 
顺利的话两周内发一版专门支持该功能

**Comment by MuuuShin** [comment]
跟上一个定位上下左右貌似就可以了
下图示，我加了个`"right":"5px"`就能正常全屏覆盖，没加就不覆盖左侧栏，不知道是什么原理……

![image](https://user-images.githubusercontent.com/97760035/193055314-304e659a-05f5-4eae-a50b-d9491f9ace86.png)

**Comment by MuuuShin** [comment]
> 跟上一个定位上下左右貌似就可以了 下图示，我加了个`"right":"5px"`就能正常全屏覆盖，没加就不覆盖左侧栏，不知道是什么原理…… ![I$%E GCKU_MO08NUJ $O{UL](https://user-images.githubusercontent.com/97760035/193055777-c9f1a1d2-a5de-4c5b-bcdb-94897183f18d.png) ![image](https://user-images.githubusercontent.com/97760035/193081577-46fd9b6b-b110-4f05-a1de-abf53d486922.png)

@shalldie

**Comment by MuuuShin** [comment]
啊……但是这样做了后左侧栏完全没法点了(点击没有任何反应，变成了装饰板，在不加载背景图的页面恢复正常

**Comment by NoDocCat** [comment]
@MuuuShin 使用背景图时 pointer-events 会被排除掉, 之前这个问题问过 @shalldie . 但一直没回复我, 似乎他也不记得为什么要这么做了. QAQ

https://github.com/shalldie/vscode-background/blob/17fa1b2760b2c0de973cb5a8765c582d5e2fffd8/src/getCss.ts#L16-L19

**Comment by MuuuShin** [comment]
> @MuuuShin 使用背景图时 pointer-events 会被排除掉, 之前这个问题问过 @shalldie . 但一直没回复我, 似乎他也不记得为什么要这么做了. QAQ
> 
> https://github.com/shalldie/vscode-background/blob/17fa1b2760b2c0de973cb5a8765c582d5e2fffd8/src/getCss.ts#L16-L19

我注释掉也没用呀，不只是这里？

**Comment by shalldie** [comment]
@MuuuShin @NoDocCat 

我记得是需要使 `pointer-events: none` 来避免阻塞用户的交互，否则用户的点击就会在“透明的背景蒙层”上。
全屏功能这周末会发一版本，一定 😂
