### ISSUE TITLE
改参数把vscode改崩了。

### ISSUE THREAD

**Issue by faker1708** [shalldie/vscode-background#269]
这个插件对应json文件在哪啊。。我找不到只能整个重装vscode了。

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/141429449-ab803799-7b14-4535-b27c-127a83a88451.png)

从这里可以打开vscode的配置文件。
有遇到过崩了的case，如果vscode是放在【下载】中的话，可以移出来，比如放到【Application】里面。

**Comment by faker1708** [comment]
> ![image](https://user-images.githubusercontent.com/9987486/141429449-ab803799-7b14-4535-b27c-127a83a88451.png)
> 
> 
> 
> 从这里可以打开vscode的配置文件。
> 
> 有遇到过崩了的case，如果vscode是放在【下载】中的话，可以移出来，比如放到【Application】里面。

然而当时人家的前端已经打不开了，不存在点击设置了。(T^T)

**Comment by shalldie** [comment]
嗯，，hhh 笑出来。
mac的【下载】目录其实有一些权限限制，下载的应用最好换一个目录放。

重装确实是解决问题的最终方案。
