### ISSUE TITLE
主题化自定义功能就少了啊，应该不少人喜欢用这个自定义背景的

### ISSUE THREAD

**Issue by EchoYoungDee** [shalldie/vscode-background#27]

**Comment by shalldie** [comment]
嗯，昨天更新了一下插件，发现下载的人还不少。
我会把插件的自定义功能坚持到微软完全禁止为止。。。

**Comment by MingHuiLiu** [comment]
没有效果啊,我在1.72 1.8 下使用过都不行,操作系统为Ubuntu,默认图片及自定义图片都无法显示

**Comment by shalldie** [comment]
@MingHuiLiu 
https://github.com/shalldie/vscode-background/issues/6
使用本插件需要有【修改文件的权限】，即管理员权限
试试上面链接的方法

**Comment by abcdongyuhau** [comment]
为什么我下载了 自定义背景还是不能用

**Comment by shalldie** [comment]
@abcdongyuhau 
如果默认背景可以显示，则是设置问题。
如果默认背景不能显示，则应该是无权限的原因。

第一次使用请开启管理员权限，win下【右键】-【以管理员身份运行】

**Comment by SertTex** [comment]
为毛不能铺满 ,只有代码块才有背景显示
