### ISSUE TITLE
Where I can change the background image? there's nothing like that in settings.json

### ISSUE THREAD

**Issue by 2JZxprazz** [shalldie/vscode-background#274]
When I installed the extension background image is there but if I want to change it ? my settings.json looks like this:

![code-snapshot2](https://user-images.githubusercontent.com/86107581/144390383-1ca85030-24d1-4bc9-9606-77967314db13.png)

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/144575813-3219477f-0fc8-4f0d-995f-c240f6270f3f.png)

the config you need is here: https://github.com/shalldie/vscode-background#config-%E9%85%8D%E7%BD%AE%E9%A1%B9

set `background.useDefault` as `false`,
then `background.customImages` as `["url1", "url2"]`

**Comment by yesImInsane** [comment]
I mean where? What is the file or something?(maybe im asking a wrong question)

**Comment by yesImInsane** [comment]
I mean what is the file I have to change this , this is just the readme?

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/144631681-d8d89a85-f450-440b-a2c7-b8adef685682.png)

![image](https://user-images.githubusercontent.com/9987486/144631784-65a9e3bf-3daa-4701-a256-21a536519ed0.png)

Oh i know.
vscode  has a setting file named `settings.json`, you can open it by the way image shows.

The short key is `command + ,` in macOS.

**Comment by yesImInsane** [comment]
> When I installed the extension background image is there but if I want to change it ? my settings.json looks like this:
> 
> ![code-snapshot2](https://user-images.githubusercontent.com/86107581/144390383-1ca85030-24d1-4bc9-9606-77967314db13.png)

but this is what settings.json looks like!

**Comment by shalldie** [comment]
@2JZxprazz  Can't you edit it?

Just add the config into the `settings.json`

**Comment by 2JZxprazz** [comment]
Oh I was confused, thank you

**Comment by Gaurav-Tewatia** [comment]
<img width="1105" alt="Screenshot 2022-11-29 at 12 04 19 PM" src="https://user-images.githubusercontent.com/103888220/204456260-d7686bf9-3678-463e-ac1b-3b0ed3aa054d.png">
this is what i am seeing in my json settings?
what should i do after this?

**Comment by Gaurav-Tewatia** [comment]
"background.enabled": true,
    "background.loop": false,
    "background.useDefault": false,
    "background.useFront": false,
    "background.style": {
          "content": "''",
          "pointer-events": "none",
          "position": "absolute",
          "z-index": "99999",
          "width": "100%",
          "height": "100%",
          "background-size": "cover",
          "background-repeat": "no-repeat",
          "opacity": 0.1
      },
    "background.customImages": [
          "https://cdn.wallpapersafari.com/5/23/AMbq2m.jpg",  //REPLACE THIS
          "/home/nl/Downloads/wallhaven-8ok7vk.jpg",          //REPLACE THIS
      ]

should i copy paste this as it is or should i delete what is written in that first and then paste the above code?

**Comment by shalldie** [comment]
@Gaurav-Tewatia answer you at https://github.com/shalldie/vscode-background/issues/346

**Comment by gyk-123** [comment]
awesome

**Comment by 13422720** [comment]
help~Where went wrong?

**Comment by 13422720** [comment]
<img width="730" alt="sp20231213_084359_354" src="https://github.com/shalldie/vscode-background/assets/43122616/1d7617f8-a9a0-4a0f-825d-1b5561b310ef">

**Comment by shalldie** [comment]
There should be a `,` at the end of `workbench.colorTheme`, it's a json file.
@13422720

**Comment by 13422720** [comment]
when i added the ","at the workbench.colorTheme".There was no error at all.But when i save the file and close it,it will change back.Why that happened?

**Comment by 13422720** [comment]
<img width="773" alt="sp20231213_145735_013" src="https://github.com/shalldie/vscode-background/assets/43122616/55c519a8-c514-4887-b17c-9f7773dc61ff">
![sp20231213_084359_354](https://github.com/shalldie/vscode-background/assets/43122616/c72d7f5d-c109-44cf-97cc-9a9dedf63dfb)

**Comment by shalldie** [comment]
> when i added the ","at the workbench.colorTheme".There was no error at all.But when i save the file and close it,it will change back.Why that happened?

@13422720 
It seems to have nothing to do with the plugin.
My suggestion is that, close all vsocde and reopen one, try to save some other info into the `settings.json`, If it's still like this,you can open an issue to `vscode`.

If you encounter any problems while using this plugin, you can create a separate issue.

**Comment by 13422720** [comment]
Thanks

**Comment by HigashiyamaHaraku** [comment]
![Image](https://github.com/user-attachments/assets/6a5e3d57-fa85-49c9-8f98-7ce1f06ab91e)
为什么没展示出图片？

**Comment by FlameBeast25** [comment]
> @2JZxprazz Can't you edit it?
> 
> Just add the config into the `settings.json`

where tho

**Comment by SnakeDream** [comment]
> How should I write the configuration file so that it can randomly display pictures from the folder?It seem have no field to set folder.
this

<img width="311" height="138" alt="Image" src="https://github.com/user-attachments/assets/280989cc-fa7d-4d12-bc5a-1ecf26c6ef36" />

**Comment by OrangeYuhang** [comment]
终端背景对应哪个键设置

**Comment by shalldie** [comment]
> 终端背景对应哪个键设置

<img width="2293" height="1650" alt="Image" src="https://github.com/user-attachments/assets/f1ada5f4-9a1a-4a48-8b69-ca384d8412d0" />

<img width="420" height="198" alt="Image" src="https://github.com/user-attachments/assets/674a5ff2-7500-4877-a1c4-6359385f150b" />


@OrangeYuhang 
可以参考readme示意图，在 panel 中设置
