### ISSUE TITLE
建议-应用背景图片在欢迎页

### ISSUE THREAD

**Issue by frg2089** [shalldie/vscode-background#279]
扩展似乎并不会将背景图叠在欢迎页上

能否提供一个设置来决定要不要将图片叠在欢迎页上?

![截图](https://user-images.githubusercontent.com/42184238/148645386-604ac357-37d2-4e24-8018-f5b70c188ec8.png)

**Comment by shalldie** [comment]
因为【欢迎页】跟【代码页】的布局有差异，把【代码页】的图片直接应用到【欢迎页】很可能展示效果不好
，，，而如果单独给【欢迎页】一个背景设置貌似又太重了。

在考虑单独做个【background 的配置/欢迎页面】

**Comment by frg2089** [comment]
我用[be5invis.vscode-custom-css](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css)扩展为`.gettingStartedContainer::before`添加了自定义样式
看起来效果还好。（除了“演练”部分背景是不透明的。）

以及...我注意到那个minimap是不透明的...能否在扩展设置中提供一个选项用来控制minimap的透明度？
我写了这样的样式，它看起来似乎不错的样子（？
```css
.minimap { opacity: 75%; }
```

**Comment by frg2089** [comment]
这个issue应该重新打开
因为提交 b96cd5934eb2a70ce11985feb289beb2f4c22e71 的修改在提交 2d71baddb9d1242fe76c581b06926fbeeff53db9 被移除
