### ISSUE TITLE
windwos 10 用不了

### ISSUE THREAD

**Issue by ChanceGao** [shalldie/vscode-background#28]

**Comment by shalldie** [comment]
麻烦试试开启管理员权限？
我这里测试了win10，木有问题

**Comment by mikemakepen** [comment]
win10要管理员权限才能显示图片，这是为什么呢

**Comment by shalldie** [comment]
@mikemakepen 
插件原理，是通过修改css文件来实现样式更换。所有系统都需要有操作文件的权限。

**Comment by mikemakepen** [comment]
我看win10下，插件是下载安装到用户的个人目录的，用户应该可以访问自己的目录吧。

**Comment by shalldie** [comment]
@mikemakepen 
我是修改 vscode 系统文件的css文件，这个操作需要管理员权限。

**Comment by mikemakepen** [comment]
原来酱紫，o(╯□╰)o

**Comment by shalldie** [comment]
@mikemakepen 
一般来说，就第一次用需要开启一下，以后就没事啦。。。
除非重装vscode

**Comment by mikemakepen** [comment]
明白了，多谢
