### ISSUE TITLE
Does not work in VS Code 1.64

### ISSUE THREAD

**Issue by mkholt** [shalldie/vscode-background#280]
Updated VS Code to 1.64, which introduces side-panes on the right side of the editor.
Since then, extension has not changed the background.

Assuming they have moved stuff around in the stylesheet.

**Comment by Oracuda** [comment]
I can vouch, It's compltely broken and I can't even get the image uninstalled, even after reinstalling, changing, etc, the restart prompt doesnt show up so im guessing its not detecting the changes anymore, changing the system files doesnt seem to work either, I'm stuck with the image.

**Comment by NoDocCat** [comment]
I'm sorry. I did not reproduce the problem. Can you provide your config file?

![image](https://user-images.githubusercontent.com/20502666/154919721-b1891b71-0e1f-496e-9885-384742e0356e.png)

**Comment by mkholt** [comment]
The issue actually seems to have resolved itself.
It's acting a bit finicky with changing the values, but that might just be slowness on my end.

Would love for the background to also be set on the new side-pane and the code-map, but that seems to be a feature request.

**Comment by NoDocCat** [comment]
If you have some new idea, please tell to @shalldie , he is the project owner.

**Comment by 8NAF** [comment]
Try reinstalling VS Code. I had the same issue and it was solved after I reinstalled VS Code.

**Comment by shalldie** [comment]
I guess the image on the disk may be changed sometime?

The protocol `https` is preferred, you can upload the image to some cdn website, and config the url starts with `https`
