### ISSUE TITLE
How to remove this extension

### ISSUE THREAD

**Issue by ghost** [shalldie/vscode-background#281]
How Can I remove touhou girl from my editor It still appears even after uninstalling this extension

**Comment by NoDocCat** [comment]
Set the config  {"background.enabled": false}  in settings.json, then uninstall the plugin

**Comment by FpXAddEFhJNdzjp** [comment]
It worked for me! thank you

**Comment by NormalProfessor** [comment]
how to modify it? i don't know anything about .json,F extension

**Comment by NormalProfessor** [comment]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/89129445/167399058-434dd620-9b20-4af8-8651-a8496b7f6d64.png">
