### ISSUE TITLE
Cannot set background image

### ISSUE THREAD

**Issue by SakanaKochiya** [shalldie/vscode-background#282]
I tried a lot of ways but it seems that the background wont load up
My setting.json
```{
  "background.enabled": true,
"background.useDefault": false,
"background.useFront": true,
"background.style": {
"pointer-events": "none",
"position": "absolute",
"width": "100%",
"height": "100%",
"background-repeat": "no-repeat",
"opacity": 1
},
"background.customImages": [
"C:/a.png"
],
}

**Comment by NoDocCat** [comment]
Plugin only support `file` or `https` protocol

**Comment by SakuraKaslana** [comment]
> Plugin only support `file` or `https` protocol

Tried with HTTPS and file protocols, also not work

**Comment by shalldie** [comment]
@SakuraKaslana 

Can default images appear?

If so, validate the urls you provide, https://github.com/shalldie/vscode-background/issues/266#issuecomment-931226595

**Comment by Ch3ru09** [comment]
umm, so, does it still not work?
i think i found a fix to it

**Comment by aorozco-caemsa** [comment]
> 

you need this form the files from windows

"file://C:/Myfolders/file.jpg"
