### ISSUE TITLE
建议添加一段配置模板方便参考

### ISSUE THREAD

**Issue by ExistNotSee** [shalldie/vscode-background#284]
建议在README.md 文件中添加一段配置模板，
比如我在配置时出现了这些错误配置。
"background.customImages": [
         “D:\04.jpg”
    ]
"background.customImages": [
         “D:\\04.jpg”
    ]

我不知道路径前面需要加“file:///”，导致解决这个问题花费了我许多时间
"background.customImages": [
         “file:///D:\\04.jpg”
    ]

**Comment by shalldie** [comment]
才认识到，你说的有道理，，我添加一下

**Comment by vachelyang** [comment]
"background.customImages" 后面能不能直接传一个文件夹的名字， 不要做成数组了。每次在文件夹下随机找张图片渲染就好了

**Comment by shalldie** [comment]
@vachelyang 
因为图片不一定在本地，所以才需要这样。
更推荐图片放在 https:// ，vscode对于本地资源存在很多限制
