### ISSUE TITLE
修改自定义图片地址后如何起效呢

### ISSUE THREAD

**Issue by kidrue** [shalldie/vscode-background#286]
"background.customImages":[
    
    "https://i.pximg.net/img-master/img/2017/08/29/18/51/39/64680369_p0_master1200.jpg"]

**Comment by shalldie** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/9987486/161055204-655d432d-ff9c-4b7b-8268-cc40461ee45f.png">

https://github.com/shalldie/vscode-background#config-%E9%85%8D%E7%BD%AE%E9%A1%B9

需要设置 `background.useDefault` 为 `false` 来使用自定义图片
