### ISSUE TITLE
这个可以支持全窗口的背景吗，还有选择图片文件夹进行自动轮播，设置轮播时长

### ISSUE THREAD

**Issue by Fan223** [shalldie/vscode-background#288]

**Comment by shalldie** [comment]
选择文件夹不行，vscode对本地文件有限制，
目前第一次选择本地文件的时候，就会读取到配置

没有轮播的计划，，，

全窗口可以通过自定义样式搞定，参考：https://github.com/shalldie/vscode-background/issues/268#issuecomment-1008863550

**Comment by Fan223** [comment]
没有起作用，还是只在工作区有。不过感觉也还不错。
血书上轮播，挽救一下重度患者。

**Comment by chenzao1024** [comment]
现在确实不能起作用了

**Comment by shalldie** [comment]
全屏在计划中：https://github.com/shalldie/vscode-background/issues/305#issuecomment-1196314614

**Comment by shalldie** [comment]
[全屏幕背景](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E5%85%A8%E5%B1%8F%E9%85%8D%E7%BD%AE) 已经支持，轮播会不会太夸张啊 😂

**Comment by shalldie** [comment]
添加了轮播功能： 
[默认模式 background.interval](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE)
[全屏模式 background.fullstreen](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E5%85%A8%E5%B1%8F%E9%85%8D%E7%BD%AE)

**Comment by Fan223** [comment]
爱了爱了！

**Comment by Fan223** [comment]
> 添加了轮播功能： [默认模式 background.interval](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE) [全屏模式 background.fullstreen](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E5%85%A8%E5%B1%8F%E9%85%8D%E7%BD%AE)

爱了爱了！
