### ISSUE TITLE
Visual Studio Code更新到1.66.2 背景图不显示默认图片也是如此

### ISSUE THREAD

**Issue by idzyr** [shalldie/vscode-background#289]
## 版本信息
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

版本: 1.66.2 (system setup)
提交: dfd34e8260c270da74b5c2d86d61aee4b6d56977
日期: 2022-04-11T07:46:01.075Z (1 周前)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by NoDocCat** [comment]
未能复现, 1.66.2 版本下插件表现正常, 请您提供一下您的配置文件

![image](https://user-images.githubusercontent.com/20502666/164954984-e788a6c2-1653-416d-879f-c680f5d9d7eb.png)

**Comment by idzyr** [comment]
> 未复现, 1.66.2 版本下插件正常, 请您提供一下您的配置文件
> 
> ![图片](https://user-images.githubusercontent.com/20502666/164954984-e788a6c2-1653-416d-879f-c680f5d9d7eb.png)

插件配置使用的默认，vs用的版本不一样，
![捕获](https://user-images.githubusercontent.com/38239519/164975118-7aaa2a1b-53d7-4dbd-91f7-6b77d882cab8.PNG)

- 使用 System 版本vs安装插件后不显示背景，必须以管理员身份运行一次vs插件才能正常使用。
- 如果在同一台设备上同时安装User 和 System 版本的vs，只要在User 版本中安装插件，System 版本中就可以正常使用。

**Comment by NoDocCat** [comment]
@idzyr System 版本是安装在 `Program Files` 下的, 常规用户运行没有写入权限. 所以必须用管理员身份运行一次才会生效.

**Comment by idzyr** [comment]
> @idzyr System 版本是安装在 `Program Files` 下的, 常规用户运行没有写入权限. 所以必须用管理员身份运行一次才会生效.

@NoDocCat 哦，可能是我之前卸载user版本时，没有卸载干净安装，system版本后又用了之前的配置所以能正常显示，估计升级到新版本有了变化所以不显示了。
