### ISSUE TITLE
请问一下，settings.json写在哪里

### ISSUE THREAD

**Issue by StudentWan** [shalldie/vscode-background#29]
不知道写在哪里 囧

**Comment by shalldie** [comment]
win下在【文件】-【首选项】-【用户设置】里面

mac下在【Code】-【首选项】-【用户设置】里面，快捷键是： Command+,

这个是专门给用户配置用的文件，我以为大家都知道的，但是好多人没用过      😂😂

**Comment by StudentWan** [comment]
找到了，是我傻逼了。。。不过还有一个问题~~楼主这个插件是要可以调图片的透明程度么，还是说需要找那种透明的图片

**Comment by shalldie** [comment]
@StudentWan 
透明度不能调，，，node的图片处理比较麻烦我没弄
用半透明图片吧，你值得拥有~

**Comment by StudentWan** [comment]
好的，谢谢楼主~~~
