### ISSUE TITLE
请问是在哪个 `settings.json` 里面添加

### ISSUE THREAD

**Issue by NormalProfessor** [shalldie/vscode-background#290]
请问是在哪个 `settings.json` 里面添加

_Originally posted by @Roc136 in https://github.com/shalldie/vscode-background/issues/119#issuecomment-655452487_

**Comment by batu1579** [comment]
`文件` -> `首选项` -> `设置` -> 右上角 `打开设置（json）`

**Comment by shalldie** [comment]
之后会在文档添加这部分说明
