### ISSUE TITLE
写的什么烂插件？这卸载也太麻烦了吧，有考虑一点都不懂js的人的感受吗？

### ISSUE THREAD

**Issue by NormalProfessor** [shalldie/vscode-background#291]

**Comment by NormalProfessor** [comment]
自己撂下一句话说改一下背景可见的bool变量，但是实际上你说的那个js文件都找不到，哪里有setting的json文佳，我电脑给你远程操控，你来，我真服了，为什么会有插件写得那么烂啊，卸载不会自动清除码？有没有站在用户的角度想一想，他们一天盯着他们呢不喜欢的那个破卡通人物半天，还卸载不了，也不想重装vsc的心情？lj

**Comment by QUALIAZX** [comment]
兄弟，不是我说，人回复的那么明白https://github.com/shalldie/vscode-background/issues/290#issuecomment-1122537149

这智商别写代码了真的

**Comment by QUALIAZX** [comment]
看不懂的话

```ctrl + shift + p```

输入```>settings.json```

到这里再看不懂我也没办法了放弃治疗吧

**Comment by shalldie** [comment]
不好意思，这是由于vscode的限制，有在readme中说明。

之后我再完善下文档吧，把这部分突出下。
