### ISSUE TITLE
Whole Screen background

### ISSUE THREAD

**Issue by q-desabre** [shalldie/vscode-background#295]
Hi,

As the name suggest, is it possible to only have one background image instead of having it duplicating itself or looping for each tab ?

I tried to mess a bit with the css, but I think it's a different settings ?

Or another way to avoid the gap between tabs ? ( see picture )

Thanks 

![Example_gap](https://user-images.githubusercontent.com/72790131/175784555-af0243e5-4a1a-4e11-867f-ecc87afc0eca.png)

**Comment by shalldie** [comment]
Have a try this: https://github.com/shalldie/vscode-background/issues/268#issuecomment-1008863550

**Comment by shalldie** [comment]
in progress: https://github.com/shalldie/vscode-background/issues/305#issuecomment-1196314614

**Comment by shalldie** [comment]
Have a try of [fullscreen in v1.2.2](https://github.com/shalldie/vscode-background#fullscreen-config)
