### ISSUE TITLE
我只想加个纯背景色，如何设置

### ISSUE THREAD

**Issue by gaoqiuling** [shalldie/vscode-background#30]
我只想加个纯背景色，如何设置

**Comment by shalldie** [comment]
@gaoqiuling 
只要背景色，其他的都不要吗？
这个插件是用来添加背景图的，没改背景色的功能。
。。。暂时没这个功能，我会考虑在下个版本中添加。

**Comment by gaoqiuling** [comment]
楼主回复好快啊~惊艳中。。。
我想有个纯背景色，在背景色上再加一张小图片~
哈哈，等你下个版本啊~~~赞赞赞~~~ @shalldie

**Comment by shalldie** [comment]
不好意思少年，前两天才更新，你来试试
