### ISSUE TITLE
vscode 1.69.2 无法展示背景图片

### ISSUE THREAD

**Issue by wopelo** [shalldie/vscode-background#300]
vscode自动升级到1.69.2，升级完成后原本可以展示的背景图片无法展示
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/22694145/179891276-b39af4ed-f47e-48d2-9025-cf3c993ea9fc.png">
系统：mac os monterey12.3.1
配置：
```
{
       "background.customImages": [
		"file:///Users/mac/Pictures/background/bg_b_pro.jpg",
		"file:///Users/mac/Pictures/background/bg_a_pro.jpg",
		"file:///Users/mac/Pictures/background/bg_c_pro.jpg",
		"file:///Users/mac/Pictures/background/bg_d_pro.jpg",
		"file:///Users/mac/Pictures/background/bg_e_pro.jpg"
	],
	"background.style": {
		"opacity": 0.4,
		"content": "''",
		"pointer-events": "none",
		"position": "absolute",
		"z-index": "99999",
		"width": "100%",
		"height": "100%",
		"background-position": "100% 100%",
		"background-size": "cover",
		"background-repeat": "no-repeat"
	},
	"background.useDefault": false,
	"background.useFront": false
}
```

**Comment by frg2089** [comment]
扩展会通过修改VSCode的样式文件来添加背景图片（这会破坏VSCode 导致你的VSCode显示{不受支持]）
每次升级后 被修改的样式文件会被还原
你需要重新修改这个配置文件

你可以尝试sudo运行VSCode

**Comment by zjclxx** [comment]
自定义图片显示不了，设置默认图片就可以显示，请问是什么情况，vscode版本1.69.2

**Comment by zjclxx** [comment]
原因是点击了这个
![image](https://user-images.githubusercontent.com/62633990/179908896-cbb38884-31eb-4009-850e-c1f8eca049c0.png)
然后我降版本，后重启，又重新升版本过来了，不知道什么原因

**Comment by NoDocCat** [comment]
@shalldie @frg2089 
问题在这里:
https://github.com/shalldie/vscode-background/blob/e04914bbcd23731764a71da34e91cb13d0772128/src/getCss.ts#L33-L33
https://github.com/shalldie/vscode-background/blob/e04914bbcd23731764a71da34e91cb13d0772128/src/getCss.ts#L71-L73

toString之后路径变成了 `[object Promise]`

**Comment by NoDocCat** [comment]
@frg2089 我看了一下 PR, 原来的写法也存在问题:

```ts
const list = images.map(async url => {
  return url.startsWith('file://') ? await loadImageBase64FromFileProtocol(url) : url;
});
```

不要在 map, forEach 之类的方法回调里使用 async function, 就算加了 await, list 也会变成 `Promise<string>[]`

**Comment by machinister** [comment]
只是对本地路径支持有问题，将自定义的图片改成base64 就可以了

**Comment by DearXuan7392** [comment]
转base64成功解决问题,就是json里看起来不太美观

**Comment by shalldie** [comment]
看到的有点晚，紧急发布了 `v1.2.1` 修复了该问题。

这次更新了大量的 async，遗漏了部分内容 =。=

**Comment by keyork** [comment]
没毛病没毛病，我这里可以正常work
<img width="459" alt="image" src="https://user-images.githubusercontent.com/50315126/180117179-5cbb964a-c95d-4847-ac0a-d981ae1e338e.png">

**Comment by wopelo** [comment]
这边正常了，又可以快乐搬砖了

**Comment by whenk7** [comment]
坏了啊，不显示自定义的

**Comment by whenk7** [comment]
坏了啊，不显示自定义的

**Comment by frg2089** [comment]
> 坏了啊，不显示自定义的

你可以发一下你的配置

**Comment by keyork** [comment]
> 坏了啊，不显示自定义的

以下代码在我的电脑上是work的：
```json
"background.useDefault": false,
    "background.customImages": [
        "file:///D:/install/VSCode/background-2560x1440.jpg"
    ],
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "center",
        "background-repeat": "no-repeat",
        "background-size": "cover",
        "opacity": 0.2
    },
```
看看你的图像路径是否以file:///开头？或者background.useDefault是否设置为false？

**Comment by frg2089** [comment]
> 看看你的图像路径是否以file:///开头？或者background.useDefault是否设置为false？

还有自定义样式有没有忘写
```json
{
  "content": "''",
}
```

**Comment by Sam5440** [comment]
> > 坏了啊，不显示自定义的
> 
> 以下代码在我的电脑上是work的：
> 
> ```json
> "background.useDefault": false,
>     "background.customImages": [
>         "file:///D:/install/VSCode/background-2560x1440.jpg"
>     ],
>     "background.style": {
>         "content": "''",
>         "pointer-events": "none",
>         "position": "absolute",
>         "z-index": "99999",
>         "width": "100%",
>         "height": "100%",
>         "background-position": "center",
>         "background-repeat": "no-repeat",
>         "background-size": "cover",
>         "opacity": 0.2
>     },
> ```
> 
> 看看你的图像路径是否以file:///开头？或者background.useDefault是否设置为false？

The same settings doesn't work in mine.the version of vscode is 1.69.2,too.

**Comment by Sam5440** [comment]
"winopacity.opacity": 225,
    "background.useDefault": false,
    "background.customImages": [
        "file:///C:/vs.jpg"
    ],
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "center",
        "background-repeat": "no-repeat",
        "background-size": "cover",
        "opacity": 0.5
    },
    "background.useFront": false,
}

> > > 坏了啊，不显示自定义的
> > 
> > 
> > 以下代码在我的电脑上是work的：
> > ```json
> > "background.useDefault": false,
> >     "background.customImages": [
> >         "file:///D:/install/VSCode/background-2560x1440.jpg"
> >     ],
> >     "background.style": {
> >         "content": "''",
> >         "pointer-events": "none",
> >         "position": "absolute",
> >         "z-index": "99999",
> >         "width": "100%",
> >         "height": "100%",
> >         "background-position": "center",
> >         "background-repeat": "no-repeat",
> >         "background-size": "cover",
> >         "opacity": 0.2
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看看你的图像路径是否以file:///开头？或者background.useDefault是否设置为false？
> 
> The same settings doesn't work in mine.the version of vscode is 1.69.2,too.

    "winopacity.opacity": 225,
    "background.useDefault": false,
    "background.customImages": [
        "file:///C:/vs.jpg"
    ],
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "center",
        "background-repeat": "no-repeat",
        "background-size": "cover",
        "opacity": 0.5
    },
    "background.useFront": false,
}

**Comment by zjclxx** [comment]
> ```
> "winopacity.opacity": 225,
> "background.useDefault": false,
> "background.customImages": [
>     "file:///C:/vs.jpg"
> ],
> "background.style": {
>     "content": "''",
>     "pointer-events": "none",
>     "position": "absolute",
>     "z-index": "99999",
>     "width": "100%",
>     "height": "100%",
>     "background-position": "center",
>     "background-repeat": "no-repeat",
>     "background-size": "cover",
>     "opacity": 0.5
> },
> "background.useFront": false,
> ```
> 
> }
> 
> > > > 坏了啊，不显示自定义的
> > > 
> > > 
> > > 以下代码在我的电脑上是work的：
> > > ```json
> > > "background.useDefault": false,
> > >     "background.customImages": [
> > >         "file:///D:/install/VSCode/background-2560x1440.jpg"
> > >     ],
> > >     "background.style": {
> > >         "content": "''",
> > >         "pointer-events": "none",
> > >         "position": "absolute",
> > >         "z-index": "99999",
> > >         "width": "100%",
> > >         "height": "100%",
> > >         "background-position": "center",
> > >         "background-repeat": "no-repeat",
> > >         "background-size": "cover",
> > >         "opacity": 0.2
> > >     },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看看你的图像路径是否以file:///开头？或者background.useDefault是否设置为false？
> > 
> > 
> > The same settings doesn't work in mine.the version of vscode is 1.69.2,too.
> 
> ```
> "winopacity.opacity": 225,
> "background.useDefault": false,
> "background.customImages": [
>     "file:///C:/vs.jpg"
> ],
> "background.style": {
>     "content": "''",
>     "pointer-events": "none",
>     "position": "absolute",
>     "z-index": "99999",
>     "width": "100%",
>     "height": "100%",
>     "background-position": "center",
>     "background-repeat": "no-repeat",
>     "background-size": "cover",
>     "opacity": 0.5
> },
> "background.useFront": false,
> ```
> 
> }

可以尝试老版本

**Comment by keyork** [comment]
> ```
> "winopacity.opacity": 225,
> "background.useDefault": false,
> "background.customImages": [
>     "file:///C:/vs.jpg"
> ],
> "background.style": {
>     "content": "''",
>     "pointer-events": "none",
>     "position": "absolute",
>     "z-index": "99999",
>     "width": "100%",
>     "height": "100%",
>     "background-position": "center",
>     "background-repeat": "no-repeat",
>     "background-size": "cover",
>     "opacity": 0.5
> },
> "background.useFront": false,
> ```
> 
> }
> 
> > > > 坏了啊，不显示自定义的
> > > 
> > > 
> > > 以下代码在我的电脑上是work的：
> > > ```json
> > > "background.useDefault": false,
> > >     "background.customImages": [
> > >         "file:///D:/install/VSCode/background-2560x1440.jpg"
> > >     ],
> > >     "background.style": {
> > >         "content": "''",
> > >         "pointer-events": "none",
> > >         "position": "absolute",
> > >         "z-index": "99999",
> > >         "width": "100%",
> > >         "height": "100%",
> > >         "background-position": "center",
> > >         "background-repeat": "no-repeat",
> > >         "background-size": "cover",
> > >         "opacity": 0.2
> > >     },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看看你的图像路径是否以file:///开头？或者background.useDefault是否设置为false？
> > 
> > 
> > The same settings doesn't work in mine.the version of vscode is 1.69.2,too.
> 
> ```
> "winopacity.opacity": 225,
> "background.useDefault": false,
> "background.customImages": [
>     "file:///C:/vs.jpg"
> ],
> "background.style": {
>     "content": "''",
>     "pointer-events": "none",
>     "position": "absolute",
>     "z-index": "99999",
>     "width": "100%",
>     "height": "100%",
>     "background-position": "center",
>     "background-repeat": "no-repeat",
>     "background-size": "cover",
>     "opacity": 0.5
> },
> "background.useFront": false,
> ```
> 
> }

会不会是因为放到C盘的权限问题？可以试试以管理员权限打开VSCode

**Comment by frg2089** [comment]
可以看看`Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css`文件是否有被修改过
有被修改过的话 应该会存在类似这样的内容
```css
/*css-background-start*/
/*background.ver.1.2.0*/
...
/*css-background-end*/
```
