### ISSUE TITLE
功能请求-在欢迎页应用背景图片

### ISSUE THREAD

**Issue by frg2089** [shalldie/vscode-background#303]
重新打开 #279
因为提交 b96cd5934eb2a70ce11985feb289beb2f4c22e71 的修改在提交 2d71baddb9d1242fe76c581b06926fbeeff53db9 被移除

_Originally posted by @frg2089 in https://github.com/shalldie/vscode-background/issues/279#issuecomment-1189833934_

**Comment by shalldie** [comment]
原本的背景定位是在【代码区域】，v1.2.2添加了【全屏】支持。
