### ISSUE TITLE
feature - 全屏背景图（fullscreen background image）

### ISSUE THREAD

**Issue by shalldie** [shalldie/vscode-background#305]
## 背景

因为以前可以通过 `background.style` 来实现全屏，所以一直不觉得是个问题，，，

但是以下几个方面形成了制约：
1. 用户的css功底不怎么好
2. 插件文档简陋（前段时间整理了一版）
3. vscode更新导致原css方式不能很好的工作

### 实现方式

这个倒是简单，添加个 `body` 的样式就行。

### 配置项
因此打算添加个专门项配置如下，此api友好度有兴趣的朋友可以提一下意见。

```json
{
    "background.fullscreen": {
        "url": "https://a.com/b.png", // 图片地址
        "background-size": "cover", // 大小
        "opacity": 0.6 // 透明度
    }
}

```

## 待确认的点

1. 全屏背景不适合复用之前的配置。
    - 太臃肿也不好控制。
    - 最好单独列出配置项？
2. 全屏需要提供哪些配置项？
    - 是否不需要太灵活呢。只用提供`url`、`opacity` 是否就够了
    - 如果配置少就打平（以后不好扩展）

**Comment by zjclxx** [comment]
![2B93A77264992D0871FC754DB0DDF25F](https://user-images.githubusercontent.com/62633990/181176331-c1fad092-ef12-42e7-bd90-2215e88e4542.jpg)

**Comment by frg2089** [comment]
> * 全屏背景不适合复用之前的配置。
>   
>   * 最好单独列出配置项？

能单独列出来配置项比较好

> * 全屏需要提供哪些配置项？

直接CSS

可以先把开发中的扩展推到测试版上，等稳定后再推到正式版里

**Comment by grauspitz** [comment]
单独给个侧边配置吧，默认配置的话可以裁当前操作区背景图片的左侧给个高糊效果那种

**Comment by shalldie** [comment]
这段时间太忙了，这周末一定搞定 =。=

**Comment by MuuuShin** [comment]
#268

**Comment by shalldie** [comment]
食言了，，，因为两部分事情耽误：

1. Dota2 ti 赛事
2. 工作上的事情

lgd 跟 rng 已经出局，
工作上的事情大概到下周三能够结束。
所以下周一定 😂😂 ，目前进度：【新建分支】

**Comment by zjclxx** [comment]
> 食言了，，，因为两部分事情耽误：
> 
> 1. Dota2 ti 赛事
> 2. 工作上的事情
> 
> lgd 跟 rng 已经出局， 工作上的事情大概到下周三能够结束。 所以下周一定 😂😂 ，目前进度：【新建分支】

新建文件夹是吧

**Comment by shalldie** [comment]
功能已经完成，周一趁上班时间更新下文档，简单测试下然后发布 =。=

**Comment by frg2089** [comment]
> 功能已经完成，周一趁上班时间更新下文档，简单测试下然后发布 =。=

好 马上就给你发一个pr
用vscode-file协议替换掉base64的实验性方案

**Comment by shalldie** [comment]
Ready， https://github.com/shalldie/vscode-background/pull/326
感兴趣的老哥们看看，对于实现、配置方式，是否有不同的想法。
今天等等反馈，没问题明天发布吧 👀
