### ISSUE TITLE
卸载插件之后重启vscode崩溃

### ISSUE THREAD

**Issue by Wakotu** [shalldie/vscode-background#306]
![W6V~}VBVV HVO``1(B{TO O](https://user-images.githubusercontent.com/58961498/182278745-2ad1ec21-422e-4bb1-a050-c5882d16c69f.png)
重启后一直是这副样子

**Comment by shalldie** [comment]
请先重装 `vscode`吧，不好意思。
这个问题还没能复现，我找时间研究研究。

**Comment by chenjiecloud** [comment]
最近我也遇到这个问题了，就是在vscode更新完，重启就变成这个样子了

**Comment by ddosakura** [comment]
同遇到该问题，似乎不仅是vscode更新导致。

我这边有原本打开的vscode显示正常（起码一个多月没关了；因为个人不喜欢关软件，vscode经常一开就个把月不关），新窗口样式崩了的情况。

因为vscode存在未关闭的窗口，所以vscode本身应该是没有更新的（重启后才会更新）。

vscode能在运行时更新已安装的插件，之前有遇到过从来没关过的vscode因为volar插件后台自动更新导致lsp版本不兼容，lsp无法使用的情况，需要重启更新vscode。

怀疑在vscode未关闭的情况下后台自动更新该插件会导致该问题（表现为更新前的窗口正常，新打开的窗口样式崩溃）。

**Comment by shalldie** [comment]
> 同遇到该问题，似乎不仅是vscode更新导致。
> 
> 我这边有原本打开的vscode显示正常（起码一个多月没关了；因为个人不喜欢关软件，vscode经常一开就个把月不关），新窗口样式崩了的情况。
> 
> 因为vscode存在未关闭的窗口，所以vscode本身应该是没有更新的（重启后更新才会生效）。
> 
> vscode能在运行时更新已安装的插件，之前有遇到过从来没关过的vscode因为volar插件后台自动更新导致lsp版本不兼容，lsp无法使用的情况，需要重启更新vscode。
> 
> 两个可能的怀疑：
> 
> 1. 在vscode未关闭的时，后台自动更新该插件会导致该问题
> 2. 在vscode未关闭的时，vscode自动更新覆盖了样式文件，但更新本身需要重新生效
> 
> 表现为更新前的窗口正常，新打开的窗口样式崩溃
> 
> vscode: 1.71.2
> 
> 损坏的 ![image](https://user-images.githubusercontent.com/26789963/192218397-6feed848-9949-45c3-a204-10893ee2ed5f.png)
> 
> 正常的 ![image](https://user-images.githubusercontent.com/26789963/192218430-43811964-1783-4e50-b41b-6cfe4b6d7eda.png)
> 
> 对比 ![image](https://user-images.githubusercontent.com/26789963/192219029-09a4cbba-936b-4dfc-a80a-5afcbf251e90.png)
> 
> 应该是vscode原本的样式都不见了
> 
> 建议之后变动这个文件的时候做下备份，恢复这个文件就一切正常了

当前的策略是直接对css做修改，有时候造成css丢失，我在想是不是多个vscode一起写入造成的。
之后会考虑先备份，基于备份文件生成新css。我想想怎么保持备份同步。

**Comment by shalldie** [comment]
发布了 v1.2.3 修复该问题。
方案: https://github.com/shalldie/vscode-background/pull/332
PR: https://github.com/shalldie/vscode-background/issues/329
