### ISSUE TITLE
想要预览图里的3张背景，能发一下么？

### ISSUE THREAD

**Issue by mokeyjay** [shalldie/vscode-background#31]
芙兰好可爱啊！！！
要是有其他角色的也请发一下

**Comment by shalldie** [comment]
链接: http://pan.baidu.com/s/1jGnbGcm 密码: 4yix

这是一个朋友给我分享的网盘，上面是原地址。

**Comment by mokeyjay** [comment]
感谢dalao

**Comment by Xmaoyuo** [comment]
Interesting /滑稽

**Comment by mokeyjay** [comment]
@Xmaoyuo 手写了一段辣鸡JS把三张图用在[我的博客](https://www.mokeyjay.com/)了XD

**Comment by Xmaoyuo** [comment]
@mokeyjay Exciting~/滑稽

**Comment by Xmaoyuo** [comment]
各位大佬们加企鹅群吗？215791619 Magic&Science

**Comment by fyzzy1943** [comment]
nice
