### ISSUE TITLE
如何开启循环背景图？

### ISSUE THREAD

**Issue by sangjunke** [shalldie/vscode-background#311]
background.customImages数组定义了三张图片，但是每次都是第一个元素的图，如何开启循环，每次打开标签使用不同的背景图

**Comment by shalldie** [comment]
`background.loop` 可以控制循环展示图片。

比如定义了3张图，对应的tab就会按照  1 2 3 1 2 3 1 2 3 来展示。

**Comment by sangjunke** [comment]
> `background.loop` 可以控制循环展示图片。
> 
> 比如定义了3张图，对应的tab就会按照 1 2 3 1 2 3 1 2 3 来展示。

我background.customImages数组定义了三张图片，"background.loop": false，每次打开新的标签 都是第一张图片呀，没有按照你说的顺序来

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/188382897-22f4891f-2d23-4380-8d8f-71682c6a853a.png)

这里的tab值得是vscode中split出的新页面，比如我这里定义了2张图，开启了loop:true就会循环显示。
或者你把配置发出来看看。

**Comment by sangjunke** [comment]
我顿悟了  感谢大佬恢复
