### ISSUE TITLE
Ubuntu 20.04 完全无作用（vscode的问题？）

### ISSUE THREAD

**Issue by YYHEggEgg** [shalldie/vscode-background#312]
翻了翻issue好像没有找到

就是插件完全失效，默认图片也不显示，**改settings,json插件不会提示重启vscode**

settings.json 内容：无 `background` 插件的设置内容（事实上改别的也不会有变化）

**Comment by shalldie** [comment]
在 code-server 中测试了下 ubuntu 20.04，因条件限制没能测试客户端的情况。

能否看一下控制台呢？看看是否有报错之类
另外 check 下 vscode 是否位于临时目录，比如 `/var` 、`/temp`、`/tmp` 之类，需要移出来

**Comment by frg2089** [comment]
你的系统中有`kdesudo`或`pkexec`吗？

vscode不允许以root身份运行
一般情况下，扩展没有权限修改vscode目录下的css文件。
这个扩展使用`sudo-prompt`(或许以后是`@vscode/sudo-prompt`）。
它**不支持**`gksudo`，而是使用`kdesudo`或`pkexec`来提权修改css文件。
[@vscode/sudo-prompt behavior](https://github.com/bpasero/sudo-prompt#behavior)

你可以试试给`workbench.desktop.main.css`设置666权限来允许任何人修改

**Comment by NoDocCat** [comment]
尝试找到 vscode 的安装目录, 用 `chown` 把文件所有权改为你当前使用的账户和组
