### ISSUE TITLE
The format of local file?

### ISSUE THREAD

**Issue by ketchup3313** [shalldie/vscode-background#313]
I'm using Win11 and copy the path of file, if it's my path format problem?
"C:\Users\xxx\Documents\icon\niu.png"
its my path, I can change the background img from internet with "https:// " and the path is correct 
是我的路径错了还是有其他的问题？谢谢:)

**Comment by shalldie** [comment]
本地图片是 file 协议的，
最简单的方式可以把图片拖到浏览器中，然后从地址栏复制 url 👌

**Comment by K1ethoang** [comment]
It's working with me ! you can test. 
```json

"background.customImages": [
    "file:///C:/folder/folder/folder/image/logo.png"
  ]

````
