### ISSUE TITLE
can't solve

### ISSUE THREAD

**Issue by RiceYangCoder** [shalldie/vscode-background#316]
there is a problem trouble me
`EPERM: operation not permitted, open 'd:\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css'`

**Comment by shalldie** [comment]
In windows, try click right button on the vscode's icon,then check the [run with the administrator authority].

**Comment by shalldie** [comment]
Has been resolved?

**Comment by cjwijtmans** [comment]
no it has not been solved. I will not run vscode as admin ☠ No piece of regular software should be run as admin.

**Comment by NoDocCat** [comment]
@cjwijtmans You should use `User Installer` instead of `System Installer`

**Comment by cjwijtmans** [comment]
no.

**Comment by NoDocCat** [comment]
@cjwijtmans You do not provide the environment. Software not working for you. it's reasonable.

**Comment by cjwijtmans** [comment]
nah its not.
