### ISSUE TITLE
背景图无法很好的显示

### ISSUE THREAD

**Issue by Nova-Noir** [shalldie/vscode-background#318]
根据 #305 以及其他相关 issue ，尝试了不少操作。
但除了无法显示全屏外，甚至连工作区都无法覆盖完全。
![normal](https://user-images.githubusercontent.com/68760718/196037952-d4b1ff3b-97eb-4104-bb90-b148b53e6c92.png)
![fullscreen](https://user-images.githubusercontent.com/68760718/196038060-2156771e-9ef2-41f6-8660-9222c7ed90d4.png)

使用 `right: "5px",` 的魔法后也不能把 `terminal` 那个视图覆盖。

使用的是最新版本
![image](https://user-images.githubusercontent.com/68760718/196038006-92bf34ac-d2af-4577-a5e9-7529193364f1.png)

附上 json:
<details>

```json
    "background.style": {

    
        "background-size": "cover",
        "position": "fixed",
        "content": "''",
        "pointer-events": "none",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "right": "5px",

        "opacity": 0.3,
        "background-repeat": "no-repeat",
    },
```

</details>

**Comment by xinkid520** [comment]
terminal默认是有颜色的，需要修改为透明色
```json
"workbench.colorCustomizations": {
		"terminal.background": "#00000000",
}
```
关于图片显示不正常的问题,这是我正在使用的配置，希望能帮到你
```json
"background.style": {
		"position": "fixed",
		"z-index": "1",
		// "width": "100vw",
		// "height": "100vh",
		"left": "0px",
		"top": "0px",
		"background-position": "center",
		"background-repeat": "no-repeat",
		"opacity": 0.25,
		"background-size": "cover",
		"background-attachment": "fixed"
	},
```
效果如下
![image](https://user-images.githubusercontent.com/46767489/196875922-ae17fd6c-b21a-4825-aaaa-11125e20b404.png)

**Comment by shalldie** [comment]
发布了全屏的功能，老哥们试试～
Have a try of [fullscreen in v1.2.2](https://github.com/shalldie/vscode-background#fullscreen-config)
