### ISSUE TITLE
有可能添加随机背景图或者自动轮播背景图的功能吗？

### ISSUE THREAD

**Issue by MuuuShin** [shalldie/vscode-background#319]
如题，有没有可能加上每开启vscode时在图片序列中随机选取一张的功能
还有自动轮播，单屏内定时切换背景图那种（不过感觉这功能做出来观感不一定很好，反而可能会影响注意力之类的）

**Comment by shalldie** [comment]
目前没有考虑随机背景图。

就像你说的，影响注意力。

。。。也有case是这样：

1. 打开vscode，随机到图9
2. 感觉不喜欢（我就要图2），重启
3. 随机到图7，重启
4. ...
93. 随机到图2

**Comment by shalldie** [comment]
添加了轮播功能： 
[默认模式 background.interval](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE)
[全屏模式 background.fullstreen](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E5%85%A8%E5%B1%8F%E9%85%8D%E7%BD%AE)
