### ISSUE TITLE
希望dalao能添加一个随机背景的功能

### ISSUE THREAD

**Issue by mokeyjay** [shalldie/vscode-background#32]
试用了一下感觉很棒，不过如果能随机就更好了，例如
```
costomImages:[
    [pic1, pic2, pic3, ...], // 窗口1的背景从这里随机
    'window2-pic', // 指定窗口2使用此背景
    [pic1, pic2, pic3, ...], // 窗口3的背景从这里随机
]
```

感谢dalao的插件，很喜欢~

**Comment by shalldie** [comment]
这个需要用js来注入。

最开始的时候用的这种方式，后来为了轻量和简易方面的考虑，就去掉了。。。不想搞太复杂，本身只是一个简单的背景插件。

vscode 目前禁止修改系统文件，会提示【不受支持】。
我只修改了一个css文件已经很麻烦了，如果再注入js，就要再添加/修改2个文件(index.html  electron程序入口，一个需要注入的js)。。。代价太大，所以不考虑了😂😂。

**Comment by mokeyjay** [comment]
好的，谢谢dalao

**Comment by kita32** [comment]
为什么不考虑修改图片？
