### ISSUE TITLE
能在Readme里给出更详细的配置项说明吗？

### ISSUE THREAD

**Issue by alice7290** [shalldie/vscode-background#323]
Readme里的配置项说明太少了，难以更深入了解插件用法...

**Comment by shalldie** [comment]
啊，，，文档前段时间特地完善过。
具体是哪里不清楚呢？

**Comment by alice7290** [comment]
> 
想更详细的知道分别有哪些项可以设置，以及每个项能设置哪些具体参数

**Comment by shalldie** [comment]
https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E9%85%8D%E7%BD%AE%E9%A1%B9

这部分在文档有提到，所有的配置项、作用、默认值。
style 属于css样式比较自由。

**Comment by alice7290** [comment]
没给全啊，style里面能设的项很多，而且比如“position”项能设“absolute”和"fixed"值，但你文档里只写了fixed值，我又不知道除了这两个值外是否还有其余能设置的值，然后其余的一些项也是如此，我不知道能设哪些具体的值，我看到你的文档没给全，一开始还以为vscode的settings.json是不是会有提示的，但网上搜索vscode的各种配置方案都只是介绍各种项和值，所以我就认为vscode的settings.json是不会有提示告诉我能设哪些值的，于是我才发了条issue来问你

**Comment by shalldie** [comment]
style 是供用户自由输入 css，非常的自由，没办法给全，，，太多了。
所以添加了对 css 的链接进行解释。

能理解你的痛点，对于非前端程序员来说确实稍头疼，
我所能做的，是在配置的地方给了一些预设的配置项，文档提供了一些常见的设置demo。

如果有一些 idea 想要去实现，也可以开issue跟大家讨论实现。

这部分确实给不全，css是一门语言，我自己都没学明白 =。=

**Comment by alice7290** [comment]
哦，按照你的方式百度了后瞬间清晰了，感谢你的帮助哈，建议你将“css position”这类建议也在文档里写写，毕竟我认为跟我一样对这方面懵逼的应该也是有的
