### ISSUE TITLE
how to merge the sidebar with the editor?

### ISSUE THREAD

**Issue by cheemscry** [shalldie/vscode-background#324]
![how.png](https://user-images.githubusercontent.com/110283303/198878799-a8fb13d8-2c95-4f0e-8c76-4dc09917a197.png)

**Comment by shalldie** [comment]
![](https://user-images.githubusercontent.com/9987486/198958380-6eaf96c7-3aa2-4fce-b27e-6f33c8d4e2c1.png)

Do you mean fullscreen image?

Here's a new version to be published soon. https://github.com/shalldie/vscode-background/issues/305

**Comment by shalldie** [comment]
Have a try of [fullscreen in v1.2.2](https://github.com/shalldie/vscode-background#fullscreen-config)
