### ISSUE TITLE
cant see anything?

### ISSUE THREAD

**Issue by HRyohni** [shalldie/vscode-background#327]
So I accidently set background and cant remove it also can't see anything because I have put capacity up.

i tryed to find mod in files 
![Snimka zaslona 2022-10-31 190154](https://user-images.githubusercontent.com/62948056/199077421-9807e6cd-bde9-461f-b25e-31789c03772a.png)
but i couldnt.

**Comment by shalldie** [comment]
Oh, try this way:

![image](https://user-images.githubusercontent.com/9987486/199177320-0604b61f-5d47-4a74-af36-b8ab418198ba.png)

1. press `F1`
2. entry `background uninstall`
3. press `Enter`
4. reload vscode

This may uninstall this plugin

**Comment by shalldie** [comment]
Another way:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/9987486/199178719-05c6afa7-f0a3-458c-bd64-bac74002c08e.png">


1. edit the `settings.json`, set `"background.enabled": false`
2. restart vscode

This may disable this plugin, then you can edit the config again before reenable it.

**Comment by shalldie** [comment]
Is the problem solved ?

**Comment by HRyohni** [comment]
yes thanks!
