### ISSUE TITLE
使用全屏设置后 每次进vsc页面初始化都会有图片闪现

### ISSUE THREAD

**Issue by MuuuShin** [shalldie/vscode-background#328]
如图
![image](https://user-images.githubusercontent.com/97760035/199450422-cec76180-45fb-4855-be89-ff686157ffc2.png)
![image](https://user-images.githubusercontent.com/97760035/199450760-a49e19a8-1e10-4afe-8861-4b7010578a8c.png)

**Comment by MuuuShin** [comment]
这是全屏实现的副作用吗（
感觉每次开vsc闪这么一下怪怪的

**Comment by shalldie** [comment]
hh 是副作用，暂时没办法 😂😂
我其实也看到了，感觉就开启的时候闪一下还能够接受。

原因是资源的加载有先后、耗时不同。
后面我看看是否有方式可以优化吧

**Comment by MuuuShin** [comment]
加油（

**Comment by MuuuShin** [comment]
加油加油+

**Comment by MuuuShin** [comment]
加油加油

**Comment by NoDocCat** [comment]
@MuuuShin 要不试试本地文件? 本地文件会被转换成 base64 插入到 css 中, 是随着 css 文件一起加载的, 应该不会有闪烁的问题

**Comment by MuuuShin** [comment]
> @MuuuShin 要不试试本地文件? 本地文件会被转换成 base64 插入到 css 中, 是随着 css 文件一起加载的, 应该不会有闪烁的问题

已经是本地文件了

**Comment by NoDocCat** [comment]
@MuuuShin 提供一下图片文件吧, 打成 zip 扔到这个 issue 下

**Comment by MuuuShin** [comment]
跟图片无关吧？我试了好几张图均是闪现

**Comment by NoDocCat** [comment]
@MuuuShin 
大概是搞清楚了, 工作区是异步加载的, 导致初始启动时没有元素盖在 body 上. 
这个问题倒是可以用 `:has` 选择器解决, 但是当前版本的 vscode, chromium 版本是 102, `:has` 选择器在 105 版本添加的支持😂

**Comment by shalldie** [comment]
看了下 `:has` nb 啊，，确实可行，那就等更新吧～

**Comment by MuuuShin** [comment]
感谢，看来目前只能等待了

**Comment by jerrycool123** [comment]
It seems that this problem has disappeared in the latest version of VSCode.
![image](https://user-images.githubusercontent.com/45344525/221340344-9d5577ff-d59e-4002-a5b2-b1034aedc62a.png)
![image](https://user-images.githubusercontent.com/45344525/221340404-1ca7c099-d300-4b1e-9751-6a0d08436ecf.png)

**Comment by MuuuShin** [comment]
> It seems that this problem has disappeared in the latest version of VSCode. ![image](https://user-images.githubusercontent.com/45344525/221340344-9d5577ff-d59e-4002-a5b2-b1034aedc62a.png) ![image](https://user-images.githubusercontent.com/45344525/221340404-1ca7c099-d300-4b1e-9751-6a0d08436ecf.png)

Yes, it doesn't blink in the initialization, but it still has a problem -- it loses transparency during initialization
see #374

**Comment by shalldie** [comment]
久等，发布了 `1.2.11` 修复了该问题 🎉🎉
