### ISSUE TITLE
按了f1  键入命令 background-info 并没有出来 setting.json

### ISSUE THREAD

**Issue by Aaronphy** [shalldie/vscode-background#33]
求助～

**Comment by shalldie** [comment]
win下在【文件】-【首选项】-【用户设置】里面

mac下在【Code】-【首选项】-【用户设置】里面，快捷键是： Command+,

settings.json，这个是专门给用户配置用的文件，vscode自带的

**Comment by Aaronphy** [comment]
谢谢~

**Comment by Aaronphy** [comment]
覆盖了 好像没有生效～

**Comment by shalldie** [comment]
@Aaronphy 
试试开启管理员权限
