### ISSUE TITLE
当VSCode设置`"editor.stickyScroll.enabled": true`且`"background.useFront": false`时 sticky栏会挡住背景图

### ISSUE THREAD

**Issue by frg2089** [shalldie/vscode-background#330]
当VSCode设置`"editor.stickyScroll.enabled": true`且`"background.useFront": false`时 sticky栏会挡住背景图

这个问题是不可修复的，如果清除 sticky栏的背景 则会导致编辑器下方的内容和sticky栏的内容重叠

解决方案1： `"editor.stickyScroll.enabled": false` 关闭sticky栏
解决方案2： `"background.useFront": true` 使用“前景图”（图片前置）

**Comment by shalldie** [comment]
看了下是有这个问题。

`useFront: false` 是代码区域下方。不仅是 stickyScroll ，还有 miniMap 也会遮挡住。
调整style或者用前景模式吧。

**Comment by frg2089** [comment]
> 不仅是 stickyScroll ，还有 miniMap 也会遮挡住。

实际上 我通过设置minimap背景色为透明色解决了这个问题

我在 #304 有提到过
