### ISSUE TITLE
loop模式

### ISSUE THREAD

**Issue by z-Zihan** [shalldie/vscode-background#331]
hi  作者你好，请问 loop模式是如何设置自动轮播的（试了好几次 不好使，文档也没找到），以及如何设置间隔多久轮播。

还有  全屏模式  fullscreen  可不可以支持轮播呢

**Comment by shalldie** [comment]
loop 不是轮播哈～ 是循环的意思

默认3张图片对应3个view，如果开了第4、5、6.... 个view的时候，loop就会循环展示之前设置的图片

**Comment by shalldie** [comment]
添加了轮播功能哈： [全屏模式Demo](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E5%85%A8%E5%B1%8F%E9%85%8D%E7%BD%AE)
