### ISSUE TITLE
大哥你好 我想问一下问题

### ISSUE THREAD

**Issue by juyaobin** [shalldie/vscode-background#336]
插件是否可以实现全屏背景 (已经实现)
能否每次打开随机一个背景

**Comment by shalldie** [comment]
随机暂时没计划，最近在考虑添加轮播功能

**Comment by shalldie** [comment]
添加了轮播功能： 
[默认模式 background.interval](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE)
[全屏模式 background.fullstreen](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E5%85%A8%E5%B1%8F%E9%85%8D%E7%BD%AE)
