### ISSUE TITLE
Image repeat

### ISSUE THREAD

**Issue by jclopes** [shalldie/vscode-background#34]
I want to add a paper texture to the background but right now it just stays on the bottom left corner. Would be nice to have a repeat / tile option like in CSS "background-repeat: repeat" option.

**Comment by shalldie** [comment]
It will be added into the plugin soon.
不要急，你想要的，岁月都会给你 :D

**Comment by liuliangsir** [comment]
+1

**Comment by shalldie** [comment]
U can set "background.style":{"background-repeat":"repeat"}  in settings.json
