### ISSUE TITLE
"Your code installation appears to be corrupt. Please reinstall"

### ISSUE THREAD

**Issue by Hulkmaster** [shalldie/vscode-background#340]
Got message from the title after installation with a link to https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported

have to uninstall for now

**Comment by shalldie** [comment]
[why the message come](https://github.com/shalldie/vscode-background#warns)

[how to uninstall](https://github.com/shalldie/vscode-background#uninstall)

**Comment by Hulkmaster** [comment]
damn my bad sorry

are there no workarounds around it?

**Comment by shalldie** [comment]
Here's a extension to remove the tag , you can see it [at here](https://github.com/shalldie/vscode-background#qa)

I personally think it doesn't matter. You can click to ignore it :D
