### ISSUE TITLE
在codespace中不能安装

### ISSUE THREAD

**Issue by mitamac** [shalldie/vscode-background#342]
我记得codespace刚出的时候好像都还是可以安装的，那时稍微测试了下codespace
现在突然这个插件就不能安装了
如下图
![image](https://user-images.githubusercontent.com/56892264/203335340-bf4f3029-0d8a-46e6-86b8-c6f90629335e.png)

**Comment by shalldie** [comment]
看了一下，应该跟早期 vscode web 的实现有关，刚出的时候 `碰巧` 可以用。

目前web版支持 [code-server](https://github.com/coder/code-server) ，不能应用于 codespace 或者 vscode.dev ，运行环境有差异。后面有空会尝试下可否迁移。
