### ISSUE TITLE
设置颜色

### ISSUE THREAD

**Issue by transtone** [shalldie/vscode-background#343]
可以设置颜色吗，只在代码编辑页面生效？

vscode 的 editor.background 是个全局属性，不但代码编辑器用它，配置页，插件介绍等全都用的它，
想找个办法单独设置代码编辑区背景。

**Comment by shalldie** [comment]
没这个功能，可以用一个带颜色的背景图来实现类似的效果。
直接改颜色的话有风险，会跟很多主题冲突

**Comment by transtone** [comment]
设置带颜色的图片，只会得到这样的效果：

![image](https://user-images.githubusercontent.com/46688/204074273-a90765e2-5788-4873-b668-5a89a48c8909.png)

![image](https://user-images.githubusercontent.com/46688/204074376-e7503d70-601c-43dd-be11-02423b6278eb.png)

**Comment by transtone** [comment]
找到方案了：https://github.com/be5invis/vscode-custom-css

**Comment by shalldie** [comment]
> 这个插件设置的图片，不能叫做背景，只能叫做前景，叫 `vscode-foreground` 似乎更贴切一些。

有 [前景/背景](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE) 的相关设置，可以决定图片在代码上方或者下方。

我原本的想法是，设置  背景图+repeat ，能实现你想要的效果
自定义样式也行~

**Comment by transtone** [comment]
> > 这个插件设置的图片，不能叫做背景，只能叫做前景，叫 `vscode-foreground` 似乎更贴切一些。
> 
> 有 [前景/背景](https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE) 的相关设置，可以决定图片在代码上方或者下方。
> 
> 我原本的想法是，设置 背景图+repeat ，能实现你想要的效果 自定义样式也行~

真正去设置了才知道，单纯的黑色背景并不能解决问题，还有好些地方需要特别设置：
https://github.com/transtone/vscode-theme-mix/blob/main/Custom%20CSS%20and%20JS%20Loader/theme.css
