### ISSUE TITLE
一次增加61张图片，循环播放，增加失败

### ISSUE THREAD

**Issue by CtrlCandV** [shalldie/vscode-background#344]
只沿用了上次的图片存储，新的图片并没有被使用
61个图片文件的总大小为：193 MB (202,839,990 字节)
配置全文：
`{
    "editor.fontSize": 20,
    "security.workspace.trust.untrustedFiles": "open",
    "background.fullscreen": {

        "image": "",
        "opacity": 0.91,
        "size": "cover",
        "interval": 0
    },
    "background.style": {

        "content": "''",
        "pointer-events": "none",
        "position": "fixed",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "top left",
        "background-repeat": "no-repeat",
        "background-size": "contain",
        "opacity": 0.5
    },
    "background.styles": [
    ],
    "background.interval": 10,
    "background.loop": true,
    "background.useDefault": false,
    "background.customImages": [
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (1).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (1).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (2).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (2).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (3).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (3).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (4).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (4).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (5).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (5).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (6).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (6).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (7).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (7).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (8).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (8).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (9).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (9).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (10).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (10).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (11).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (11).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (12).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (12).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (13).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (13).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (14).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (14).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (15).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (15).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (16).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (16).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (17).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (17).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (18).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (18).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (19).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (19).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (20).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (20).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (21).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (21).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (22).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (22).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (23).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (23).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (24).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (24).png",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (25).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (26).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (27).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (28).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (29).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (30).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (31).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (32).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (33).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (34).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (35).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (36).jpg",
        "file:///C:/Users/windows10/Pictures/桌面背景/1 (37).jpg"
    ]
}`

**Comment by shalldie** [comment]
应该是内存炸了 😂😂
，，，200M的话太大了，简单分析了下，

|type | size| 影响 |
:---: | :--- | :--- |
|硬盘 | `200M` | ... |
| base64 |  约 `260M` | css 文件有近 300M |
| 内存 | 可能在 `780M` ~ `1G+` | 涉及内存中几次运算，大概在这里炸了 =。= |

以这个图片数量就不建议放本地了，老哥可以把图片托管一下用https访问。

**Comment by NoDocCat** [comment]
当时图片转 base64 是个临时想到的 hack, 现在 vscode-file 这个自定义协议稳定下来之后可以尝试着用一下. 参见 #322 .
或者把资源复制到插件自身的目录下记得可以直接用 file 协议加载的, 插件目录在 vscode 的白名单里.

**Comment by shalldie** [comment]
> 当时图片转 base64 是个临时想到的 hack, 现在 vscode-file 这个自定义协议稳定下来之后可以尝试着用一下. 参见 #322 . 或者把资源复制到插件自身的目录下记得可以直接用 file 协议加载的, 插件目录在 vscode 的白名单里.

周末试试，优先考虑 vscode-file，复制的话能解决问题但是成本有点大

**Comment by NoDocCat** [comment]
@shalldie 我来写吧, 正好被封控着没啥事干

**Comment by shalldie** [comment]
@CtrlCandV 
已发布，试试ok不
