### ISSUE TITLE
how to change the background 

### ISSUE THREAD

**Issue by Gaurav-Tewatia** [shalldie/vscode-background#346]
<img width="1105" alt="Screenshot 2022-11-29 at 12 20 26 PM" src="https://user-images.githubusercontent.com/103888220/204458922-5b0567ae-2c63-4951-bc74-7b785e599933.png">
this is how my json file looks like right now i wanna know what i need to add/ delete in order to add a background off my choice in the vs code also would interfering with this json file would cause some problem with my vs code in the future or not?

**Comment by shalldie** [comment]
U can see this to know [what settings.json is](https://code.visualstudio.com/docs/getstarted/settings#_settingsjson)

---
Q: what i need to delete.
A: Nothing

Q: what i need to add.
A: See config [here](https://github.com/shalldie/vscode-background#default-config),  just add your change to settings.json, here are [some examples](https://github.com/shalldie/vscode-background#examples)

Q: would cause some problem with my vs code in the future?
A: The config with prefix `background` would only influence this plugin, it's safe.

Q: how to uninstall
A: see [here](https://github.com/shalldie/vscode-background#uninstall)

**Comment by shalldie** [comment]
anything still unclear?
