### ISSUE TITLE
Read-Only on MacOS Mac Air M1 

### ISSUE THREAD

**Issue by DETLIXX** [shalldie/vscode-background#349]
Hello, i am trying to install this extension but it show this error

<img width="390" alt="Screenshot_2022-12-01_at_13 36 32" src="https://user-images.githubusercontent.com/43766321/205057245-707c0e97-71fa-47c4-a0df-db52984e2534.png">
<img width="403" alt="Screenshot_2022-12-01_at_13 37 05" src="https://user-images.githubusercontent.com/43766321/205057297-eb1ceb9c-b150-42ea-983b-1dfcfc223315.png">

**Comment by shalldie** [comment]
Is the problem solved ?

**Comment by shalldie** [comment]
@bhumit070 
Sounds seem that your account doesn't have the root access.

Try this command in your terminal:
```bash
sudo chmod a+rw '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css'
```
then reload vscode, can it works?

**Comment by bhumit070** [comment]
> 

Okay, I will try but to solve this issue i copied this command in terminal with sudo prefix and ran manually and worked.

But I will also try this it this will work or not

**Comment by lainisourgod** [comment]
@shalldie doing `sudo chmod a+rw '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css'` helped for me. thanks!

**Comment by shalldie** [comment]
For all friends who come here, from `v2.0.0`, the command should be:

```bash
sudo chmod a+rw '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js'
```

Refer to [(Mac) read-only file system](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.md#mac-read-only-file-system)

**Comment by DIEGOHORVATTI** [comment]
iso should be on the home screen of the extension or be a command given after installing the extension if the system is mac

**Comment by shalldie** [comment]
> iso should be on the home screen of the extension or be a command given after installing the extension if the system is mac

@DIEGOHORVATTI 
Most of the time, a 「Try as Sudo」button is provided and the command is not needed.
