### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by krisystef** [shalldie/vscode-background#35]
I`ve created my own picks on my PC and set it up in settings.json but still It wont show them. Any ideas ?

**Comment by shalldie** [comment]
Sorry for my english.

I think, you need to get the administrator permission.
You should get the authority to edit files of vscode.

**Comment by raviteja83** [comment]
how to do that @shalldie ?

**Comment by shalldie** [comment]
@raviteja83 
For example,in windows.
Right click on the vscode's icon,then check the 【Run with administrator permission】(U know which item i mean,right? I have never used the computer with english language.)。
Administrator permission should be gotten while the first time to change background.

Or , login on the computer with administrator account。
