### ISSUE TITLE
设置页搜索框显示背景图问题

### ISSUE THREAD

**Issue by quaintclever** [shalldie/vscode-background#350]
描述：
安装完插件，默认配置，未修改setting.json，发现设置页搜索框有显示问题，如下图。

环境：
win10
vscode 1.73.1

![image](https://user-images.githubusercontent.com/45060092/205113692-6402098b-ef8d-4597-8f5c-8388d9b151ce.png)

**Comment by shalldie** [comment]
已合入，会尽快发版 https://github.com/shalldie/vscode-background/pull/345
