### ISSUE TITLE
High-frequency problems navigation. 高频问题导航

### ISSUE THREAD

**Issue by shalldie** [shalldie/vscode-background#352]
> High frequency problem navigation, real-time update.
> 高频率问题导航，实时更新。

## 1. How to uninstall. 如何卸载？

Read [doc here](https://github.com/shalldie/vscode-background#uninstall)
看 [文档](https://github.com/shalldie/vscode-background#uninstall)

相关 issues：
Related issues:
[Background Wont GO AWAY](https://github.com/shalldie/vscode-background/issues/177)

## 2. Not work? 不生效？

99% may be due to authority problems.
大概率权限问题。

### Mac: 

Move `vscode` from Directory `Download` to `Application`
把 `vscode` 从 `下载` 移动到 `应用` 中

#### Related issues. 相关 issues：
[关于macOS无法正常显示图片的一个可能原因 - case in macOS](https://github.com/shalldie/vscode-background/issues/252)
[Code won't update on macOS](https://github.com/microsoft/vscode/issues/7426)
[Read-Only on MacOS Mac Air M1 #349](https://github.com/shalldie/vscode-background/issues/349)

### Ubuntu:
[然而ubuntu16.04依然用不了 #6](https://github.com/shalldie/vscode-background/issues/6)
[Ubuntu 16.04 安装完不起作用 #231](https://github.com/shalldie/vscode-background/issues/231)

## 3. Examples. 示例

https://github.com/shalldie/vscode-background#examples

**Comment by Wei179553** [comment]
可以把轮播图修改为随机播放吗？

**Comment by shalldie** [comment]
Deprecated, go and see [common-issues](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.md)
