### ISSUE TITLE
插件失效，在vsc开发工具中显示refused to load the image

### ISSUE THREAD

**Issue by median-dxz** [shalldie/vscode-background#353]
# vsc版本信息

版本: 1.74.0-insider (user setup)
提交: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
日期: 2022-12-05T10:17:57.998Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
沙盒化: Yes

# 问题情况

背景不显示。打开vsc开发者工具，有以下提示：

![image](https://user-images.githubusercontent.com/33348142/205688426-5e29815b-5431-4d66-9a57-8eac2680bb08.png)

**Comment by shalldie** [comment]
你的图片是本地的吗？

图片会有个转换：
```ts
file:///Users/foo/bar.png => vscode-file://vscode-app/Users/foo/bar.png
```

获取图片地址的简单方式，可以把图片拖到浏览器然后从地址栏复制。
我感觉好像本地图片地址少写了一个 `/`，这地方再确认下？

**Comment by median-dxz** [comment]
> 

感谢，问题解决了。

确实如你所说，在配置文件中，file协议后面应该是`///`，而我的配置文件里写的是`//`。不过我还是很奇怪为什么是这两天突然出现这个问题😥，我最近应该没动过我的配置文件。

**Comment by median-dxz** [comment]
我想起了我好像这个插件也是最近进行了一次更新，或许和vsc的更新并没什么关系😂

**Comment by shalldie** [comment]
hhh 昨天确实更新了一版，涉及这部分的一些优化
大概以前虽然有bug但是也能run吧 😅

**Comment by NoDocCat** [comment]
原来在读取 buffer 之前有一行 `new URL(url)`, 一些不规范的路径会被自动修正. 
在改用 `vscode-file` 协议的时候把这个忘了, 我的锅.

![image](https://user-images.githubusercontent.com/20502666/205826134-17eb0064-df30-4395-8db0-6e04a62fb8d7.png)
