### ISSUE TITLE
希望可以增加fullscreen模式下自定义样式功能

### ISSUE THREAD

**Issue by VMatrices** [shalldie/vscode-background#354]
类似 `"background.style"`：

```json
  "background.fullscreen": {
      "image": "......",
      "interval": 0,
      "style": {
          "opacity": 0.91,
          "background-size": "auto",
          "background-position": "right bottom",
          "background-repeat": "no-repeat",
      }
  },
```

**Comment by shalldie** [comment]
最初设计时候考虑过，也参考了同类插件的方式，没有选择添加该api。

原因是这样的，`全屏` 的场景非常有限，用户也用不到太多配置，过于灵活可能把vscode玩崩。
能描述下你的场景吗？

**Comment by VMatrices** [comment]
> 最初设计时候考虑过，也参考了同类插件的方式，没有选择添加该api。
> 
> 原因是这样的，`全屏` 的场景非常有限，用户也用不到太多配置，过于灵活可能把vscode玩崩。 能描述下你的场景吗？

主要想实现类似Jetbrain系列的这种全窗口背景效果：

![image](https://user-images.githubusercontent.com/24680533/205971889-92a7a833-45b2-472a-a2e5-e8967a061e8c.png)

![image](https://user-images.githubusercontent.com/24680533/205971765-7c6952ab-8d4f-4bbe-b556-571de8de79b9.png)

**Comment by shalldie** [comment]
了解，可以添加该功能，时间大概1～2周内吧～

**Comment by shalldie** [comment]
感觉能自定义太危险，，，加一个 `position` 是不是就够用了？

**Comment by VMatrices** [comment]
3Q~

可以的，补充个position、repeat基本能够覆盖大部分场景了

**Comment by shalldie** [comment]
目前默认 `no-repeat`，禁止修改

**Comment by shalldie** [comment]
已发布 v1.2.8
