### ISSUE TITLE
图片自动播放时,每当切换标签页就又会从第一张重新开始

### ISSUE THREAD

**Issue by aaazhouaa** [shalldie/vscode-background#358]
![动画](https://user-images.githubusercontent.com/92150833/206957473-29cbb33b-05a0-4990-a57c-06d3369163f7.gif)

**Comment by shalldie** [comment]
原因是这样的：
在 vscode 看来，每次切换tab都是 `先关闭、再创建`，是全新的页面，没有复用dom。

暂时没办法解决这个问题

**Comment by aaazhouaa** [comment]
哦哦 懂了懂了 感谢回复😊

**Comment by aaazhouaa** [comment]
> 

哦哦 懂了懂了 感谢回复
