### ISSUE TITLE
Add possibility to blur the background image

### ISSUE THREAD

**Issue by edmondmentori** [shalldie/vscode-background#360]
While it is nice to have a background while coding, the details of the image can sometimes be distracting.
I think it would be nice to be able to blur the background easily, just like adjusting opacity.

**Comment by shalldie** [comment]
`opacity` is supportted, you can find it in doc's config or examples.

I see you open another issue

**Comment by duraki** [comment]
@shalldie I'd also like this implemented. Sometimes the backgrounds of our choice are too bright. A blur option would be nice IMO.
