### ISSUE TITLE
Choose if text is supposed to become transparent aswell

### ISSUE THREAD

**Issue by edmondmentori** [shalldie/vscode-background#361]
When you decrease opacity, the text also becomes transparent, making it harder to read. It should be possible to select if you want the text to become transparent as well or not.

**Comment by shalldie** [comment]
Try `"background.useFront": false` to `Set the image to back of your code`, then the images may not influence your code.

**Comment by edmondmentori** [comment]
<img width="722" alt="Skärmavbild 2022-12-18 kl  17 42 23" src="https://user-images.githubusercontent.com/70721551/208309562-5fd17983-c4d1-4792-ab81-e240aeff6319.png">

It did not work for me, the text is still transparent

**Comment by shalldie** [comment]
Oh you mean `fullscreen` mode, it may overwrite other configurations.
`background.useFront` is for the default mode(`code area`).

There's no similar config for `fullscreen mode`, limited by the implementation. 😢
