### ISSUE TITLE
在上下分屏界面透明度失效

### ISSUE THREAD

**Issue by Conless** [shalldie/vscode-background#362]
![image](https://user-images.githubusercontent.com/37496034/208245288-3cfea185-d07c-415d-b7ef-ab1ec2cb707c.png)
![image](https://user-images.githubusercontent.com/37496034/208245306-9c980b8f-1afb-4875-a75f-a0a15ed9d8ef.png)
图一是正常状态，图二是上下分屏后的状态

**Comment by shalldie** [comment]
yang了，老眼昏花没看出区别，详细描述一下？

**Comment by xcbyao** [comment]
路过，@Conless 的意思是右侧上下分屏之后，全屏背景图的透明度失效；第一张是设置了透明度，第二张透明度失效变亮了。

![image](https://user-images.githubusercontent.com/40726291/214797638-131330d0-d261-45c0-a1b9-4efe040fd0b6.png)

**Comment by shalldie** [comment]
一直没能复现这个问题，因为【全屏】跟【代码区域】 是互斥的，应该只有全屏生效才对。
猜测是鼠标点击某面板，focus后该面板会高亮，造成透明度
