### ISSUE TITLE
全屏 与 代码区域 图片 能够同时显示

### ISSUE THREAD

**Issue by I-love-study** [shalldie/vscode-background#363]
当同时设置了 `background.fullscreen` `background.style` `background.customImages` 时，插件将只会显示全屏内容

适用情况：代码区域放Q版人物，同时全屏放置照片

**Comment by shalldie** [comment]
前段时间yang了，回复不及时。

不能同时显示，就是这么设计的。
两者一起展示太乱了，会看不清楚。

**Comment by I-love-study** [comment]
懂了，感谢
