### ISSUE TITLE
how can we add multile images ?

### ISSUE THREAD

**Issue by Sid0006** [shalldie/vscode-background#365]
I already added a single images as vs code background but I Don't know how to add multiple images as background, 
I tried    "background.customImages": [
        "https://  image01.png",
        "https://  image02.png"
    ],
but only image01 is visible as background img

**Comment by shalldie** [comment]
The `image02.png` may be displayed in 2rd panel.

try
mac: `command + 2`
windows: `ctrl + 2`
to see it.

**Comment by Sid0006** [comment]
> The `image02.png` may be displayed in 2rd panel.
> 
> try mac: `command + 2` windows: `ctrl + 2` to see it.

Yes, it worked thank you :)
