### ISSUE TITLE
problem with background and install system version of visual code

### ISSUE THREAD

**Issue by Jerem59** [shalldie/vscode-background#366]
Hi,
to use this extension, i must update write on the file C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench _workbench.desktop.main.css
to write for users. If i don't make it, impossible to use the exetension.
But when i change it, code alert to corrupt install .

**Comment by NoDocCat** [comment]
Because vscode does not provide an API to modify the UI, So we can only to do.
About corrupt, please reference: https://github.com/shalldie/vscode-background#warns
