### ISSUE TITLE
Win10，customImages中，文件扩展名是大写时，无法加载文件

### ISSUE THREAD

**Issue by asuper0** [shalldie/vscode-background#367]
Win10系统，一开始以为路径写的不合法，来回折腾了好多次，突然发现是扩展名大小写的问题，用大写的无法加载，小写就没问题了，文件路径中其他部分没问题。

本来想自己改代码，发现TS完全看不懂在哪里判断的扩展名。

**Comment by NoDocCat** [comment]
这是 vscode 沙盒的限制, 参考: https://github.com/microsoft/vscode/blob/96bf637c101b8832e44a97a27a26305d8c2cf22e/src/vs/platform/protocol/electron-main/protocolMainService.ts#L26-L27

除非有类似于 GAS 的特殊情况, 文件扩展名请始终保持小写.

**Comment by asuper0** [comment]
好家伙，直接写死了……那是否可以在readme中说明一下
或者在读取customImages字段时把扩展名部分转为小写应该也可行吧

**Comment by shalldie** [comment]
之前倒是没注意过，，，会在文档中补充扩展名小写的问题。

读取时候转应该不行也不合适，最好保持文件名小写。
