### ISSUE TITLE
If set multiple images, multiple tabs will keep the image #2 across other tabs

### ISSUE THREAD

**Issue by tbogard** [shalldie/vscode-background#368]
Not sure what happened, but it was working fine until some update on vscode forced the images of other tabs to go away and keep the second image on the array to be on all other tabs.

here my configuration:

```JSON
 "background.enabled": true,
  "background.interval": 0,
  "background.loop": true,
  "background.useDefault": false,
  "background.useFront": false,
  "background.style": {
    "content": "''",
    "pointer-events": "none",
    "position": "absolute",
    "z-index": "99999",
    "width": "100%",
    "height": "100%",
    "margin": "0%",
    "background-size": "cover",
    "background-position": "center center",
    "background-repeat": "no-repeat",
    "opacity": 0.1
  },
  "background.customImages": [
    "https://media3.giphy.com/media/NKEt9elQ5cR68/giphy.gif",
    "https://wallpaperaccess.com/full/8351160.gif",
    "https://wallpaperaccess.com/full/8351227.gif",
    "https://cutewallpaper.org/cdn-cgi/mirage/879d3f56044898301ccabab4a8a90586cd5663eca603a14193df05b49a03034b/1280/28/cyberpunk-gif-wallpaper/cyberpunk-gif-icegif.gif"
  ],
```
result:
![image](https://user-images.githubusercontent.com/1978642/213088095-8aae7f80-d57a-4212-8ae8-f4d66210ff75.png)

**Comment by NoDocCat** [comment]
In dom tree, tabs not necessarily sibling elements. In fact a tab may be nested within a tab. 
The index that decides which background to use depends only on its position in this level

like this:
![image](https://user-images.githubusercontent.com/20502666/213096077-741aed02-7fec-4218-9b3b-16d9882d91a0.png)

**Comment by shalldie** [comment]
Simplify the answer upstairs: `Only horizontal layout is considered` ~
