### ISSUE TITLE
Add option to enable background only on some themes

### ISSUE THREAD

**Issue by lainisourgod** [shalldie/vscode-background#369]
Hi! Thanks for extension, everything works as expected!

I'd like to have a feature to enable background only with some themes. E.g. I like my transparent background with dark theme (1), but don't like with light theme (2 disabled → 3 enabled).

![CleanShot 2023-01-30 at 14 44 26@2x](https://user-images.githubusercontent.com/24773652/215457016-16e3007b-0038-417d-86a5-5524a6875da7.png)

![CleanShot 2023-01-30 at 14 44 02@2x](https://user-images.githubusercontent.com/24773652/215457104-3c26c93f-4f79-4d37-9225-2e1eaddf88ee.png)

![CleanShot 2023-01-30 at 14 44 14@2x](https://user-images.githubusercontent.com/24773652/215457031-d9e517df-9dc1-49e9-b065-d27f44c83bbf.png)

Possible configuration is:
```jsonc
"background.enabledWithTheme": {
  "[Ayu Mirage]": true,
  "[Ayu Light]": false,
}
```

or

```jsonc
"background.enabledWithColorTheme": {
  "dark": true,
  "light": false,
}
```

**Comment by shalldie** [comment]
Thanks for your comments, here are some of my thoughts, translated by google:

1. Switching themes isn't a regular occurrence, like I might do every few years.

2. Visual effects are jointly determined by pictures, styles, and themes, and it may not be appropriate to display them for themes.

3. The startup/shutdown of the plug-in actually has a lot of costs, and it may be necessary to restart vscode multiple times to disable it according to the theme.

**Comment by lainisourgod** [comment]
1. I switch theme on daily basis between light and dark, as my OS theme switches.
3. I understand this and as it requires restarting VSCode, auto-reneabling it isn't an option.
