### ISSUE TITLE
卸载之后还有图片

### ISSUE THREAD

**Issue by haixinn** [shalldie/vscode-background#37]
如何恢复默认

**Comment by shalldie** [comment]
卸载的时候，先设置 "background.enabled":false ，然后再卸载插件。
或者重装 vscode ，，，

**Comment by haixinn** [comment]
ok

**Comment by wangxufire** [comment]
你改了什么东西，默认图片存在哪了？为什么一直显示

**Comment by shalldie** [comment]
@wangxufire 
在readme中已经说明，修改了vscode的系统文件(一个css文件)，所以卸载请按照如下方式。

> Q:How to uninstall the extension?
> Q:怎么卸载这个插件？
> 
> A:Set the config  {"background.enabled": false}  in settings.json,then uninstall the plugin.
> A:在 settings.json 中设置 {"background.enabled": false} ，然后再删除插件。如果直接删除插件会有遗留，就需要重装vscode了。

**Comment by wangxufire** [comment]
看了代码手动改css文件改回去了，这个插件质量不太高啊。文件管理器和控制台的背景没有覆盖到，透明度不知道怎么设置，加了css 代码字体的透明度也跟着变了

**Comment by cooper1x** [comment]
还是要覆盖安装vscode

**Comment by shalldie** [comment]
@cooper1x 现在的插件是会自动清理的，可以看下 readme

**Comment by cooper1x** [comment]
@shalldie 试过了不行的，我加了`"background.enabled": false`配置，然后会出现默认的背景，卸载插件也还有残留。

**Comment by shalldie** [comment]
@cooper1x 快速测了几种卸载方式，没能复现。
再开一个 issue 来详细描述问题吧

**Comment by cooper1x** [comment]
@shalldie 不好意思，看错了，我之前改的是`"background.useDefault": false,`
