### ISSUE TITLE
add background videos

### ISSUE THREAD

**Issue by 404jv** [shalldie/vscode-background#370]
Hello everyone! Is it possible to include videos in the background too? 

I am using a plugin called [Glassit-VSC](https://marketplace.visualstudio.com/items?itemName=s-nlf-fh.glassit) to make my vscode transparent then I put some videos behind it to see how it looks and it's awesome ([see it](https://ik.imagekit.io/dwei78ukbe/video_UkaHjlxZl.mp4?ik-sdk-version=javascript-1.4.3&updatedAt=1675393074826)).

But, when I tried to create a GIF with that mp4 to use as a background image, of course, it lost a lot of quality ([see it](https://ik.imagekit.io/dwei78ukbe/2023-02-02_23-58-39_4QzAt1tPf.mp4?ik-sdk-version=javascript-1.4.3&updatedAt=1675393210637)). Is there a way to add the video directly into the editor?

**Comment by NoDocCat** [comment]
CSS only can add some images to HTML (use background).
If add a video, we need to operate DOM, This is complex and dangerous for a vscode plugin. 

---

If you really need, Recommended use [monkey-patch](https://github.com/iocave/monkey-patch)

**Comment by 404jv** [comment]
@NoDocCat Thank you, I'll take a look.
