### ISSUE TITLE
全屏模式下的背景图片无法居中

### ISSUE THREAD

**Issue by Cyorageeee** [shalldie/vscode-background#372]
在Ubuntu 20.04下使用code-server来安装插件时，全屏模式下的背景无法居中，在多次修改配置之后无果。情况如下图（图中配置为现有配置）:  
![pic](https://i.328888.xyz/2023/02/07/rKLXZ.png)

**Comment by NoDocCat** [comment]
问题未能复现, 且已排除窗口过宽和过高的问题.
尝试仅使用 `background.fullscreen`, 不要两个选项同时使用.
最后: 天梨 さいこう

### 3024 * 1964

<img width="1512" alt="Snipaste_2023-02-07_22-46-48" src="https://user-images.githubusercontent.com/20502666/217279581-10fa5375-d93e-4d4e-8605-2a67ef84feee.png">

### 3440 * 1440

![Snipaste_2023-02-07_22-47-51](https://user-images.githubusercontent.com/20502666/217279893-3a5b89ca-33b6-463b-b74f-d406015bf2de.png)

### 2160 * 3840

<img width="1080" alt="Snipaste_2023-02-07_22-48-17" src="https://user-images.githubusercontent.com/20502666/217279798-8d35dbd5-7d68-4009-80f1-475eb10ed500.png">

**Comment by shalldie** [comment]
@Cyorageeee @NoDocCat 

#### 环境
我在 docker 版本的 code-server 中复现了

使用的镜像：`codercom/code-server:4.4.0`
cat /etc/issue：`Ubuntu 20.04 LTS \n \l`

#### 原因
code-server `魔改` 了一些样式，给 body 添加 `position:fixed` 导致。不知道为啥要这么做，，，
因为并不是标准版vscode，暂时没啥好办法。

#### 临时方案
临时方案可以通过更改size来微调，比如设置 size 为 `100vw 200vh`

#### 后续
后面会在不影响标准版的情况下，尝试给 code-server 做一些hacky的事情。

**Comment by Cyorageeee** [comment]
@shalldie 我会尝试一下更改size。   
我使用的环境大致相同。系统同样是20.04 LTS,但是是直接在系统中以安装文件方式运行code-server 4.9.1版本。  
静候佳音。  
@NoDocCat 你也喜欢天梨，那我们就是异父异母的好兄弟了（x

**Comment by shalldie** [comment]
@Cyorageeee 
发布了 v1.2.9，适配了 code-server 的场景。

code-server的应用市场是自己维护的（不同于vscode插件市场），版本会落后，且更新时间不确定。
可以从 [vscode Marketplace](https://marketplace.visualstudio.com/items?itemName=shalldie.background) 的 [Version History] 下载最新版本插件，上传到 code-server，选择 [从VSIX安装]。

可以参考[这篇文章](https://nosaid.com/article/coding-in-browser#%E4%B8%8B%E8%BD%BD%2F%E4%B8%8A%E4%BC%A0)

**Comment by Cyorageeee** [comment]
@shalldie 
收到，我会马上开始尝试！

**Comment by shalldie** [comment]
在 code-server:4.9.1 下测试ok，有2个地方要注意：
1. 可能需要权限，尝试 [Retry with Admin] 或者手动 `sudo chmod a+w xxx.css`
2. 缓存。改配置之后可能要强刷才能生效。

**Comment by Cyorageeee** [comment]
![](https://img.cyoragex.top/images/2023/02/17/-2023-02-17-140400.png)  
现在问题已经解决，感谢。
