### ISSUE TITLE
VSCode启动时图片透明度丢失

### ISSUE THREAD

**Issue by MitsuhaYuki** [shalldie/vscode-background#374]
## 问题描述

启动VSCode时，背景图片会先原样显示出来，界面加载完成后才会正常出现透明度

这个问题在background v1.2.8的时候设置`background.fullscreen.position: "bottom"`的时候不会出现，在v1.2.9的时候无论怎样设置position都会出现该问题

## 完整插件配置

```
"background.useDefault": false,
"background.fullscreen": {
    "image": "file:///E:/图片库/Background/69602151_p0.jpg",
    "opacity": 0.9,
    "size": "cover",
    "position": "center",
    "interval": 0
}
```

## 相关环境信息

```
Version: 1.75.1 (user setup)
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes
```

## 图片

![issue01](https://user-images.githubusercontent.com/46064690/218906761-7087dfb9-b02d-4cb4-a66f-b932a8e284eb.jpg)

![issue02](https://user-images.githubusercontent.com/46064690/218906765-96645470-bcbe-4c32-ac56-39d1767483f7.jpg)

**Comment by shalldie** [comment]
> `启动VSCode时，背景图片会先原样显示出来，界面加载完成后才会正常出现透明度`

一直都有这个问题，因为vscode内的各部分也是一层层加载出来，所以背景初始时候比较突兀。
有一些想法（animation-delay），会找时间尝试下。

**Comment by MuuuShin** [comment]
#328

**Comment by shalldie** [comment]
这几周实在太忙了，天天加班。
现在缓过来了看这个问题 =。=

**Comment by shalldie** [comment]
久等，发布了 `1.2.11` 修复了该问题 🎉🎉
