### ISSUE TITLE
Always first image of an array of backgrounds when a new file is opened

### ISSUE THREAD

**Issue by FBRAA** [shalldie/vscode-background#375]
When background.loop is true, background images should change over an interval of time. But when opening a new file the first image is always shown, as if it is a new window of vscode.

I'd like to have consistent flow of images across all opened files inside one vscode window - as best
or start loop from a random image of an array - if the best isn't possible

**Comment by shalldie** [comment]
`loop` has some ambiguity, I plan to remove it later.
It works only when the number of tabs is more than the number of your pictures. Like this:

![image](https://user-images.githubusercontent.com/9987486/219876720-c7acbf4f-072a-4f5d-b9ec-bea9fbc678a2.png)

**Comment by shalldie** [comment]
> I'd like to have consistent flow of images across all opened files inside one vscode window - as best
> or start loop from a random image of an array - if the best isn't possible

The design is to display pictures according to the order of tabs.
Or set only one image, so that all tabs will display this one.

Random pictures cannot be supported on the current architecture... 😿

**Comment by shalldie** [comment]
@FBRAA 

https://github.com/shalldie/vscode-background#default-config

There's a carousel config: `background.interval`, the image in a tab will be displayed in turn.
Maybe you like it 😸

**Comment by FBRAA** [comment]
> @FBRAA
> 
> https://github.com/shalldie/vscode-background#default-config
> 
> There's a carousel config: `background.interval`, the image in a tab will be displayed in turn. Maybe you like it 😸

I currently use interval. Nonetheless, each time I open new tab, it starts anew х_х. 
I want the state of the image to be hold somewhere, so when I open new tab it could take current image in my array and current timer to continue with them. It is like when background.fullscreen option, but inside tabs and without losing the opacity of the window
