### ISSUE TITLE
使用随机图片api只显示固定图片

### ISSUE THREAD

**Issue by qsgy-edge** [shalldie/vscode-background#376]
如题，api第一次获取哪张图片，轮换时就固定是哪张了，是因为在第一次访问图片链接会本地缓存吗，能否去掉缓存？

**Comment by shalldie** [comment]
缓存是你的服务端响应头决定的，比如 cache-control 之类。
可以试试在 response header 里面添加： cache-control: no-store

**Comment by qsgy-edge** [comment]
我是用的网上找到的api，看了一下图片设置是在
![image](https://user-images.githubusercontent.com/60124215/220306542-95863327-59e4-4e60-82c3-638990a26490.png)
那图片获取应该是vscode自动实现的？我还因为是插件获取后转base64

**Comment by shalldie** [comment]
曾经是转base64，但太大了，后来本地文件换了 vscode-file 协议。
比如这个 200M 的case： https://github.com/shalldie/vscode-background/issues/344

---

> 我是用的网上找到的api

回到原本问题，这个api看样子没有考虑过前端缓存，不适合当前需求。
有条件的话可以加个代理来支持。
