### ISSUE TITLE
"background.useFront": false bug

### ISSUE THREAD

**Issue by lsaiot** [shalldie/vscode-background#377]
"background.useFront": false 将图片做为背景图时，除了文本编辑区域外都不能使用鼠标点击，当用作前景图时正常。

**Comment by NoDocCat** [comment]
能否提供一下你配置文件? 包含本插件相关配置的部分即可.

**Comment by myluckytimes** [comment]
> 能否提供一下你配置文件? 包含本插件相关配置的部分即可.

  "background.enabled":true,
  "background.loop": false,       //轮播图
  "background.interval": 0,       //单位 秒，轮播时候图片切换间隔，默认 0 表示不开启。
  "background.useFront": false,   //是否使用前景图，这样会使图片放在代码的顶部
  "background.useDefault": false, //默认图片
  "background.customImages": [    //自定义背景图
      //"file:///E://Users//图片//壁纸//草狗表情包-护眼壁纸.png"
      "file:///E://Users//图片//壁纸//拒霜思.png"
  ],
  "background.style": {       //自定义样式
      "content": "''",
      "pointer-events": "none",
      "position": "fixed", //图片位置
      "width": "100%",
      "top": "0px",
      "left": "0px",
      "background.repeat": "no-repeat",
      "background-size": "cover", //图片大小
      "opacity": 0.3 //透明度
  },

**Comment by NoDocCat** [comment]
建议直接使用新的全屏图片配置: https://github.com/shalldie/vscode-background#fullscreen-config

**Comment by myluckytimes** [comment]
使用这个配置的时候，右上角从最小化窗口向右和背景色不一致
![image](https://user-images.githubusercontent.com/50024887/220532533-bc6b53c9-bcc8-4c97-bd24-680d5cb27a59.png)

**Comment by NoDocCat** [comment]
这个表现倒是一个 Bug, Windows 这么神奇的吗?

**Comment by myluckytimes** [comment]
可能是Windows版本问题，目前是win11 22H2 22621.1343，之前没有出现的，这个情况具体是哪个版本开始的也记不太清楚了🤣

**Comment by shalldie** [comment]
应该是win下的系统按钮，xp、win7、win10 的表现还不一致，插件感觉干涉不了。（以我浅薄的winform经验）

> 建议直接使用新的全屏图片配置: https://github.com/shalldie/vscode-background#fullscreen-config

@myluckytimes 
除了右上角按钮，
在使用全屏的配置后，`"background.useFront"` 是不生效的，这时候还有问题吗？

**Comment by myluckytimes** [comment]
> @myluckytimes 除了右上角按钮， 在使用全屏的配置后，`"background.useFront"` 是不生效的，这时候还有问题吗？
全屏配置的时候可以点击所有位置，只是右上角哪里有点别扭。不使用全屏配置， `"background.useFront": true` 这样把图片放在代码上面都正常，但是只要改为 `false` 就出问题。

**Comment by myluckytimes** [comment]
> 嗯，全屏提供了专门的配置，直接用吧。 大概自定义样式的 `position:fixed` 对鼠标的操作造成了影响，避免使用吧 =。=
> 
> 现在插件有两种模式：代码区域、全屏。 不再建议在代码区域通过自定义样式实现全屏的效果，自定义太灵活了不可控。

嗯嗯，我改改这个试试
