### ISSUE TITLE
windows  vscode 1.76.0版本 设置网络图片背景不生效，设置本地图片可以生效，请问如何解决？

### ISSUE THREAD

**Issue by lvjisong** [shalldie/vscode-background#379]
windows  vscode 1.76.0版本 设置网络图片背景不生效，设置本地图片可以生效，请问如何解决？

**Comment by shalldie** [comment]
麻烦确认下 checklist：

1. 图片地址协议是 https的
2. 该图片是可公开访问的。
    - 很多网站会做校验，不允许其它网站访问它的资源。
    - 比如你可以试试这个开放的地址：https://i.loli.net/2021/03/26/seH6v1pJIdODynX.png

**Comment by lvjisong** [comment]
知道原因了，图片是http协议的，已经更换图片解决，感谢！！！
