### ISSUE TITLE
win10下vscode1.9.1版本貌似不能用了

### ISSUE THREAD

**Issue by saybye720** [shalldie/vscode-background#38]
配置没毛病，不显示图片

**Comment by shalldie** [comment]
hi ，我刚刚试了一下 mac下的1.9.1 ，按理说 win下也能用。
请试试开启管理员权限，如果还不行请留言。
手边暂时没有win的本子 😂😂

**Comment by KkEeVvIiNnn** [comment]
您好，我也是这个情况，win10+最新版用不了

**Comment by shalldie** [comment]
@KkEeVvIiNnn 
没有明白 ，，太亮的，什么意思呢  0.0

**Comment by saybye720** [comment]
Code 安装似乎损坏。请重新安装。
我管理员打开后显示这个了，还会，过几天在折腾下吧。估计还是权限问题

**Comment by shalldie** [comment]
@saybye720 
提示损坏，请选择最后一项【不再提示】
因为官方不允许修改这些东西，所以我是通过修改vscode文件来实现，有这个提示。

**Comment by saybye720** [comment]
哦，原来如此，谢咯
