### ISSUE TITLE
Background not showing properly after updating

### ISSUE THREAD

**Issue by architelos** [shalldie/vscode-background#383]
Hello! Recently, I've updated VSC from 1.76.2 to 1.77.1.
After updating, the background no longer is a "background", so to say (screenshot)

![{15689EAD-9F59-460B-BF71-19E61F44B5BA} png](https://user-images.githubusercontent.com/108888162/230732936-24b0775b-0c3f-4436-a997-392b17669eb5.jpg)

Here's my settings.json:
```json
{
    "workbench.colorCustomizations": {},
    "security.workspace.trust.untrustedFiles": "open",
    "editor.accessibilitySupport": "off",
    "editor.experimentalWhitespaceRendering": "off",
    "files.hotExit": "onExitAndWindowClose",
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "files.trimFinalNewlines": true,
    "workbench.commandPalette.preserveInput": true,
    "javascript.format.semicolons": "insert",
    "security.workspace.trust.banner": "never",
    "security.workspace.trust.startupPrompt": "never",
    "workbench.colorTheme": "Ayu Dark Bordered",
    "[python]": {
        "editor.formatOnType": true
    },
    "background.customImages": [
        "https://i.pinimg.com/originals/0c/1f/74/0c1f748f5702c12423c3720d4cce4cc4.png"
    ]
}
```
What could be the issue?

**Comment by shalldie** [comment]
1. If you want to enable the customimages, you should add: `"background.useDefault": false`

2. If you want the image below the code， add: `"background.useFront": false`

3. Adjust the opacity:

```json
"background.style": {
    "opacity": 0.3
}
```

4. Or a fullscreen background: https://github.com/shalldie/vscode-background#fullscreen-config

**Comment by architelos** [comment]
I already tried "background.useDefault": false, that was what caused the background to show like in the ss above. Will try the other steps though, thanks

**Comment by architelos** [comment]
Ahh thanks, it worked, really appreciate it
