### ISSUE TITLE
How can i fix it?

### ISSUE THREAD

**Issue by ICE0208** [shalldie/vscode-background#384]
The image I set appears on the Install button.. but not on the disable, uninstall buttons, etc, only on the Install button.

[The Image I set]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/46257328/230841167-92778f83-a551-434f-a654-5e683172ca47.png">

[BUG]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/46257328/230841028-ad1a24a9-7626-469c-b60c-2bd3540ea969.png">

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/230844599-04972f9d-bd0b-46ea-9f28-db5a63a0a1de.png)

![image](https://user-images.githubusercontent.com/9987486/230844691-f6404f9e-8f5a-47b1-902a-c85b967fa91e.png)

Strange,  I test it ok on my mac, can you show your `background` config ,and the vscode's version.

**Comment by shalldie** [comment]
Can't reproduce. I'm upgrading the os to maintain the same environment as you...

What's the version of `shalldie.backgorund` extension?
By the way,  please paste your images here, i want to keep all env same as you.

**Comment by ICE0208** [comment]
It's probably a newer version. v1.2.9
in fact it's been a while since I've seen this bug. I created an issue because I was wondering if anyone else had experienced the same thing.
here are my images

![guraguragura](https://user-images.githubusercontent.com/46257328/230857780-65cf4e2c-396d-43a4-a6c8-a3aa1df578bb.png)
![chisato-kawaii](https://user-images.githubusercontent.com/46257328/230857828-4f73307d-30c1-4fad-9ee2-d7c93c1c5fad.png)
![dlf pt-asuna-yuuki-png-3369377](https://user-images.githubusercontent.com/46257328/230857876-c165556a-e4f7-436a-b969-9c84ff0fbb92.png)
