### ISSUE TITLE
如何让代码不被图片透明度覆盖？

### ISSUE THREAD

**Issue by rm919** [shalldie/vscode-background#387]
想请问有没有什么方法让代码不会随着图片透明度调高而影响？因为调越高那个代码就越看不到
 "background.enabled": true,
        "background.useDefault": false,
        "background.customImages": [
            "file:///C:/Users/rmyeow/Desktop/naruto.jpg"
        ],
        "background.style": {
            "content": "''",
            "pointer-events": "none",
            "position": "absolute",
            "top": "0",
            "right": "0",
            "background-size": "cover",
            "opacity": 0.5,
            "z-index": "99999",
            "width": "1920px",
            "height": "1200px",
            "background-repeat": "no-repeat",

**Comment by NoDocCat** [comment]
https://github.com/shalldie/vscode-background#fullscreen-config

**Comment by rm919** [comment]
{
    "[python]": {
        "editor.formatOnType": true
    },
    "workbench.colorTheme": "2077",
    "background.enabled": true,
    "background.fullscreen": {
        "image": "C:/Users/rmyeow/Desktop/wallpaper/bear.jpg",
        "opacity": 0.91,
        "size": "cover",
        "position": "center",
        "interval": 0
    },
}

#This is my file but the bear picture is not showing, what is the issue?

**Comment by NoDocCat** [comment]
Please use `file` or `https` to load images
