### ISSUE TITLE
弱弱的问一句，怎么卸不掉呀？ORZ

### ISSUE THREAD

**Issue by fungwan** [shalldie/vscode-background#39]
背景图还在，我换了一张岛国动作电影女主角的图片看看效果，后面准备换掉，结果卸不掉=_=!!!

**Comment by shalldie** [comment]
哈哈哈哈哈，我笑了半天，感觉你应该好着急。

![image](https://cloud.githubusercontent.com/assets/9987486/23349950/fc07c988-fcf1-11e6-9607-52c01dde1a9b.png)

卸载，需要设置 background.enabled=false 先

**Comment by fungwan** [comment]
我已经重新安装vscode了。还是谢谢作者鸟^_^。
