### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by myluckytimes** [shalldie/vscode-background#392]
1. 安装后提示权限问题  EPERM: operation not permitted, open 'd:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\ workbench.desktop.main.css'
2.  修改文件的所有用户权限都是“完全控制”后，可以显示默认图片
3.  若自定义全屏设置不会显示
```
"background.enabled": true,
"background.useDefault": true,
// "background.fullscreen": {
    // "image": "E:\\24188\\Pictures\\background\\拒霜思.png", // url of your image
    // "opacity": 0.91, // 0.85 ~ 0.95 recommended
    // "size": "cover", // also css, `cover` to self-adaption (recommended)，or `contain`、`200px 200px`
    // "position": "center", // alias to `background-position`, default `center`
    // "interval": 0 // seconds of interval for carousel, default `0` to disabled.
// },
```

**Comment by NoDocCat** [comment]
`background.useDefault` 这个配置的优先级是最高的, 它存在的时候所有自定义图片都不会生效. 将它设置为 `false` 就好了.
另外你的图片路径存在问题, 必须使用 `https` 或者 `file` 协议.

**Comment by NoDocCat** [comment]
@shalldie `background.useDefault` 这个配置项或许可以优化一下, 发现有自定义的图片配置后应该自动关闭, 而不是像现在这样需要用户手动关闭.

另外上大给我加个协作权限吧, 我方便处理 issue 的时候打 tag.

**Comment by shalldie** [comment]
> @shalldie `background.useDefault` 这个配置项或许可以优化一下, 发现有自定义的图片配置后应该自动关闭, 而不是像现在这样需要用户手动关闭.
> 
> 另外上大给我加个协作权限吧, 我方便处理 issue 的时候打 tag.

Done，还是第一次用这个功能

**Comment by myluckytimes** [comment]
> `background.useDefault` 这个配置的优先级是最高的, 它存在的时候所有自定义图片都不会生效. 将它设置为 `false` 就好了. 另外你的图片路径存在问题, 必须使用 `https` 或者 `file` 协议.

按这个修改之后还是有问题：透明度能调节，但是图片仍然不显示
```
"background.enabled": true,
"background.useFront": true,
"background.useDefault": false,
"background.fullscreen": {
    "image": "file://E:/24188/Pictures/background/拒霜思.png",
    "opacity": 0.91,
    "size": "cover",
    "position": "center",
    "interval": 0
},
```

**Comment by NoDocCat** [comment]
另外图片路径协议这个也需要优化一下, 不符合要求的应该有提示
配置项应该可以添加正则验证的规则, 在配置时提示用户而不是拖到生成时再检查

**Comment by myluckytimes** [comment]
> @shalldie `background.useDefault` 这个配置项或许可以优化一下, 发现有自定义的图片配置后应该自动关闭, 而不是像现在这样需要用户手动关闭.

有个小建议不知道可行不：背景图片可以随着外观改变。当外观是浅色主题时设置一张图片，当外观是深色主题时设置另一张图片。

**Comment by NoDocCat** [comment]
@myluckytimes 目前没有办法通过媒体查询确定主题是否为深色, 使用 `prefers-color-scheme` 只能获取操作系统的主题设置.

例如我在 vscode 中使用的主题是默认的 `现代深色`, 但是通过媒体查询匹配的结果如下:

![image](https://github.com/shalldie/vscode-background/assets/20502666/4566805d-0440-41bb-9b45-d495ca8261c7)

如果有更好的实现方法, 欢迎 PR.

**Comment by myluckytimes** [comment]
> @myluckytimes 目前没有办法通过媒体查询确定主题是否为深色, 使用 `prefers-color-scheme` 只能获取操作系统的主题设置.

我是使用以下配置和Auto Dark Mode实现VScode外观随系统外观变化的，如果能获取到这些配置应该能实现背景随外观变化。我在 https://code.visualstudio.com/api/references/vscode-api 看到有个 getConfiguration 的 API，不知道能否使用它实现获取配置信息。

```
"window.autoDetectColorScheme": true,                       //根据系统外观自动切换到首选颜色主题
"workbench.preferredLightColorTheme":"GitHub Light Default",//系统浅色主题时使用的主题
"workbench.preferredDarkColorTheme": "GitHub Dark Default", //系统是深色主题时的默认外观
```

**Comment by shalldie** [comment]
图片 url 校验确实需要，已经看到 pr了，强需求p0

根据主题切换图片，需要考量下。
之前收到过类似的需求，比如根据不同主题显示不同图片。

一个是场景比较复杂，比如多个切换场景的优先级，，新旧配置兼容balabala，，，
另一方面成本大。
这类需求会先记下来，根据用户反馈情况选择呼声高的加入feature

**Comment by webxmsj** [comment]
> 

有办法区分， 尝试设计下图片配置的api

**Comment by webxmsj** [comment]
> @myluckytimes 目前没有办法通过媒体查询确定主题是否为深色, 使用 `prefers-color-scheme` 只能获取操作系统的主题设置.
> 
> 例如我在 vscode 中使用的主题是默认的 `现代深色`, 但是通过媒体查询匹配的结果如下:
> 
> ![image](https://user-images.githubusercontent.com/20502666/238502745-4566805d-0440-41bb-9b45-d495ca8261c7.png)
> 
> 如果有更好的实现方法, 欢迎 PR.

有办法区分， 尝试设计下图片配置的api
