### ISSUE TITLE
如何在调低opacity属性的同时让代码不被图片覆盖住呢？

### ISSUE THREAD

**Issue by summerainX** [shalldie/vscode-background#394]
我想调低图片的opacity属性，让图片能看着更清楚点，但是这样的话代码就被图片盖住了导致看不清楚文字，如何能实现既让图片显示清晰又不影响文字显示呢，就像vs studio的背景插件效果一样
这是我现在的背景：
![图片](https://github.com/shalldie/vscode-background/assets/103112890/b1ef6e7e-1e20-4fa8-91c0-eea4ef8324df)
这是配置：
"background.fullscreen": {
        "image": "file:///Users/shuidi/工作/CODE/2.png", // url of your image
        // "image": ["https://pathtoimage.png"], // An array may be useful when set interval for carousel
        "position": "center", 
        "opacity": 0.4, // 0.85 ~ 0.95 recommended
        "size": "cover", // also css, `cover` to self-adaption (recommended)，or `contain`、`200px 200px`
        //"position": "center", // alias to `background-position`, default `center`
        "interval": 0 // seconds of interval for carousel, default `0` to disabled.
    },

想要的效果（vs studio的效果样式）
![图片](https://github.com/shalldie/vscode-background/assets/103112890/4bbc6833-7747-4388-b919-0cfd292b2706)

**Comment by shalldie** [comment]
全屏模式下，暂时只能做到这个程度 😂😂
一方面众口难调，另一方面确实没啥好办法

如果是代码区域，倒是有配置去区分 `前景/背景`

**Comment by shalldie** [comment]
https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE

`background.useFront` 前景/背景

**Comment by summerainX** [comment]
"terminal.integrated.fontWeight": "normal",
    "background.useFront": true,
    "background.customImages": ["file:///Users/shuidi/工作/CODE/2.png"],
    "background.style": {
        "opacity": 1
    },
我在案例里面没找该怎么写这种配置文件，我按照自己的理解写了一个，但是好像还是不生效，能提供一个模版么QAQ

**Comment by shalldie** [comment]
```json
{
  "background.useDefault": false,
  "background.useFront": false,
  "background.customImages": [
    "https://i.loli.net/2021/03/26/seH6v1pJIdODynX.png",
    "https://i.loli.net/2021/03/26/rYHWm9f6nt3pSwc.png",
    "https://i.loli.net/2021/03/26/seH6v1pJIdODynX.png"
  ],
  "background.interval": 12,
  "background.style": {
    "content": "''",
    "pointer-events": "none",
    "position": "absolute",
    "z-index": "99999",
    "width": "100%",
    "height": "100%",
    "background-position": "100% 100%",
    "background-repeat": "no-repeat",
    "background-size": "320px 460px",
    "opacity": 0.1
  }
}
```

`"background.useFront": false`  这里设置为 `背景`

**Comment by summerainX** [comment]
感谢大佬的教学 问题解决了，现在舒服了，另这里"background-size"设置成“cover”的话基本就能覆盖各种尺寸的图片了
