### ISSUE TITLE
1.10版本的minimap会遮挡一部分背景图

### ISSUE THREAD

**Issue by jerrwy** [shalldie/vscode-background#40]

**Comment by FelixZh0u** [comment]
遇到相同问题
版本：1.10.2

**Comment by shalldie** [comment]
看到了这个问题，周末我会处理一下，看看有什么好的方式。 :laughing:

**Comment by wolfsilver** [comment]
小地图设置了半透明，感觉还不错

![image](https://cloud.githubusercontent.com/assets/2452450/23824893/6abaf5b8-06ba-11e7-8f6b-cbd936ec2257.png)

**Comment by shalldie** [comment]
@wolfsilver  是通过系统的配置设置的？还是什么

**Comment by wolfsilver** [comment]
直接改样式

**Comment by FelixZh0u** [comment]
@wolfsilver 这种方式也不错啊

**Comment by shalldie** [comment]
这两天就改了提上去

**Comment by shalldie** [comment]
非常不好意思，，早就承诺了要改的。
但是tmd连续加班好多天，刚刚才下班。
这周一定改

**Comment by felixzh0u** [comment]
我是来催更的，23333😅

2017-03-23 1:07 GMT+08:00 谢爽 <notifications@github.com>:

**Comment by shalldie** [comment]
@felixzh0u 
0.0 昨晚就怕有人催更，凌晨2点半特地发了个版本，你更新一下喽

**Comment by felixzh0u** [comment]
@shalldie 2333， 辛苦了
