### ISSUE TITLE
windows全屏图片无法应用

### ISSUE THREAD

**Issue by lkyu-ly** [shalldie/vscode-background#400]
## Summary | 概述
全屏图片设置失败，无法应用，似乎并非管理员权限问题（vccode全程处于管理员模式下）

### Versions

- `OS(Win10 / Mac OSX / Linux)`:win11
- `vscode`:1.73
![Clip_230609_1156](https://github.com/shalldie/vscode-background/assets/67578466/fa0a0529-fa13-4b4b-8da3-94507a2bdef3)

### Background Config | 插件的配置

```json
{
    "background.fullscreen": {
    "images": ["file:///E:/Pictures/illust_86470349_20210122_170051Real-ESRAN.png"],
    "opacity": 0.8,
    "size": "cover",
    "position": "center",
    "interval": 0
  },
}
```

### 详细问题
在`settings.json`里如上面所述配置完成后，使用`ctrl+单击`可以打开图片，查看修改目标css显示如下：
![Clip_230609_1159](https://github.com/shalldie/vscode-background/assets/67578466/c4e55d5e-b3e3-480e-be83-9615b0c53ccc)
发现此链接无法被vscode读取。报错如下：
![Clip_230609_1200](https://github.com/shalldie/vscode-background/assets/67578466/5529ed96-92ab-4565-be64-319c017eac2c)

**Comment by Elpis1999** [comment]
我也遇到了相同的问题，windows下全屏配置不生效

### Versions
- `OS(Win10 / Mac OSX / Linux)`: Win10
- `vscode`: 1.77

### 配置
```
  "background.fullscreen": {
    "images": ["https://cdn1.tianli0.top/npm/elpis-picbed@latest/images/wallpaper5.png"],
    "opacity": 0.85,
    "size": "cover",
    "position": "center",
    "interval": 0
  }
```

**Comment by shalldie** [comment]
更新下 vscode 再试试~
因为使用了新的css选择器(https://github.com/shalldie/vscode-background/pull/399)，需要chromium105+才支持（为了修复刚打开闪烁的问题）

vscode版本比较老的话就不能支持了。

**Comment by flcloud4869** [comment]
@shalldie 加个特性检查吧, 支持的情况下才使用 has 选择器. 然后就是 loop 的默认行为没变就发版了 🤣🤣🤣

**Comment by hobbies-dev** [comment]
![image](https://github.com/shalldie/vscode-background/assets/35590801/f773646d-8876-4a75-970f-12cda54203a9)
![image](https://github.com/shalldie/vscode-background/assets/35590801/4767e1ee-da0c-4451-ab08-296e46fd52c4)
我更新了vscode版本，设置里也配置了自定义的图片路径，全屏图片还是无法生效

**Comment by hobbies-dev** [comment]
@lkyu-ly 你更新后，全屏图片能生效吗

**Comment by lkyu-ly** [comment]
> @lkyu-ly 你更新后，全屏图片能生效吗

刚更新完，生效了
![Clip_230609_1815](https://github.com/shalldie/vscode-background/assets/67578466/33670fc8-15bd-4212-9a99-0988037d5575)

**Comment by hobbies-dev** [comment]
@shalldie 已经能显示，感谢

**Comment by lkyu-ly** [comment]
感谢解答，已经生效了 @shalldie

**Comment by shalldie** [comment]
之前没考虑到低版本vscode的case。

发布了 `v1.2.12` 兼容低版本vscode，在使用 `vscode >= 1.78` 时可以获得最佳体验。
