### ISSUE TITLE
[Bug Report] Full background not working anymore

### ISSUE THREAD

**Issue by carlos-mta** [shalldie/vscode-background#401]
## Summary | 概述

Image not showing with the following config:

```json
  "background.fullscreen": {
    "images": ["https://images6.alphacoders.com/118/1188708"],
    "opacity": 0.91,
    "size": "cover",
    "position": "center",
    "interval": 0
  }
```

### Versions

- Linux Elementary OS distro
- VSCODE 1.74.2

![Captura realizada el 2023-06-09 15 32 41](https://github.com/shalldie/vscode-background/assets/109365219/f0bff224-52cd-492d-bb58-0dccd8384f3d)

### Background Config | 插件的配置

```json
  "background.enabled": true,
  "background.fullscreen": {
    "images": ["https://images6.alphacoders.com/118/1188708"],
    "opacity": 0.91,
    "size": "cover",
    "position": "center",
    "interval": 0
  }
```

### Expected Behaviors | 期望的行为

Show the fullscreen image

**Comment by shalldie** [comment]
update your vscode ~ and you will see it

**Comment by shalldie** [comment]
I didn't consider the case of lower version vscode before.

Update your vscode, or try new version `v1.2.12`, which is compatible with lower versions of vscode, providing the best experience when using `vscode>=1.78`.
