### ISSUE TITLE
同时有上下和左右分屏的时候图片显示错误

### ISSUE THREAD

**Issue by AllenHee** [shalldie/vscode-background#403]
## Summary | 概述

vscode同时打开上下和左右的分屏图片显示的顺序错误了，除了第一张之外，其他都显示的是第二张图片

### Versions

v1.2.12

- `OS( Mac OSX)`:
- `vscode`:

### Background Config | 插件的配置
```json
"background.customImages": ["file:///Users/hewei/bg/bg67.jpg", "file:///Users/hewei/bg/bg1.jpg", "file:///Users/hewei/bg/bg82.jpg"],
```

![image](https://github.com/shalldie/vscode-background/assets/16890350/f3f44558-a135-42ee-ab30-e4b6a5c54478)

**Comment by shalldie** [comment]
<img width="311" alt="image" src="https://github.com/shalldie/vscode-background/assets/9987486/cfa46d35-2acc-4540-89a8-429a6f000909">

面板分割方式非常非常灵活，子面板也能够横/竖向继续分割，
所以很难定义应该以什么为基准，往哪个方向去循环显示图片。

考虑到大多数人的使用习惯（也是vscode默认分配方式），目前排版如图，以左上为基准，往右下方每多一圈就算一层。
这样最大化的兼顾了【从左到右】、【从上到下】的排列方式

**Comment by AllenHee** [comment]
好的，感谢
