### ISSUE TITLE
background.style属性的opacity属性的修改似乎没有用，启用插件后文字透明度过高以至于看不清楚

### ISSUE THREAD

**Issue by FrSprWind** [shalldie/vscode-background#404]
"background.interval": 300,
    "background.customImages": [
// 一系列图片
],
    "background.style": {
        "opacity": 0.85,
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "100% 100%",
        "background-repeat": "no-repeat"
    },
    "background.useFront": false

**Comment by shalldie** [comment]
试了下你的配置没问题。使用的版本、系统环境呢？

要不你把 opacity 改低点试试

**Comment by suiyun39** [comment]
怀疑是 `z-index` 的问题, 尝试仅保留要修改的样式. 如果需要全屏背景的话, 请使用 `fullscreen`

**Comment by FrSprWind** [comment]
系统环境是windows11，使用的background版本是1.2.12版，opacity改低似乎没什么用

**Comment by FrSprWind** [comment]
z-index好像也没问题的样子emoji

**Comment by FrSprWind** [comment]
<img width="890" alt="屏幕截图 2023-07-05 172850" src="https://github.com/shalldie/vscode-background/assets/122779621/031dd652-7a60-4cbd-b6d6-794eaba7c192">
界面看起来是这个样子的

**Comment by shalldie** [comment]
看起来像设置了  `background.fullscreen`，check 下？
全屏会覆盖其它设置

**Comment by FrSprWind** [comment]
用fullscreen解决了，谢谢您们，mua
