### ISSUE TITLE
[Bug Report] Background appears in unintended places

### ISSUE THREAD

**Issue by Loskir** [shalldie/vscode-background#405]
## Summary | 概述

Background appears over the buttons on extension page

<img width="614" alt="image" src="https://github.com/shalldie/vscode-background/assets/21295738/49bf6620-bc16-466b-af52-92cebeb61fda">

### Versions

Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:40:17.963Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

### Background Config | 插件的配置

Out of the box

### Expected Behaviors | 期望的行为

Background should not appear here

**Comment by suiyun39** [comment]
Can you provide your config?

**Comment by suiyun39** [comment]
The issue repeat with #416, It will be fixed in the next verison, please wait.

**Comment by suiyun39** [comment]
This is fixed, close
