### ISSUE TITLE
[Question] 无法更换背景图片

### ISSUE THREAD

**Issue by xiaopangju** [shalldie/vscode-background#408]
## Summary | 概述

我尝试更换背景，但无反应，vscode似乎不想让我用root权限启动。

### Versions

- `OS(Win10 / Mac OSX / Linux)`:Archlinux
- `vscode`:版本: 1.80.1
提交: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
日期: 2023-07-12T17:22:25.257Z
电子: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.6-arch1-1

### Additional Context | 其它信息

我使用的包是AUR上的visual-studio-code-bin，选择图片后无反应，尝试重启，也没有丝毫变化。尝试使用sudo启动vscode，提示“You are trying to start Visual Studio Code as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.”
求一个解决方案，谢谢。

**Comment by shalldie** [comment]
搜了一下 `visual-studio-code-bin` 貌似是个二进制版本。

当前插件是通过修改硬盘上css文件来实现换背景的，不适用于二进制版本的vscode。
感觉sudo了也不能work，，，

需要使用 `非binary` 的版本。我对Archlinux不熟悉，需要其它朋友分享点经验

**Comment by xiaopangju** [comment]
@shalldie 我试着把`visual-studio-code-bin`这个包卸载之后安装`code`这个包，发现找不到这个扩展了。我不清楚下一步要做什么。

**Comment by xiaopangju** [comment]
这个链接或许可以提供些参考：https://wiki.archlinuxcn.org/wiki/Visual_Studio_Code

**Comment by xiaopangju** [comment]
啊，抱歉，我好像提错项目了

**Comment by Zylsjsp** [comment]
> 搜了一下 `visual-studio-code-bin` 貌似是个二进制版本。
AUR的这个包是通过微软发布的tar包进行安装的 不是AppImage这种单一应用镜像 https://aur.archlinux.org/packages/visual-studio-code-bin 在Source对应的信息可以看到构建使用的源文件列表
> 当前插件是通过修改硬盘上css文件来实现换背景的，不适用于二进制版本的vscode。 感觉sudo了也不能work，，，
1.x实现的方式在v1.94-都可用 升级2.x后仍然是可用的 除了需要按照readme修改配置文件使用之前的壁纸 我认为插件的工作方式不会因为vscode的打包方式不同就有差异

**Comment by shalldie** [comment]
@Zylsjsp 
条件有限，并没有去实际尝试
我以为二进制版本的意思就直接打包成一个 可执行binary，不会再次解压

后面会再更新文档
