### ISSUE TITLE
自定义图片显示不出来

### ISSUE THREAD

**Issue by chueia** [shalldie/vscode-background#41]
"background.useDefault": false,
    "background.customImages": [
        "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1489728605120&di=39e2c2a49613a1a11353e0d577165573&imgtype=0&src=http%3A%2F%2Fcartoon.zwbk.org%2FImageUploadTK%2F63468890451334875012523622145.jpg",
        "file:///G:/1.png"
    ]

设置里是这么写的，网上的图片和本地都显示不出来，要怎么改呢？

**Comment by shalldie** [comment]
建议都换成本地图片，先把图片下到电脑里先。
看着没问题，不知道是否开启管理员权限？默认图片能显示么

**Comment by chueia** [comment]
默认的能显示呢  我再捣敲捣敲

**Comment by boxuanzhang** [comment]
`    "background.enabled": true,
    "background.useDefault": false,
    "background.customImages": [
        "file:///C:/xixi.jpg"
    ]`
您好，十分感谢您制作的插件，这是我的config代码，在win下可以直接ctrl加鼠标右键点开文件连接在vsc里面打开图片，证明路径格式正确，默认图片可以正常显示，已经打开管理员权限。
最后再次感谢你制作的插件~
祝好

**Comment by shalldie** [comment]
@boxuanzhang 
自定义图片显示不了么？
把这个图片拖到浏览器，然后用地址栏的路径试试。
