### ISSUE TITLE
默认样式中的 z-index: 99999 会遮挡提示框

### ISSUE THREAD

**Issue by 0x-jerry** [shalldie/vscode-background#412]
## Summary | 概述

默认样式中的 `z-index: 99999` 会遮挡提示框。

<img width="653" alt="image" src="https://github.com/shalldie/vscode-background/assets/14226737/86209d28-18ba-4e5e-9a2b-f76bd22b1dff">

### Versions

Version: 1.82.0 (Universal)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:09:41.364Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0

### Background Config | 插件的配置

使用默认配置，无更改

### Expected Behaviors | 期望的行为

不遮挡

### Additional Context | 其它信息

<img width="1440" alt="image" src="https://github.com/shalldie/vscode-background/assets/14226737/3ad38f76-0757-41da-92ec-ba5e30fbc5bf">

改成 1 可解决

**Comment by suiyun39** [comment]
这个改动，我需要和 @shalldie 讨论一下当时为什么要用这么大的 z-index 值，似乎是为了实现 useFront 而设置的来着。
请给我们一些时间回忆一下，谢谢

**Comment by shalldie** [comment]
回忆不起来，估计当年随手写的吧，，，
这周check下没问题就合入
