### ISSUE TITLE
[Bug Report] 设置背景之后再其他地方也出现了背景

### ISSUE THREAD

**Issue by YL-python** [shalldie/vscode-background#416]
### Versions

- `OS(Win10 / Mac OSX / Linux)`: Mac OS
- `vscode`: 1.82.2

### Background Config | 插件的配置

```json
{
    "background.enabled": true,
  "background.useFront": true,
  "background.useDefault": false,
  "background.customImages": [
    "https://upload-bbs.miyoushe.com/upload/2023/02/24/196231062/8540249f2c0dd72f34c8236925ef45bc_3880538836005347690.png",
  ],
  "background.style": {
    "content": "''",
    "pointer-events": "none",
    "position": "absolute",
    "z-index": "99999",
    "right": "7%",
    "bottom": "0",
    "width": "30%",
    "height": "30%",
    "background-repeat": "no-repeat",
    "background-size": "contain",
    "opacity": 0.3
  },
}
```

### Screenshots | 截图

这是我的背景
<img width="1499" alt="image" src="https://github.com/shalldie/vscode-background/assets/49944266/ce7c3f22-3f6b-4dd9-b3b3-be660dcc49af">

现在我发现我的背景会出现在其他地方

比如 插件详情页的安装按钮
<img width="596" alt="image" src="https://github.com/shalldie/vscode-background/assets/49944266/e15c9623-9ae7-462d-813a-5889a10a425d">

键盘快捷键设置的源这里
<img width="1562" alt="image" src="https://github.com/shalldie/vscode-background/assets/49944266/b648c412-4530-4a30-b486-d09e3e6a0e6b">

放大看长这样
<img width="1359" alt="image" src="https://github.com/shalldie/vscode-background/assets/49944266/f3413868-324d-43b5-9c5e-0ff4d31b1562">

**Comment by shalldie** [comment]
感谢反馈！后面找时间修一下
