### ISSUE TITLE
[Question] 怎么精确定位？

### ISSUE THREAD

**Issue by alpha-xdream** [shalldie/vscode-background#417]
我调整好图片的位置后，隐藏侧边栏发现位置又不对了。请问有没有办法精确定位到代码预览栏那个位置？
![image](https://github.com/shalldie/vscode-background/assets/8527855/48162025-0316-4374-93fe-8998a91db1cb)
![image](https://github.com/shalldie/vscode-background/assets/8527855/c96c74d0-6d66-4502-93d2-968157110c65)

**Comment by shalldie** [comment]
看了下应该做不到，minimap的宽度会随着窗口宽度动态调整。

**Comment by alpha-xdream** [comment]
感谢回复。我改成图片贴边，鼠标移过去才显示minimap
