### ISSUE TITLE
[Question] Set image fullscreen under the code

### ISSUE THREAD

**Issue by Spc-CXCVIII** [shalldie/vscode-background#419]
### Background Config

```json
{
  "background.useFront": false,
  "background.fullscreen": {
    "images": ["file:///D:/image.jpg"],
    "size": "cover",
    "content": "''",
    "pointer-events": "none",
    "position": "absolute",
    "z-index": "99999",
    "height": "100%",
    "width": "100%",
    "background-position": "center",
    "background-size": "100%",
    "background-repeat": "no-repeat",
    "opacity": 0.5,
  },
}
```
```"background.useFront": false``` is not works
![FullScreen](https://github.com/shalldie/vscode-background/assets/117971480/6d89c04a-1b2f-44ff-a0d2-c3237f4894a3)

but it works with ```"background.customImages"```
![CustomImage](https://github.com/shalldie/vscode-background/assets/117971480/9829b934-f185-4a5f-97d0-182f42953e2d)

Is it possible to use ```"background.fullscreen"``` and set ```"background.useFront"```: false ?
Thanks,
Spc

**Comment by shalldie** [comment]
No, can't set image fullscreen under the code.

Full screen mode affects the entire editor and cannot be limited to the editing area

**Comment by Spc-CXCVIII** [comment]
Ok, Thanks for answer
