### ISSUE TITLE
gentoo 无法使用

### ISSUE THREAD

**Issue by VZIKL** [shalldie/vscode-background#42]

**Comment by shalldie** [comment]
win和mac测试是可以的。是否开启过管理员权限呢？
在windows环境中，可以右键单击vscode的图标，选择【以管理员身份运行】

**Comment by VZIKL** [comment]
:) gentoo 是 Linux的一个分支

**Comment by shalldie** [comment]
@VZIKL 
额，，这里有个 ubuntu 开启管理员权限的方式，不妨试试：
https://github.com/shalldie/vscode-background/issues/6

**Comment by VZIKL** [comment]
@shalldie  没有那个文件夹

**Comment by VZIKL** [comment]
修改/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.css 的权限
-> chmod 777 workbench.main.css 就正常工作了 ;D

**Comment by shalldie** [comment]
谢谢，我会记下来

**Comment by VZIKL** [comment]
这个文件夹不一定是我说的目录 毕竟vscode并不在gentoo的源里 (具体位置还是要根据vsc自带的开发者工具里的报错信息
