### ISSUE TITLE
[Bug Report] fullscreen doesn't seem to work...

### ISSUE THREAD

**Issue by HalfSweet** [shalldie/vscode-background#422]
## Summary | 概述

After updating the version to v1.2.13, it seems that the configurations in background.fullscreen become invalid and I can't do a fullscreen image display. But the configuration in Custom Images still works!

### Versions

- `Win 11`:
- `vscode`:1.84.2 and 1.85.0-insider

### Background Config | 插件的配置

```json
    "background.fullscreen": {
        "image": "file:///C:\\Users\\HalfSweet\\OneDrive/图片/AiDraw/00001-3835532815.png",
        "opacity": 0.85,
        "size": "cover",
        "position": "center",
        "interval": 0,
    }
```

### Expected Behaviors | 期望的行为

I would like to display the full screen image correctly

### Screenshots | 截图

![图片](https://github.com/shalldie/vscode-background/assets/60973476/58058858-5447-4c2a-8e28-932c7c121df9)

**Comment by HalfSweet** [comment]
I found out what the problem was... in https://github.com/shalldie/vscode-background/issues/397 it mentions that the original `background.fullscreen.images` attribute was being deprecated, and I changed it to the new ` images` attribute, which fixed my problem.
One thing that puzzles me, though, is whether there should be a warning or an error if the `image` attribute is continued, and I'm not finding them!

**Comment by shalldie** [comment]
Anyway, it's been hard... 😂
Since 5 months ago, there was a warning prompt on 'background. fullscreen. image': 'deprecated,' will be removed in the next version '.

But it is true that the configuration page is not frequently opened, and future field adjustments will be more cautious and compatible.
