### ISSUE TITLE
[Bug Report] Some problem...

### ISSUE THREAD

**Issue by ngogiaphat** [shalldie/vscode-background#423]
### Versions
![image](https://github.com/shalldie/vscode-background/assets/54573446/2018e9b1-c24b-49cf-9bc7-4e41fb2efd98)

- `OS(Win10 / Mac OSX / Linux)`:
![image](https://github.com/shalldie/vscode-background/assets/54573446/7c5d1051-8ead-407e-aeb7-7a0726ba6332)
- `vscode`:
![image](https://github.com/shalldie/vscode-background/assets/54573446/1ffb4b63-bba0-4316-a0b4-b33919e00f01)

### Background Config | 插件的配置
my settings.json of me

### Expected Behaviors | 期望的行为

Why i don't turn off default background + loop ? See the picture

![image](https://github.com/shalldie/vscode-background/assets/54573446/0124cbe0-b1d4-4127-ba1a-1f35b5d85ff3)

See the picture, plsss =((((( Pls help me, the people in the picture is my sunshine, my idol, is my source of motivation =(((((

My configuration is as shown in picture 1 and if successful, it will look like this, 2nd photo ? 
![image](https://github.com/shalldie/vscode-background/assets/54573446/3816421f-5195-4e89-ad73-ee1106db111c)

and it don't work, see picture 3rd
![image](https://github.com/shalldie/vscode-background/assets/54573446/963cc8e1-51e9-4c31-b559-05c43ebbbd6b)

**Comment by suiyun39** [comment]
Fullscreen background and normal backgroud are mutually exclusive, It is recommended that you only use one.

About `background.loop` and `background.useDefault`, We found that these options caused a lot of trouble for users, so we removed these options in the new version.

In your scenario, my advice would be as follows:

1. Remove configuration except `background.enabled` and `background.fullscreen`
2. In `background.fullscreen` only keep `images` and `opacity`
3. Adjust `opacity` to your liking, For example `0.3 - 0.7`

**Comment by ngogiaphat** [comment]
> Fullscreen background and normal backgroud are mutually exclusive, It is recommended that you only use one.
> 
> About `background.loop` and `background.useDefault`, We found that these options caused a lot of trouble for users, so we removed these options in the new version.
> 
> In your scenario, my advice would be as follows:
> 
> 1. Remove configuration except `background.enabled` and `background.fullscreen`
> 2. In `background.fullscreen` only keep `images` and `opacity`
> 3. Adjust `opacity` to your liking, For example `0.3 - 0.7`

![image](https://github.com/shalldie/vscode-background/assets/54573446/e72c6177-bf6b-4b7b-ab60-c5fa35c7551a)


it's not working @@~

**Comment by ngogiaphat** [comment]
> Fullscreen background and normal backgroud are mutually exclusive, It is recommended that you only use one.
> 
> About `background.loop` and `background.useDefault`, We found that these options caused a lot of trouble for users, so we removed these options in the new version.
> 
> In your scenario, my advice would be as follows:
> 
> 1. Remove configuration except `background.enabled` and `background.fullscreen`
> 2. In `background.fullscreen` only keep `images` and `opacity`
> 3. Adjust `opacity` to your liking, For example `0.3 - 0.7`

it's working :">>> 
![image](https://github.com/shalldie/vscode-background/assets/54573446/df775ace-190e-4504-8376-ca1b932e60e6)

thank u very much 😘 I luv u 3k ❤️
