### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by TranPhuc9898** [shalldie/vscode-background#424]
I want to ask if it is possible to add colors corresponding to the background image. For example, I'm using goku gif but it seems a bit dark and not transparent. Is there any way to fix it and make it transparent so the color can be clearly seen? Thank you for answering a very good and useful extension
![Uploading Screenshot 2023-11-16 at 16.53.40.png…]()

**Comment by shalldie** [comment]
The screenshot is broken.

We can't add color to the background image, which may bring unpredictable risks.
The better way is to edit the image with some tools first(eg. Photoshop), add color or edit the opacity.
