### ISSUE TITLE
opacity is unused， due to the vscode update today？

### ISSUE THREAD

**Issue by baiwenmo** [shalldie/vscode-background#425]
I found that the opacity function is disabled today, no matter what values I fill in
my problem or vscode cause that？

**Comment by shalldie** [comment]
```
版本: 1.84.2 (Universal)
提交: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
日期: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.4.0
```

Works fine in my computer, can you provide the config and other environment message?

**Comment by baiwenmo** [comment]
win11，setting

**Comment by baiwenmo** [comment]
by the way, i cant disable this plugin. i can only change the png path to delete the picture in my vscode. and i can set the position and size, only except the opacity

**Comment by baiwenmo** [comment]
my bad, other plugin autosetting in this setting.json, sorry to waste your time

**Comment by shalldie** [comment]
OK.

And , if you want to use `fullscreen mode`，
need to replace `image` with `images` , which is an `Array`.
