### ISSUE TITLE
The sticker just doesn't go away, I cannot reinstall vscode, I tried everything please suggest a fix

### ISSUE THREAD

**Issue by Dhruvil099** [shalldie/vscode-background#427]
## Summary | 概述

I have already searched [GitHub Issues](https://github.com/shalldie/vscode-background/issues), ...

### Versions

- `OS(Win10 / Mac OSX / Linux)`:
- `vscode`:

**Comment by Dhruvil099** [comment]
I got it fixed !!!
By deleting a part in Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/ori_workbench.desktop.main.css.  
( not in Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.cs )
 delete starting from css-background-start till css-background-end. save that file and restart vscode.

**Comment by shalldie** [comment]
https://github.com/shalldie/vscode-background#uninstall

Sorry for coming late, this part of the doc shows how to uninstall it.
