### ISSUE TITLE
[Feature Request] 在FullscreenOptions下增加folder选项map到images里，可以更方便的导入本地文件夹路径

### ISSUE THREAD

**Issue by AnthonyZhang220** [shalldie/vscode-background#428]
第一次使用，体验很好。不过一个一个导入url或者文件路径感觉很吃力。之前在visual code用的ClaudiaIDE extension，里面支持本地文件夹路径自动导入，不知道能否支持一下。

目前的想法是：
不改动原来的逻辑，增加一个folder option,
```
{
  "background.fullscreen": {
    "images": ["https://pathtoimage.png"], // urls of your images
    "folder": "", // local folder
    "opacity": 0.91, // 0.85 ~ 0.95 recommended
    "size": "cover", // also css, `cover` to self-adaption (recommended)，or `contain`、`200px 200px`
    "position": "center", // alias to `background-position`, default `center`
    "interval": 0 // seconds of interval for carousel, default `0` to disabled.
  }
}

```
可以把本地文件夹路径里的图片推进```images[]```，然后options里images或者folder可选其一。

**Comment by shalldie** [comment]
这样的话可能会有这种case：无法感知 folder中的文件变动，进而触发配置更新。

暂时想不到更好的交互，或者直接唤起系统弹框选择文件，，？

**Comment by AnthonyZhang220** [comment]
ClaudiaIDE里好像也不能自动感知变动，需要重新启动visual studio。 有时候我在开启vs的时候添加图片到文件夹vs还会闪退，所以我在想是不是没有必要增加感知和交互，就重启vscode就可以达到期望的效果。如果想做交互的话可能会麻烦很多，我还需要去看看extension的reference guide，没有extension开发的经验，哈哈。

**Comment by shalldie** [comment]
在文件夹内图片变更的时候没办法自动更新，
手动更新也挺困难（文件夹地址没变），体验不好。

鉴于大部分情况图片并不多，copy/paste 就够了。先搁置吧我后面想想。

**Comment by shalldie** [comment]
现在 `v2.0.4` 版本已经支持了文件夹
