### ISSUE TITLE
如何为单个图片设置单独样式

### ISSUE THREAD

**Issue by astimes** [shalldie/vscode-background#43]
如何为单个图片设置单独样式
我又三个图片 尺寸不一
如果为这三张图设置不同的缩放尺寸

**Comment by shalldie** [comment]
有道理，可以加上

**Comment by astimes** [comment]
老哥 稳

**Comment by Mason-Xu** [comment]
我一般都自己PS,抠好图.....😂

**Comment by shalldie** [comment]
...... 终于可以把这个issue关了。

不好意思，我因为忙，也因为懒。。。一直拖到现在 hh

现在可以单独设置样式，透明度也都没问题了。
