### ISSUE TITLE
[Feature] 既想要全屏，又想要代码编辑区域右下角的图案能配置

### ISSUE THREAD

**Issue by Musicminion** [shalldie/vscode-background#430]
全屏会默认屏蔽其他的功能，有没有可能既有全屏，又能够配置代码编辑区域右下角的背景图案呢？

比如给他们设置不同的z-index？

**Comment by shalldie** [comment]
是特地做成这样的，不让他们同时存在。
「全屏」对其它部分的背景图影响非常大，效果很不好

**Comment by Musicminion** [comment]
还有一个问题，似乎在github code space里面不能用这个background插件？
<img width="235" alt="截屏2023-12-15 22 43 33" src="https://github.com/shalldie/vscode-background/assets/84625273/c157f136-ae6f-4d12-be97-0073aed7182f">

我找了三个，发现有两个老版本的，还有一个最新的，但是最新版的web是不可用的。
<img width="606" alt="截屏2023-12-15 22 43 50" src="https://github.com/shalldie/vscode-background/assets/84625273/e1cc927c-7594-45c8-bc8d-b61e8ddeaafc">

**Comment by shalldie** [comment]
@Musicminion 已知问题，插件主要应用于客户端。
web版目前只支持 code server，没有计划支持其它平台。

**Comment by suiyun39** [comment]
这两天简单的研究了一下，结论是：目前为止，无法在 Github Codespace / VSCode Dev 中实现同等的插件功能。

在 code-server 中是允许插件在服务端运行的。因此插件可以使用 Node API 来实现功能。

而在 Github Codespace / VSCode Dev 中，插件会被下发到浏览器并使用 Web Workers 运行。因此 Node API 和 DOM API 都无法在插件中使用，只能通过 VSCode 提供的有限 API 与之交互。

如果要实现同等功能，可能用浏览器的插件实现会更好。
