### ISSUE TITLE
[Feature] Would like to get an option to switch images between days

### ISSUE THREAD

**Issue by GymMed** [shalldie/vscode-background#431]
Hi, 
I really liked your extension and by having ability to change my background I noticed that I started wanting to open my code editor more frequently. 

However, while coding I encountered lot's of problems and background image started to associate with them. I wanted something fresh from time to time. On other hand, available options like carousel would distract my attention from coding.

[Feature]
Suggestion: could carousel have modes like days/seconds. I want that every new day when I open my editor, background image would change to new one from defined list. It doesn't matter which approach you choose, I am suggesting feature for every new day editor is opened to switch image to next defined in the list.

**Comment by suiyun39** [comment]
Sorry, If want to achieve the feature, We have to inject javascript into vscode instead of just inject css. But for a UI plugin, this is a bit too much.
If vscode provide API to modify the UI in the future, we would be happy to implement such the feature.
