### ISSUE TITLE
Persists even after uninstall

### ISSUE THREAD

**Issue by Iambeastofhell** [shalldie/vscode-background#432]
### Versions

- `OS(Win10 / Mac OSX / Linux)`:
- `vscode`:

**Comment by suiyun39** [comment]
Due to platform limitations, the implementation is compromised.
Please read the document to uninstall correctly.

https://github.com/shalldie/vscode-background#uninstall

**Comment by suiyun39** [comment]
@Iambeastofhell Has the problem been solved? If the problem still exists, Please reopen.
