### ISSUE TITLE
我的两台电脑忽然背景图片都不展示了

### ISSUE THREAD

**Issue by CtrlCandV** [shalldie/vscode-background#433]
我的两台电脑，背景图片都不展示了，我没有操作任何地方，图片也确认存在。现在只有默认的背景图片在展示。setting.json中内容也都存在，我尝试了卸载重装，没有任何作用。
vs code版本：
`版本: 1.85.1 (user setup)
提交: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
日期: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045`

background 版本：v1.2.13

settings.json内容：
`{
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook",
        "*.6": "default"
    },
    "python.pythonPath": "C:\\Users\\kll\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
    "editor.fontSize": 22,
    "security.workspace.trust.untrustedFiles": "open",
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "python.defaultInterpreterPath": "C:\\Users\\kll\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
    "background.loop": true,
    "background.interval": 10,
    "background.useDefault": false,
    "background.fullscreen": {
        "image": [
            "file:///F:/娱乐/壁纸/横/0.jpg",
            "file:///F:/娱乐/壁纸/横/1 (1).jpg",
            "file:///F:/娱乐/壁纸/横/1 (10).jpg",
            "file:///F:/娱乐/壁纸/横/1 (10).png",
            "file:///F:/娱乐/壁纸/横/1 (11).png",
            "file:///F:/娱乐/壁纸/横/1 (12).png",
            "file:///F:/娱乐/壁纸/横/1 (13).png",
            "file:///F:/娱乐/壁纸/横/1 (14).jpg",
            "file:///F:/娱乐/壁纸/横/1 (14).png",
            "file:///F:/娱乐/壁纸/横/1 (15).jpg",
            "file:///F:/娱乐/壁纸/横/1 (15).png",
            "file:///F:/娱乐/壁纸/横/1 (16).jpg",
            "file:///F:/娱乐/壁纸/横/1 (17).jpg",
            "file:///F:/娱乐/壁纸/横/1 (17).png",
            "file:///F:/娱乐/壁纸/横/1 (18).jpg",
            "file:///F:/娱乐/壁纸/横/1 (18).png",
            "file:///F:/娱乐/壁纸/横/1 (19).jpg",
            "file:///F:/娱乐/壁纸/横/1 (2).jpg",
            "file:///F:/娱乐/壁纸/横/1 (2).png",
            "file:///F:/娱乐/壁纸/横/1 (20).jpg",
            "file:///F:/娱乐/壁纸/横/1 (20).png",
            "file:///F:/娱乐/壁纸/横/1 (21).jpg",
            "file:///F:/娱乐/壁纸/横/1 (21).png",
            "file:///F:/娱乐/壁纸/横/1 (22).jpg",
            "file:///F:/娱乐/壁纸/横/1 (22).png",
            "file:///F:/娱乐/壁纸/横/1 (25).jpg",
            "file:///F:/娱乐/壁纸/横/1 (26).jpg",
            "file:///F:/娱乐/壁纸/横/1 (27).jpg",
            "file:///F:/娱乐/壁纸/横/1 (28).jpg",
            "file:///F:/娱乐/壁纸/横/1 (29).jpg",
            "file:///F:/娱乐/壁纸/横/1 (3).jpg",
            "file:///F:/娱乐/壁纸/横/1 (3).png",
            "file:///F:/娱乐/壁纸/横/1 (30).jpg",
            "file:///F:/娱乐/壁纸/横/1 (32).jpg",
            "file:///F:/娱乐/壁纸/横/1 (33).jpg",
            "file:///F:/娱乐/壁纸/横/1 (34).jpg",
            "file:///F:/娱乐/壁纸/横/1 (36).jpg",
            "file:///F:/娱乐/壁纸/横/1 (37).jpg",
            "file:///F:/娱乐/壁纸/横/1 (4).png",
            "file:///F:/娱乐/壁纸/横/1 (5).jpg",
            "file:///F:/娱乐/壁纸/横/1 (5).png",
            "file:///F:/娱乐/壁纸/横/1 (6).jpg",
            "file:///F:/娱乐/壁纸/横/1 (7).jpg"
        ], 
        "opacity": 0.85, // 建议值 0.85 ~ 0.95
        "size": "cover", // css, 建议使用 `cover`自适应，或者 `contain`、`200px 200px`
        "interval": 10 // 设置图片轮播切换间隔 `秒` 数，默认 `0` 表示不开启
      },
    "background.style": {

        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "100% 100%",
        "background-repeat": "no-repeat",
        "opacity": 1
    },
    "background.useFront": false,
    "background.styles": [

        {},
        {},
        {}
    ],
    "[python]": {
        "editor.formatOnType": true
    },
    "git.enableSmartCommit": true,
    "css.enabledLanguages": [
        "html"
    ],
    "editor.fontLigatures": false,
    "files.associations": {
        "*.vue":"html"
    },
    "emmet.triggerExpansionOnTab": true,
    "emmet.includeLanguages": {
        "vue-html":"html",
        "vue":"html"
    },
    "html.format.indentHandlebars": true,
    "html.format.indentInnerHtml": true,
    "html.format.templating": true
}`

**Comment by suiyun39** [comment]
请将 `background.fullscreen` 中的 `image` 改为 `images`，这个改动在上个版本已经声明过弃用了。

**Comment by suiyun39** [comment]
@CtrlCandV 问题已经解决了吗？如果还没有解决，请重新打开这个 issue。
