### ISSUE TITLE
[Feature] Randomized Image Ordering for Improved Visual Diversity

### ISSUE THREAD

**Issue by ericmp33** [shalldie/vscode-background#434]
Lets say I have n images:
```js
"background.fullscreen": {
    "images": [
        "https://w0.peakpx.com/wallpaper/991/1011/HD-wallpaper-3d-black-texture-geometric-black-texture-black-abstraction-background-3d-abstraction-black-texture-creative-black-background.jpg",
        // ...
    ],
    "opacity": 0.93,
    "size": "cover",
    "position": "center",
    "interval": 600
},
```

They get changed each 600 seconds. But always in the same order. If I have 300 images, I never see the last ones, since I'm not (600*300) minutes in VSCode. So I'd like to get them randomized, so I can see different images in a random order.

**Comment by suiyun39** [comment]
@ericmp33 

Because vscode don't provide API to modify UI with plugin, we took a hack method: According to your config, modify the style file of vscode.
So, in fact the background image switch is just a pre generated CSS animation. There can be nothing logical in it.
