### ISSUE TITLE
[Bug Report] 与Insider 1.86.0中与新的特性冲突

### ISSUE THREAD

**Issue by Moemu** [shalldie/vscode-background#435]
## Summary | 概述

在Insider 1.86.0中，似乎与新的特性冲突。它使得背景图片无法在此特性中显示。在这个特性中，它优化了代码块的显示，通过只显示父元素以省略不必要的代码块，但新的代码块底部无法显示背景图片。

### Versions

- `OS(Win10 / Mac OSX / Linux)`: Win10
- `vscode`:

版本: 1.86.0-insider (user setup)
提交: aed5f4d65d2dbfda2c98abd7eb371751016838ab
日期: 2024-01-17T07:04:28.837Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22635
### Background Config | 插件的配置

```json
"background.customImages":[
        "file:///E:/壁纸/ピロリ菌/F0Cw-tQaQAAObWn-16.9.jpg"
    ],
    "background.useFront": false,
    "background.styles": [
    

        {},
        {},
        {}
    ],
    "background.style": {

        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "100% 100%",
        "background-repeat": "no-repeat",
        "opacity": 0.06,
        "background-size": "cover"
    },
    "background.fullscreen": {
        "images": "",
        "opacity": 0.96,
        "size": "cover",
        "position": "center",
        "interval": 0
    },
```

### Expected Behaviors | 期望的行为

壁纸图片应该完整地被显示在代码区域中

### Screenshots | 截图
![ 代码行的上部无法显示图片 ](https://github.com/shalldie/vscode-background/assets/72406624/652f931d-47bf-4d52-8c45-468ec4d620fc)

### Additional Context | 其它信息

使用background.useFront可以解决此问题

**Comment by suiyun39** [comment]
这个问题先留一下吧，毕竟 Insider 不能保证稳定，等这个版本 release 后再看一下是不是要做特殊处理。

**Comment by suiyun39** [comment]
@Moemu 另外，如果想使用全屏背景的话，可以删除掉其他的配置，仅保留 `background.fullscreen`。相对来说，全屏背景的配置是专门设计的，比用样式模拟兼容性会好很多。

**Comment by suiyun39** [comment]
@Moemu 1.86 版本已发布 release。经验证，新特性对背景图并未造成影响，两种工作模式展示的效果都符合预期。

根据你的配置，建议使用全屏模式来设置背景图，如果在使用过程中发现有其他问题，欢迎 reopen。

![image](https://github.com/shalldie/vscode-background/assets/20502666/0a7a61cc-8356-470d-86c0-06f4ab14d56a)

![image](https://github.com/shalldie/vscode-background/assets/20502666/8de071a7-2a17-431c-b082-564424735330)
