### ISSUE TITLE
在 Windows 下，设置的背景未影响右上角的操作按钮区域

### ISSUE THREAD

**Issue by suiyun39** [shalldie/vscode-background#437]
### Discussed in https://github.com/shalldie/vscode-background/discussions/436

<div type='discussions-op-text'>

<sup>Originally posted by **TaoZhi23** January 22, 2024</sup>
设置backgroun: fullscreen后，页面右上角的关闭、最小化按钮处不透明
![bug](https://github.com/shalldie/vscode-background/assets/118145424/4a0dc51b-5233-4b7a-ab45-4fdb8614dcdd)
</div>

**Comment by shalldie** [comment]
记得有朋友以前提过这个问题，刚刚没找到。
这部分（最小化、放大、关闭按钮）应该不属于「electron」，而属于「系统」，在不同操作系统(win7、8.1、10)上也会表现不一致。
同样的，mac上的那3个圆点也同样属于系统，不会受到css部分的影响

**Comment by suiyun39** [comment]
开虚拟机确认了一下，确实是 windows 系统的问题：

![image](https://github.com/shalldie/vscode-background/assets/20502666/66813c3d-7278-477c-8cff-9c9069917bdd)

**Comment by TaoZhi23** [comment]
Windows的问题那就不管了

**Comment by ShiqiChen2022** [comment]
有没有什么办法可以解决呢，强迫症患者很难受

**Comment by Spyict** [comment]
> 有没有什么办法可以解决呢，强迫症患者很难受

有个治标不治本的方法，始终全屏打开，就没有那三个控件了，不过现在有更好的办法吗
