### ISSUE TITLE
[Bug Report] 安装这个插件提示code损坏

### ISSUE THREAD

**Issue by duhbbx** [shalldie/vscode-background#438]
![image](https://github.com/shalldie/vscode-background/assets/26406531/a19fd336-6490-4592-9727-fd12d541bb9e)

删除了这个插件，背景图片还在，有点哈人

**Comment by shalldie** [comment]
已知case，已在文档中列出。

关于损坏提示： https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E6%B3%A8%E6%84%8F

卸载： https://github.com/shalldie/vscode-background/blob/master/README.zh-CN.md#%E5%8D%B8%E8%BD%BD

**Comment by suiyun39** [comment]
@duhbbx 由于 vscode 的限制，我们不得不使用了一些 hack 的方式实现了背景图的功能，所以造成了一些插件行为的怪癖。因此请仔细阅读使用文档。

**Comment by duhbbx** [comment]
ok, thanks a lot
