### ISSUE TITLE
[Feature] Your great idea...  大量图片的管理

### ISSUE THREAD

**Issue by yulunyue** [shalldie/vscode-background#439]
我有很多张图片时，能否在轮播的images的http请求带上时间和索引。 例如增加一个参数 image_range_num_max: int 。如果配置了这个参数就在加载图片的url后面带上这个参数，它的值应该是递增的。。顺便也可以带上一个time参数，值为时间戳。。这样可以和本地的http 图片爬虫服务一起使用，拿到很多网上随机的图片，几张图片已经看腻了，管理起来也麻烦

**Comment by suiyun39** [comment]
插件的实际工作原理，是根据你的配置去修改 vscode 的样式文件，所以不能做一些动态运行的事情。

我建议你可以在 web server 端解决这些问题，比如一个 get 接口每次随机扔一张图片出来，这样你每次打开新的标签页都会是随机的背景图。关于同 url 的缓存问题，因为 vscode 和浏览器的工作模式相同，所以你可以通过 http headers 来禁止缓存。

**Comment by yulunyue** [comment]
好多，多谢。http headers 来禁止缓存，这个不太确定，因为之前改了本地同名文件，没生效感觉可能做不到

**Comment by suiyun39** [comment]
> 好多，多谢。http headers 来禁止缓存，这个不太确定，因为之前改了本地同名文件，没生效感觉可能做不到

直接简单粗暴一点：`Cache-Control: no-store`

**Comment by yulunyue** [comment]
不支持http，只支持https吗

**Comment by yulunyue** [comment]
哎，不安全的https也不支持，这是bug吗

**Comment by shalldie** [comment]
> 哎，不安全的https也不支持，这是bug吗
@yulunyue 
符合预期，网页也打不开不安全的啊，，会弹出各种警告
插件没有做什么，是vscode自身的限制。

**Comment by yulunyue** [comment]
但是http也不支持呢，为什么呀

**Comment by shalldie** [comment]
> 但是http也不支持呢，为什么呀

@yulunyue 
https://code.visualstudio.com/api/extension-guides/webview#only-load-content-over-https
在某个版本后，http就被vscode禁用了，估计是考虑不安全吧
