### ISSUE TITLE
[Bug Report] Some problem...

### ISSUE THREAD

**Issue by Ririsu-Kokoromu** [shalldie/vscode-background#440]
红框部分无法点击，把top和left或者position注释掉之后就正常了

![image](https://github.com/shalldie/vscode-background/assets/120046369/7a50a3d2-ed9f-4c6b-94b2-19cf5d921816)

**Comment by suiyun39** [comment]
全屏背景请使用：https://github.com/shalldie/vscode-background?tab=readme-ov-file#fullscreen-config

使用伪元素模拟全屏背景的用例在有 fullscreen config 之后，不再考虑支持。

**Comment by suiyun39** [comment]
@Ririsu-Kokoromu 请问问题解决了吗？如果还存在问题，欢迎 reopen。
