### ISSUE TITLE
Does any know if this works on a mac? [Question] Some question...

### ISSUE THREAD

**Issue by tizol** [shalldie/vscode-background#441]
## Does this full screen background image work on a mac? | 概述

I have already searched [GitHub Issues](https://github.com/shalldie/vscode-background/issues), ...

### Versions

- `OS(Win10 / Mac OSX / Linux)`: macOS Ventura 13.5
- `vscode`:  Version: 1.86.2

### Background Config | 插件的配置

```json
  "background.fullscreen": {
        "image": "https://tonyhandyman.com/assets/images/Front/front1.jpg", 
        "opacity": 0.91, 
        "size": "cover", 
        "position": "center", 
        "interval": 0 
      }
```

### Additional Context | 其它信息
I made the setting changes  but after save and restarting VS code multiple times I still see the original image logo

<img width="1417" alt="Screenshot 2024-02-20 at 1 54 23 PM" src="https://github.com/shalldie/vscode-background/assets/6495684/b5d850f9-52de-40d8-b719-7b91967c1fad">

**Comment by shalldie** [comment]
Not `image` but `images`, it's an `Array`.

```json
  "background.fullscreen": {
    "images": ["https://tonyhandyman.com/assets/images/Front/front1.jpg"],
    "opacity": 0.91,
    "size": "cover",
    "position": "center",
    "interval": 0
  }
```

This works fine on my mac.

**Comment by tizol** [comment]
<img width="1214" alt="CODE " src="https://github.com/shalldie/vscode-background/assets/6495684/be240162-f08c-4b82-b843-13ecfef23cc5">

I was able to get it working. Thanks ☺️
