### ISSUE TITLE
[Question] Some question...

### ISSUE THREAD

**Issue by zpwc** [shalldie/vscode-background#443]
## Summary | 概述
使用https网址可以正常显示图片，但是使用file协议却失败无法更新图片。我的图片路径是`/home/ubuntu/my_file/26.jpg`。我想确定是不是我的file协议写错了还是说存在bug

### Versions

- 系统版本`Ubuntu 22.04.4 LTS`:
- `vscode`:code-server: v4.16.1 版本: 1.80.2

### Additional Context | 其它信息
通过点击`file:///home/ubuntu/my_file/26.jpg`弹出如下报错信息：
~~请无视之前https下载图片的残余背景~~
`(FileSystemError): Error: No file system handle registered (\home))`
![image](https://github.com/shalldie/vscode-background/assets/132753455/7e11f44b-3e18-4946-991e-f63d9c42f4ef)
我确定我已经给my_file文件夹以及其下文件赋予了777的权限

**Comment by shalldie** [comment]
code-server 是web版，运行在浏览器的网页访问不了硬盘，跟客户端版本（vscode）不太一样。

插件有限支持web版本，这里还是换成 https 吧~
