### ISSUE TITLE
切回vscode的时候闪屏

### ISSUE THREAD

**Issue by AsukaShinichi** [shalldie/vscode-background#447]
## Summary | 概述

我用的是双屏，鼠标从另外一个屏幕回来点击vscode的时候背景图片会覆盖整个页面
![image](https://github.com/shalldie/vscode-background/assets/153926862/4e7a2918-6803-4d45-9ba2-77dbe06928c3)
然后再点一下vscode所在桌面的任务栏就又恢复正常了
这种情况发生的非常频繁

### Versions

- `OS(Win10 / Mac OSX / Linux)`:win10
- `vscode`: 
1.88.1
e170252f762678dec6ca2cc69aba1570769a5d39
x64

**Comment by AsukaShinichi** [comment]
插件配置：
"background.fullscreen": {
        "images": [
            "file:///C:/Users/Asuka/Pictures/Saved%20Pictures/psc.png",
            "https://photogz.photo.store.qq.com/psc?/V133jLPf05pTEP/ruAMsa53pVQWN7FLK88i5s1d5opvl55d9yXiooj6Gjn4XS*LHNZix7*WsQUGNSeo6na9XRIG43RFXTb7GyYphVxM.kq4FqNevSaINETPG*k!/b&bo=QAk4BAAAAAADh9c!&rf=viewer_4"
        ],
        "opacity": 0.95,
        "size": "cover",
        "position": "center",
        "interval": 0
    }

**Comment by suiyun39** [comment]
目前手头没有 Win 10 的设备，能帮忙确认两个问题吗？

1. 在更新到 1.88.1 版本之前，是否出现过此问题或者类似的现象？
2. 更新到 1.89.1 之后，此问题是否依然继续出现？

**Comment by AsukaShinichi** [comment]
1.89.1还是存在，切换到1.87.2暂时没出现这个问题了，谢谢

**Comment by shalldie** [comment]
没有「win」+「双屏」，在单独的win上测试倒是没问题。
即将发布 v2.0，如果到时候仍然存在这个问题，请再打开issue。
