### ISSUE TITLE
How to show the background on dark mode

### ISSUE THREAD

**Issue by jugo-de-mora** [shalldie/vscode-background#448]
I have already searched [GitHub Issues](https://github.com/shalldie/vscode-background/issues), ...

I currently have a dark theme, I want to set a galaxy background (which of course is dark) however it barely be seen when I highlight text or when I open settings (for example going to file to open a folder), I was using another extension before that actually I was working correctly to show the background, unfortunately it stopped working so I gave a chance to this one, I hope it works with your answers, I've tried to uninstall the extension, reload it, put other images, etc. I thought it was the opacity that's why it's set to 1 but that doesn't make it more visible. It only works for light themes.

```json
  "background.enabled": true,
  "background.fullscreen": {
    "images": ["file://C:/Users/jsegu/OneDrive/Imágenes/wallpapers/galaxy.jpg"],
    "opacity": 1.0, // 0.85 ~ 0.95 recommended
    "size": "cover", // also css, `cover` to self-adaption (recommended)，or `contain`、`200px 200px`
    "position": "center", // alias to `background-position`, default `center`
    "interval": 0 // seconds of interval for carousel, default `0` to disabled.
  },
```
![background](https://github.com/shalldie/vscode-background/assets/97373782/800794f4-5895-4332-bbfd-f77614c8673a)

As you could appreciate on the last image only when I highlight text the background can be barely seen.

What settings should I deactivate or what should I do so it can be visible?

**Comment by shalldie** [comment]
Sorry for the slow response. I just came back from vacation.

It should be caused by opacity and cannot be set to 1.
Your image (starry sky image) is not displayed friendly enough in dark mode, which is caused by the current implementation of fullscreen image.
Currently, you need to set the opacity to 0.85~0.95 to see the image, and I will consider this issue later.
