### ISSUE TITLE
[Question] 是否仅在主窗口上支持

### ISSUE THREAD

**Issue by MiunaQwQ** [shalldie/vscode-background#452]
## Summary | 概述

很喜欢的插件。
但是我在打开新窗口时新窗口的背景仍为VSC的默认背景而非插件替换的背景图片，所以想问问是不是仅在主窗口上支持修改背景？

### Versions

- `OS(Win10 / Mac OSX / Linux)`:Windows 11 Pro for Workstations 24H2 26120.961
- `vscode`: V1.90.1

### Background Config | 插件的配置
```json
    "background.fullscreen": {
        "images": [
            "file:///N:\\GEmeFuGaQAAUKD9.jpg",
            "file:///N:\\364504.jpg"],
        "opacity": 0.91,
        "size": "cover",
        "position": "center",
        "interval": 60
    }
```

**Comment by shalldie** [comment]
你是说「拖动一个tab到空白区域，产生新窗口」是吗？

试了一下确实无法展示图像，该窗口较特殊。暂时没有计划给这个加上。
