### ISSUE TITLE
[Bug Report] Default background

### ISSUE THREAD

**Issue by pushline** [shalldie/vscode-background#455]
## Summary | 概述

I followed the tutorial and even tho i restarted my vscode it stills shows the default one (the anime girl)

### Versions

- `OS(Win10 / Mac OSX / Linux)`: Win10
- `vscode`: 1.19.1
![image](https://github.com/user-attachments/assets/2356f78c-69f5-458e-8d55-8811245d24fa)

### Background Config | 插件的配置

```json
{
    "background.enabled": true,
    "background.fullscreen": {
      "image": "https://i.imgur.com/JFK28VB.jpeg", 
      "opacity": 0.91, 
      "size": "cover",
      "position": "center", 
      "interval": 0 
    }
}
```

### Screenshots | 截图

https://imgur.com/a/LxS8cuU

**Comment by shalldie** [comment]
It's `images`, not `image`, see [fullscreen config](https://github.com/shalldie/vscode-background?tab=readme-ov-file#fullscreen-config)

You can try:

```json
{
    "background.enabled": true,
    "background.fullscreen": {
      "images": ["https://i.imgur.com/JFK28VB.jpeg"], 
      "opacity": 0.91, 
      "size": "cover",
      "position": "center", 
      "interval": 0 
    }
}
```

**Comment by pushline** [comment]
It worked, thanks.
