### ISSUE TITLE
[Bug Report] 最新的code-insider 1.94.0中，插件失效

### ISSUE THREAD

**Issue by median-dxz** [shalldie/vscode-background#459]
## Summary | 概述

如题

### Versions

- `OS(Win10 / Mac OSX / Linux)`: Win11
- `vscode`: 

```
版本: 1.94.0-insider (user setup)
提交: 6e9d8a281003211220a6732ec538a28c483ff78b
日期: 2024-09-11T05:04:03.124Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

### Background Config | 插件的配置

```json
  "background.enabled": true,
  "background.fullscreen": {
    "images": ["file:///E:/Resource/Custom/vsc-bg.jpg"],
    "opacity": 0.9,
    "size": "cover",
    "interval": 0
  },
  "background.useFront": false,
  "background.style": {
    // "background-position": "0% 0%",
    // "position": "fixed",
  },
```

### Expected Behaviors | 期望的行为

插件激活

### Screenshots | 截图

![image](https://github.com/user-attachments/assets/02e53eca-fb97-4810-96e8-a274e7381b7a)

### Additional Context | 其它信息

无

**Comment by shalldie** [comment]
多谢反馈，insider版本随时都可能变更，最终结果不一定会合入到stable。
会关注这个问题，直到 1.94 的 stable 发布。

**Comment by ringo360** [comment]
I have same issue on VSC-Insiders

**Comment by KiyoEAC** [comment]
刚刚更新vscode版本1.94stable后，插件已无法使用
![{DEA8935A-7240-4aa5-90D9-0CE30071E15D}](https://github.com/user-attachments/assets/29b75982-be44-44c5-93e6-8baba7dc0be2)
![{AFAF8D97-2612-48b6-8965-F2BE18915665}](https://github.com/user-attachments/assets/36ecacab-559d-463e-9b10-0a5628183427)
