### ISSUE TITLE
mac下默认图片不显示

### ISSUE THREAD

**Issue by Criya** [shalldie/vscode-background#46]

**Comment by shalldie** [comment]
这个需要有修改用户文件的权限。

**Comment by luchongkang** [comment]
修改哪个文件的权限？ @shalldie

**Comment by shalldie** [comment]
@Criya 
@luchongkang 

Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css

很不好意思，之前看到了这个但是忘记回了。。。

mac 下需要有上述文件的修改权限。

**Comment by luchongkang** [comment]
@shalldie 请问这个Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css文件是哪里呀？

**Comment by shalldie** [comment]
@luchongkang 
mac 下，右键 vscode ，选择显示包内容，然后照着上面的路径就可以找到该文件

**Comment by luchongkang** [comment]
@shalldie 我修改了，还是没有效果呀[http://ww1.sinaimg.cn/large/6af7296cgy1fjou3ogbpej20so02gt9b.jpg](url)

**Comment by luchongkang** [comment]
@shalldie 我修改了，还是没有效果呀
[截图地址](http://ww1.sinaimg.cn/large/6af7296cgy1fjou3ogbpej20so02gt9b.jpg)

**Comment by shalldie** [comment]
@luchongkang 

![image](https://user-images.githubusercontent.com/9987486/30578153-09c9f548-9d45-11e7-83fd-475d5d6b0fa3.png)

我是这么来添加权限的。手边没有mac，用的以前的图

**Comment by luchongkang** [comment]
@shalldie 好的。谢谢

**Comment by Criya** [comment]
@shalldie 我的机子里好像没workbench.main.css

**Comment by shalldie** [comment]
@Criya 
...... 怎么会。
这个是vscode程序依赖的一个css文件，位置在：
Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css

mac 下，右键 vscode ，选择显示包内容，就可以打开它的文件夹

**Comment by Criya** [comment]
@shalldie
<img width="309" alt="2017-09-20 20 29 04" src="https://user-images.githubusercontent.com/23690459/30643748-c0050c8c-9e42-11e7-8159-8eb50a6b6c62.png">
-_-!!我也不知道为什么没有

**Comment by shalldie** [comment]
@Criya 
啊，，，我建议这样：
1. 检查一下你的vscode版本，现在是 1.16.1
2. 再次确认一下路径，看看是不是所有的都匹配上了
:rofl:

**Comment by summer789** [comment]
已经设置了权限，还是无法显示背景

**Comment by Criya** [comment]
无效，放弃了。。

**Comment by MecDog** [comment]
@Criya @summer789  我也碰到同样的问题。
虽然给了权限，启动vscode时候,还是没有提示vscode遭到损坏的消息,我怀疑是插件没有去修改。然后我修改插件的图片样式保存，vscode先提示“扩展设置修改了，需要restart”,重启后在提示的“vscode损坏”，图片就出来了。

**Comment by woshixiaoqianbi** [comment]
@MecDog  大佬，你怎么修改插件的图片样式解决这个问题的啊

**Comment by pelaliu** [comment]
@woshixiaoqianbi  修改完权限之后将  background.style  这一段代码复制到右边“用户设置”中，然后重启vs code，之后会出现上条中所说的情况，之后就出来了，我的是这么出来的。

**Comment by pelaliu** [comment]
@woshixiaoqianbi 啊对我修改了其中的透明度

**Comment by JourneyL** [comment]
@shalldie  1.20 不好使啊

**Comment by shalldie** [comment]
我这 `1.20.1` 没有问题，请修改一下权限试试 :D

**Comment by treezhou05** [comment]
![image](https://user-images.githubusercontent.com/32838069/41840737-1569c312-7899-11e8-9089-e85eba4c617b.png)
设置后没反应呀，

**Comment by zuggs** [comment]
"background.customImages": ["\\Users\\aaaa\\Desktop\\ffaa\\bg.jpg"]
哪里配置错了？为什么不能用

**Comment by yzzting** [comment]
![image](https://user-images.githubusercontent.com/15907064/47897946-b066c100-deae-11e8-8872-5c5ce59ac088.png)
![image](https://user-images.githubusercontent.com/15907064/47897968-c5435480-deae-11e8-81a3-ec54550c2253.png)
![image](https://user-images.githubusercontent.com/15907064/47898028-0471a580-deaf-11e8-9836-b74aadbe40bb.png)

给足了权限还是这样....
卒...

**Comment by sigai** [comment]
写给后来的参考：
我用的eZIP解压的就会有这个问题， 然后我下载了旧的几个版本也是一样的问题，所以猜测是解压的问题。
所以用unzip命令解压出来的就是正常的了。
**unzip VSCode-darwin-stable.zip**
然后拖到应用程序文件夹
希望帮到后面的人。

**Comment by fanfanyir** [comment]
https://www.jianshu.com/p/b2e372a96271   实测好用
