### ISSUE TITLE
[Feature] Let Shuffle The Images

### ISSUE THREAD

**Issue by ericmp33** [shalldie/vscode-background#460]
I currently have this configuration for the plugin:
```json
"background.fullscreen": {
    "images": [
        "https://image1example.test",
        "https://image2example.test",
        "https://image3example.test",
        "https://image4example.test",
        "https://image5example.test",
    ],
    "interval": 600
    ...
},
```
Every time I launch a new VSCode window, it starts with the same image. I'd love the array of images to be shuffled somehow. In the example config I provided there is only 5 images, but in reality I have a lot more. The ones at the end never get shown.

Is it possible to add a new config, and shuffle the images array every time a new VSCode window launches?
```json
"shuffleImages": true
```

**Comment by shalldie** [comment]
There have been some similar suggestions that have been rejected.
But now it seems that it can bring some interesting experiences, and this feature may not have a high priority. I will keep this issue open.

**Comment by suiyun39** [comment]
Please refer to #456 for specific reasons. If you have good suggestions, welcome to participate in the discussion

**Comment by shalldie** [comment]
`v2.0.0` has released, just try it !
