### ISSUE TITLE
[Question] Is it normal for the text to still be covered by the image when setting the foreground to the background? Is there a way to avoid this?

### ISSUE THREAD

**Issue by SYREB** [shalldie/vscode-background#461]
## Summary | 概述

I have already searched [GitHub Issues](https://github.com/shalldie/vscode-background/issues), ...

### Versions

- `vscode`:
ver: 1.93.1 (user setup)
commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
datatime: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22000

### Background Config | 插件的配置

```json
{
    "background.enabled": true,
    "background.style":{
        "background-position": "100% 100%",
        "background-size": "auto",
        "opacity": 1
    },
    "background.styles":[
        {},
        {},
        {},
    ],
    "background.customImages":[],
    "background.interval":0,
    "background.fullscreen": {
        "images": ["file:///C:/Users/REB_S/OneDrive/がぞう/GYGGxbkb0AAhUaQ.jpg"],
        "opacity": 0.55,
        "size": "cover",
        "position": "center",
        "interval": 0,
        "background.useFront": false,
    },
}
```

### Additional Context | 其它信息

![image](https://github.com/user-attachments/assets/7a413280-f7c3-4fdf-ab68-a4dc81b44684)

**Comment by shalldie** [comment]
`fullscreen` mode has no config `useFront`, the useFront config is design to the `code area` mode.
