### ISSUE TITLE
Fail to initialize on linux, vscode installed as a snap

### ISSUE THREAD

**Issue by FrostKiwi** [shalldie/vscode-background#464]
## Summary | 概述

Installed VSCode on latest Ubuntu via the Package manager `Discover`, which installs VSCode as a `snap`. All extensions work, except `background`, which errors out due to not being able to write to the sandboxed environment of the snap. It errors out with 

```
EROFS: read-only file system, access '/snap/code/169/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css'
```
Performing the action with root, results in nothing happening, but opening a new window shows the following in the extension host output:
```
2024-10-02 00:36:43.013 [error] Activating extension shalldie.background failed due to an error:
2024-10-02 00:36:43.013 [error] Error: EEXIST: file already exists, open '/home/bamboo/.vscode/extensions/shalldie.background-1.2.13/shalldie.background.lock'
```
However, there actually is no such lock file, upon checking.

### Versions

![image](https://github.com/user-attachments/assets/092d6bdb-6a2d-4e5d-bedf-c03ae178c39f)

### Background Config | 插件的配置

default

### Screenshots | 截图

![image](https://github.com/user-attachments/assets/94027019-bed6-4438-8677-f4d6d9fe164e)

### Additional Context | 其它信息

Installed from the Ubuntu App

**Comment by suiyun39** [comment]
Please ref #382 , This is a known issue that cannot be resolved.

**Comment by FrostKiwi** [comment]
Yes, I expected the read only sandboxing of the snap to be the issue. Just wondered if there is something that can be done code wise. If not, then I guess I will also install vscode via .deb packages.

I guess this can be closed as won't fix?
