### ISSUE TITLE
Background image not showing

### ISSUE THREAD

**Issue by AmanBisht02** [shalldie/vscode-background#467]
Type: <b>Bug</b>

Background was working before updating vs code now background image not showing

Extension version: 1.2.13
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by 13RTK** [comment]
I had the same problem on Mac, It worked before

**Comment by Doming3000** [comment]
Same problem here :/

**Comment by FcoAgZa** [comment]
Rollback to [1.93](https://code.visualstudio.com/updates/v1_93), that's it

**Comment by JIMyyf** [comment]
While I can roll my code version to 1.93, but I want to update my code to the latest version.

**Comment by shalldie** [comment]
v1.2.15 has been released.
