### ISSUE TITLE
[Feature] add restart background button and key combination

### ISSUE THREAD

**Issue by JustKemForFun** [shalldie/vscode-background#468]
I need you to add a feature that is a button to restart VSCode and re-display the image when updating a new version of VSCode. This makes me quite annoyed because every time I update vscode, the image is lost but it doesn't pop up a notification for me to restart, so please create a key combination to restart the background on VSCode. Thanks!

**Comment by shalldie** [comment]
![image](https://github.com/user-attachments/assets/25a26a97-e6ef-4f11-8876-8e1f817e3b83)

Strange, it should be auto pop up a notification when vscode update.

I add a statusbar button in v1.2.16, you can:
1. click the statusbar on the right bottom.
2. chose the install command.
3. It'll reinstall the background and show confirm to reload.
