### ISSUE TITLE
怎么自定义图片的透明度啊？还有就是我添加了自己本地图片但是怎么可以达到编辑框内是铺满状态

### ISSUE THREAD

**Issue by wkkvow** [shalldie/vscode-background#47]
图片的透明度怎么来设置啊？我添加自己图片后它没达到铺满状态，这是我的图片太小的原因还是设置的问题？

**Comment by shalldie** [comment]
刚发了个版本，ver.1.1.12，已经把透明度功能加上了
在 settings.json 中添加：
`"background.style":{ "opacity":0.6 }`
就可以设置透明度了。
如果想铺满，可以设置背景图大小，比如 background-size

**Comment by wkkvow** [comment]
好的，谢谢啊

发自我的 iPhone

在 2017年6月27日，下午1:01，谢爽 <notifications@github.com<mailto:notifications@github.com>> 写道：


刚发了个版本，ver.1.1.12，已经把透明度功能加上了
在 settings.json 中添加：
"background.style":{ "opacity":0.6 }
就可以设置透明度了。
如果想铺满，可以设置背景图大小，比如 background-size
