### ISSUE TITLE
[Feature] 给每个项目添加不同的图片

### ISSUE THREAD

**Issue by lt123345** [shalldie/vscode-background#471]
我希望不同项目能有不同的项目背景图，所以我尝试在Workspace的setting.json里添加配置，然后Reload Window。但是这样会覆盖全局的图片，因为其他项目Reload之后也会变成刚刚Workspace里的背景图片。

希望能支持Workspace settings.json里配置的时候，优先用Workspace的。Workspace没有的话，就用User settings.json里的。

**Comment by shalldie** [comment]
插件是通过修改vscode文件运作的，整个修改范围是「全局」。
目前的思路和方案，还做不到workspace的粒度。

**Comment by lt123345** [comment]
好的，Happy to know that!
