### ISSUE TITLE
about background position

### ISSUE THREAD

**Issue by ddxglin** [shalldie/vscode-background#472]
## Summary | 概述

I have already searched [GitHub Issues](https://github.com/shalldie/vscode-background/issues), but i don't know how to change the position about image,i just find 'center','right top','bottom','absolute'...i want to let camera capture the top of my image!please tell my what to do,thanks bigguy ♥♥♥

### Versions

- `OS(Win11 / Mac OSX / Linux)`:
- `vscode`:

**Comment by shalldie** [comment]
What is `i want to let camera capture the top of my image` ?

Would you like to upload screenshots to assist in explanation ♥

**Comment by ddxglin** [comment]
![image](https://github.com/user-attachments/assets/7e010458-6312-4999-adac-48573b5729b4)

Just like this!(i cropped the picture afterwards)
Before, it was like this
![image](https://github.com/user-attachments/assets/95a3aeae-101f-4455-aa5f-852cd4d6e03d)
i just want to know how to change the position

**Comment by ddxglin** [comment]
humm,change it by code

**Comment by ddxglin** [comment]
thanks bro.in the beginning,I tried to change it under 'background-fullscreen ', you mean to write yourself another line 'background-position', like............ em,SAME as adjusting STYLE?!☺️

**Comment by shalldie** [comment]
Here's the [Doc](https://github.com/shalldie/vscode-background?tab=readme-ov-file#default-config).

I think you're not using the `fullscreen` mode, so you can edit the `background.style` to adjust the `editor` section.
`fullscreen` also can edit the `position` which alias to `background-position`.

Upload your image here, let me see which style is better.

**Comment by suiyun39** [comment]
> thanks bro.in the beginning,I tried to change it under 'background-fullscreen ', you mean to write yourself another line 'background-position', like............ em,SAME as adjusting STYLE?!☺️

Yes, you are right. In fact, the way the plugin works is to modify the vscode style file.

**Comment by ddxglin** [comment]
> Here's the [Doc](https://github.com/shalldie/vscode-background?tab=readme-ov-file#default-config).
> 
> I think you're not using the `fullscreen` mode, so you can edit the `background.style` to adjust the `editor` section.
> `fullscreen` also can edit the `position` which alias to `background-position`.
> 
> Upload your image here, let me see which style is better.
dank,here is.![Image_1730023733733.jpg](https://github.com/user-attachments/assets/0745f393-0ca0-4798-8f52-e2537cd0c3a0)

**Comment by shalldie** [comment]
![image](https://github.com/user-attachments/assets/16500979-4e6c-41c3-9d68-b6e805974cdb)

@ddxglin 
I think `fullscreen` is better, here's my config:

```json
{
  "background.fullscreen": {
    "images": [
      "https://private-user-images.githubusercontent.com/111481180/380485983-0745f393-0ca0-4798-8f52-e2537cd0c3a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODQ2NjMsIm5iZiI6MTczMDA4NDM2MywicGF0aCI6Ii8xMTE0ODExODAvMzgwNDg1OTgzLTA3NDVmMzkzLTBjYTAtNDc5OC04ZjUyLWUyNTM3Y2QwYzNhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwMjU5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTRhMDYwZDE2OWQwOTk5ODQ0YWQ3ZWEyZThjYjNkZTQ4MTcyNDk1MjE1MTA5NDZiYmNkMTBlM2RjNTJlZmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jh2MfYq81BCvCpoB-ZfqoxJWxPCiLG2CvTdIdaa-08k"
    ],
    "opacity": 0.91,
    "size": "cover",
    "position": "center",
    "interval": 0,
    "random": false
  }
}
```

**Comment by ddxglin** [comment]
Thanks for your help, in fact, I just started learning c recently and there are a lot of things I don't understand :). This part sounds a lot like web design.
