### ISSUE TITLE
[Bug Report] When `useFront` is false, multiple images are stacked with each other

### ISSUE THREAD

**Issue by Marsman1996** [shalldie/vscode-background#474]
## Summary | 概述

When `useFront` is false, multiple images are stacked with each other.

### Versions

- `OS(Win10 / Mac OSX / Linux)`: Mac OS 15.0.1
- `vscode`: 1.94.2 (Universal)

### Background Config | 插件的配置

```json
{
   "background.editor": {
        "useFront": false,
        "images": [
            "file:///Users/marsmac/Pictures/vscode/40583669-d6189844-61c5-11e8-89e3-c52ad153da09.png",
            "file:///Users/marsmac/Pictures/vscode/40583670-d6478c9e-61c5-11e8-9551-6b55eacc7b8d.png",
            "file:///Users/marsmac/Pictures/vscode/40583671-d676c6e4-61c5-11e8-94cb-34ec4a12fa01.png"
        ],
    }
}
```

### Expected Behaviors | 期望的行为

The three pictures show in three panes separately like `useFront` is true.

### Screenshots | 截图

When `useFront` is false:
<img width="1577" alt="image" src="https://github.com/user-attachments/assets/c5c6ca80-fdd1-40f9-856e-f461908d80d3">

And when `useFront` is true:
<img width="1586" alt="image" src="https://github.com/user-attachments/assets/c4f012a4-e396-4bee-8960-93b9a0793794">

**Comment by shalldie** [comment]
I was unable to reproduce this issue.

There is a guess, did you also use another background extension at the same time? 
Which applied an effect similar to `useFront: true`.

1. When `useFront: true`, the background overrides it's configuration.
2. When `useFront: false`, both the background and it exist simultaneously.

This can cause the phenomenon you mentioned.

**Comment by Marsman1996** [comment]
Hi, thank you for your quick reply!

However, I disable all the other extensions here and set `useFront` to false and the problem still exists 🤔

<img width="1869" alt="image" src="https://github.com/user-attachments/assets/915f2f46-f2f9-44ab-9b0d-a3bab416d4d8">

Maybe I will just keep `useFront` as true.

**Comment by Marsman1996** [comment]
In my screenshot, it seems vscode-background treats `Minimap` as a pane and also show pic in it?

**Comment by shalldie** [comment]
> However, I disable all the other extensions here and set `useFront` to false and the problem still exists

These types of plugins are generally not effective if they are only disabled.
Usually, specialized uninstallation methods are provided.

I have these suggestions:

1. It is best to find the corresponding plugin and uninstall it according to its documentation.
2. Or reinstalling VSCode after disabling can solve all problems
3. My guess: Your `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css` should have been modified. You can open it to see if there is a space at the bottom of the file that is enclosed by a comment.



> In my screenshot, it seems vscode-background treats `Minimap` as a pane and also show pic in it?

No, `vscode-background` just would not change the opacity of minimap now.
I open an issue https://github.com/shalldie/vscode-background/issues/475 , you can find the effect here.

**Comment by shalldie** [comment]
If you want to save time, try this way, to find `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css`

Open this file and check if there are any strange places at the bottom, for example sth like this:

```css
/*css-background-start*/
...
/*css-background-end*/
```

Delete this section, save the file and restart VSCode 😺

**Comment by Marsman1996** [comment]
Thank you for your advise!
