### ISSUE TITLE
[Bug Report] image obscures screen and code

### ISSUE THREAD

**Issue by JustKemForFun** [shalldie/vscode-background#477]
## Summary | 概述

today when i entered my vscode it was normal until i saw the notification of the extension restart popup then i restarted and the error occurred as shown in the image how to fix it when i have restarted vscode many times but still not working.

### Versions

- `OS(Win10 / Mac OSX / Linux)`: Win10
- `vscode`: new latest

### Expected Behaviors | 期望的行为

fix bug success

### Screenshots | 截图

![image](https://github.com/user-attachments/assets/08836985-4586-4fa1-9dd4-ea76c85711a4)

**Comment by shalldie** [comment]
### Or try this to fix it

![image](https://github.com/user-attachments/assets/5048b080-b83c-405a-978c-51210bf76317)

1. click this on the right-bottom corner.

![image](https://github.com/user-attachments/assets/ffa995b1-1780-47da-9c8d-a3cddbce131d)

2. chose this to disable

3. clear your config

![image](https://github.com/user-attachments/assets/c46d5b69-36c5-4b53-95c5-9fbdb8766fdf)

4. enable again

5. change your config, it should be ok.

**Comment by JustKemForFun** [comment]
thank you. 
![image](https://github.com/user-attachments/assets/f168e79d-870e-4d34-8c41-e0c4b157af62)
