### ISSUE TITLE
[Feature] Add translation [Help Wanted!]

### ISSUE THREAD

**Issue by shalldie** [shalldie/vscode-background#479]
# Translation

- After upgrading to v2, there are several translation tasks left over. I hope some friends can pr them ~
- 升级到v2之后，有几项翻译工作遗留，希望有朋友能pr下 ~

## Work Content

* [ ] 日本語
    - [ ] `package.nls.ja.json`
    - [ ] `README.ja-JP.md`
    - [x] `l10n/bundle.l10n.ja.json`
* <del>[ ] Portugues</del>
    - Because I am not familiar with Portuguese and it is difficult to find maintainers, I plan to delete this section.
    - 因为我不了解葡萄牙语而且很难找到维护者，因此打算删除这部分。
    - <del>[ ] `package.nls.pt.json`</del>
    - <del>[ ] `README.pt-BR.md`</del>
    - <del>[ ] `l10n/bundle.l10n.pt.json`</del>

## TKS

If you'd like to PR, thanks a lot.
如果你有意愿 PR，感激不尽。
「PR」をしたいなら、ありがとうございます。

**Comment by shim4stat** [comment]
@Octopus058, have you found someone to work on the Japanese translation? If not, I'd like to take on the task.

**Comment by Octopus058** [comment]
sure, i haven't find one so you can feel free to do it. xD

**Comment by shim4stat** [comment]
I see, thank you!
