### ISSUE TITLE
mac不生效啊，chmod777了

### ISSUE THREAD

**Issue by wangxufire** [shalldie/vscode-background#48]

**Comment by shalldie** [comment]
确定对这个文件有 【读／写】 权限哟
Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.css

**Comment by radicalviva** [comment]
@shalldie  解决下这个问题啊~~ 我这边mac也不行。

**Comment by wangxufire** [comment]
@radicalviva 我下载源码debug搞了搞可以了，不过效果不太好，适合部分图片不适合一张图片覆盖所有区域

**Comment by radicalviva** [comment]
@wangxufire 恩，能详细点吗。。

**Comment by shalldie** [comment]
@radicalviva 
确定对这个文件有 【读／写】 权限哟
Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.css
这个路径上vscode包的路径，【右键文件】-【显示简介】，在下方可以查看和设置该文件的读写权限。

**Comment by radicalviva** [comment]
@shalldie 在 mac 上，我没找到这个路径额。。

**Comment by shalldie** [comment]
@radicalviva 
在vscode安装目录，右键vscode的图标，然后选择【显示包内容】，然后按照上面的路径  0.0

**Comment by radicalviva** [comment]
@shalldie 我看了下，我一直有 读与写 的权限额。发现并没什么用。

**Comment by shalldie** [comment]
@radicalviva 
everyone  也加上试试

**Comment by radicalviva** [comment]
@shalldie  已加，是否是我的配置代码写错了。。
```
{
    "background.useDefault": false,
    "background.customImages": [
        "https://b.yzcdn.cn/v2/image/intro/new_index/index_case_2_1111.png"
    ],
    "workbench.colorTheme": "One Dark Pro",
    "workbench.iconTheme": "vs-seti"
}
```

**Comment by shalldie** [comment]
@radicalviva 
加我QQ 吧，394229785
