### ISSUE TITLE
「全屏」会改变所有东西的透明度

### ISSUE THREAD

**Issue by JiaY19** [shalldie/vscode-background#481]
在使用全屏图片时，透明度会使所有东西变得透明，包括编辑界面的文字，侧边栏的文字。

**Comment by shalldie** [comment]
因为当前「全屏」的实现方式导致。
重新看了这部分，有一些更好的实现方式，可以避免上述问题。

但历史配置如何兼容需要整体考虑下，这次fix会跟随其它feature一起发版，时间上稍晚一些。

**Comment by shalldie** [comment]
Fixed in `v2.0.2`

**Comment by aldlss** [comment]
更新完总感觉跟之前不太一样，原来是这里改了

**Comment by shalldie** [comment]
> 我是新手，麻了

hh 别急，可以新开一个issue描述下遇到的问题
