### ISSUE TITLE
[Bug Report] 插件提示在linux下不显示为中文

### ISSUE THREAD

**Issue by hbcraft** [shalldie/vscode-background#485]
## Summary | 概述

插件提示在linux下不显示为中文

![image](https://github.com/user-attachments/assets/37cf1759-3ae7-4acc-8bcd-7d238ce09c13)

在输出面板的扩展宿主页出现报错

```log
2024-10-31 11:43:51.152 [error] Failed to load translations for shalldie.background from file:///home/xx/.vscode/extensions/shalldie.background-2.0.1/l10n/bundle.l10n.zh-cn.json: 无法读取文件'/home/xx/.vscode/extensions/shalldie.background-2.0.1/l10n/bundle.l10n.zh-cn.json' (Error: 无法解析不存在的文件 '/home/xx/.vscode/extensions/shalldie.background-2.0.1/l10n/bundle.l10n.zh-cn.json')
```

### Versions

- `OS(Win10 / Mac OSX / Linux)`: `Linux`
- `vscode`: `1.95.0`

### Background Config | 插件的配置

```json
{
  "background.enabled": true,
  "background.editor": {
    "useFront": true,
    "style": {
      "background-position": "100% 100%",
      "background-size": "auto",
      "opacity": 0.6
    },
    "styles": [
      {},
      {},
      {}
    ],
    "images": [
    "file:///home/xx/Pictures/惠惠2.gif"
    ],
    "interval": 0,
    "random": false
  }
}
```

### Expected Behaviors | 期望的行为

插件提示正常显示中文，在输出面板的扩展宿主页无报错

### Screenshots | 截图

![image](https://github.com/user-attachments/assets/37cf1759-3ae7-4acc-8bcd-7d238ce09c13)

### Additional Context | 其它信息

猜测原因为windows下读取文件不区分大小写，linux/mac 下区分大小写，应该将 `bundle.l10n.zh-CN.json` 更名为 `bundle.l10n.zh-cn.json`

**Comment by shalldie** [comment]
有在linux测试吗？
我在mac下测过ok，按理说 mac/linux 应该一致才对

**Comment by hbcraft** [comment]
> 有在linux测试吗？ 我在mac下测过ok，按理说 mac/linux 应该一致才对

我现在用的就是linux

```
版本: 1.95.0
提交: 912bb683695358a54ae0c670461738984cbb5b95
日期: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-45-generic
```

**Comment by shalldie** [comment]
嗯我的意思文件名改成小写，linux下就正常了是么

**Comment by hbcraft** [comment]
> 嗯我的意思文件名改成小写，linux下就正常了是么

是的，我手动在插件目录改了文件名试的

**Comment by shalldie** [comment]
好的，多谢 反馈+pr

**Comment by shalldie** [comment]
问一下你用的是 linux哪个发行版呢？ 以及版本号

**Comment by hbcraft** [comment]
> 问一下你用的是 linux哪个发行版呢？ 以及版本号 @hbcraft

`Ubuntu 24.04.1 LTS`

![image](https://github.com/user-attachments/assets/261fef54-9be9-4c82-9c17-403449dd19a0)
