### ISSUE TITLE
卸载后，还有背景图，

### ISSUE THREAD

**Issue by ycjcl868** [shalldie/vscode-background#49]
![image](https://cloud.githubusercontent.com/assets/13595509/26586930/5e5d7cb6-4583-11e7-8f78-01083d6c85dd.png)

**Comment by shalldie** [comment]
> Q:How to uninstall the extension?
> Q:怎么卸载这个插件？
> 
> A:Set the config  {"background.enabled": false}  in settings.json,then uninstall the plugin.
> A:在 settings.json 中设置 {"background.enabled": false} ，然后再删除插件。如果直接删除插件会有遗留，就需要重装vscode了。

因为插件是修改了系统文件，所以需要按照 readme 中描述的方式来卸载哈。
可以再安装一次background然后设置上述值，或者重装vscode。

**Comment by ycjcl868** [comment]
这个插件太黑客了
