### ISSUE TITLE
疑似新版本Background插件获取权限造成的vscode软件字体错位

### ISSUE THREAD

**Issue by Royikiss** [shalldie/vscode-background#490]
### Versions

- `vscode`: 版本:  1.95.1
- `Electron`: 32.2.1
- `ElectronBuildId`: 10427718
- `Chromium` : 128.0.6613.186
- `Node.js` : 20.18.0
- `V8` : 12.8.374.38-electron.0
- `OS`: Linux x64 6.9.7-arch1-1

### Background Config | 插件的配置

```json
{
  "background.editor": {

    "useFront": true,
    "style": {
      "background-position": "100% 100%",
      "background-size": "auto",
      "opacity": 0.6
    },
    "styles": [
      {},
      {},
      {}
    ],
    "images": [
      "https://user-images.githubusercontent.com/9987486/40583669-d6189844-61c5-11e8-89e3-c52ad153da09.png",
      "https://user-images.githubusercontent.com/9987486/40583670-d6478c9e-61c5-11e8-9551-6b55eacc7b8d.png",
      "https://user-images.githubusercontent.com/9987486/40583671-d676c6e4-61c5-11e8-94cb-34ec4a12fa01.png"
    ],
    "interval": 0,
    "random": false
  },
}
```

### Expected Behaviors | 期望的行为

回复到老版本默认壁纸效果，其他不变

### Problem description and reproduction steps | 问题描述与复现步骤

在我的本地机环境下，想要使用该插件需要获取部分root权限，如图：

![图片](https://github.com/user-attachments/assets/bb250ff0-4600-4a6a-a85b-a0257a5c8044)

信息如下：
`EACCES: permission denied, access '/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js'`

点击 `Retry with Admin/Sudo` 之后，需要输入root密码：

![图片](https://github.com/user-attachments/assets/d477b607-9e99-4a85-965f-107392e272fd)

输入之后重启vscode:

![图片](https://github.com/user-attachments/assets/51e7f67b-4eb0-45c7-b01f-eaedc6201bed)
![图片](https://github.com/user-attachments/assets/1e1162a8-fa6a-430d-908f-783e8ef96290)

### Additional Context | 其它信息

我发现似乎这些字体以某种奇怪的方式错位了，导致显示错误。每个按钮的功能与其所显示的字体没有任何关系......

变成如上的情况之后，我是卸载掉vscode重新安装才恢复正常的......

**Comment by shalldie** [comment]
同 #487

你能稳定复现吗？
我使用虚拟机安装了几个系统都尝试未果 😂

系统、架构、vscode 安装方式，麻烦详细表述下。我再试试能否复现。

**Comment by Royikiss** [comment]
@shalldie 

我尝试了几次，在我的环境下按照我之前说的方式可以稳定复现。

补充一下其他的信息：

- `fastfetch 捕捉` :
![图片](https://github.com/user-attachments/assets/b09beef6-dbfa-437c-9b2b-991542d78f94)

安装 vscode 的 方式：

``` shell
yay -S visual-studio-code-bin
```

值得一提的是，在进行 `background` 插件的更新之前，我进行了系统的更新（sudo pacman -Syu），出现了一些冲突，并且与vscode相关，相关信息我不能再复现了，但是我保留了当时的部分冲突信息：

```txt
/usr/lib/debug/.build-id/20/97e5c14ea48a1c15644af3fa6bc386f1130303 同时存在于 'electron32-bin-debug' 和 'visual-studio-code-bin-debug'
/usr/lib/debug/.build-id/20/97e5c14ea48a1c15644af3fa6bc386f1130303.debug 同时存在于 'electron32-bin-debug' 和 'visual-studio-code-bin-debug'
/usr/lib/debug/.build-id/31/ea968e0335b1c7839fd4ddc6570ce201dc3c08 同时存在于 'electron32-bin-debug' 和 'visual-studio-code-bin-debug'
/usr/lib/debug/.build-id/31/ea968e0335b1c7839fd4ddc6570ce201dc3c08.debug 同时存在于 'electron32-bin-debug' 和 'visual-studio-code-bin-debug'
/usr/lib/debug/.build-id/48/cafa1bd1eeeb500a3cee7cec9603f2440e9ce3 同时存在于 'electron32-bin-debug' 和 'visual-studio-code-bin-debug'
/usr/lib/debug/.build-id/48/cafa1bd1eeeb500a3cee7cec9603f2440e9ce3.debug 同时存在于 'electron32-bin-debug' 和 'visual-studio-code-bin-debug'
/usr/lib/debug/.build-id/5c/a551d83e15add4be7632cb656cb42302b494fd 同时存在于 'electron32-bin-debug' 和 'visual-studio-code-bin-debug'
/usr/lib/debug/.build-id/5c/a551d83e15add4be7632cb656cb42302b494fd.debug 同时存在于 'electron32-bin-debug' 和 'visual-studio-code-bin-debug'
发生错误，没有软件包被更新。
 -> 安装时出错:  [/home/royi/.cache/yay/linuxqq-appimage/linuxqq-appimage-3.2.13_2024_11_4-1-x86_64.pkg.tar.zst /home/royi/.cache/yay/electerm-bin/electerm-bin-1.40.20-1-x86_64.pkg.tar.zst /home/royi/.cache/yay/electerm-bin/electerm-bin-debug-1.40.20-1-x86_64.pkg.tar.zst /home/royi/.cache/yay/microsoft-edge-stable-bin/microsoft-edge-stable-bin-130.0.2849.68-1-x86_64.pkg.tar.zst /home/royi/.cache/yay/electron32-bin/electron32-bin-32.2.2-1-x86_64.pkg.tar.zst /home/royi/.cache/yay/electron32-bin/electron32-bin-debug-32.2.2-1-x86_64.pkg.tar.zst /home/royi/.cache/yay/dingtalk-bin/dingtalk-bin-7.6.15.4102301-2-x86_64.pkg.tar.zst /home/royi/.cache/yay/visual-studio-code-bin/visual-studio-code-bin-1.95.1-1-x86_64.pkg.tar.zst /home/royi/.cache/yay/visual-studio-code-bin/visual-studio-code-bin-debug-1.95.1-1-x86_64.pkg.tar.zst] - exit status 1
```

关于此的修复方式我尝试移除了vscode，并重新安装：

 - 清空缓存包和一些缓存信息
 - 删除vscode和相关依赖
 - 重新下载

```shell
yay -Sc
yay -Rns visual-studio-code-bin
yay -S visual-studio-code-bin
```

修复上面的问题之后，我成功的更新了 `vscode` , 最后就是在 `vscode` 中 更新了 background 插件，后续的操作和我之前描述的一样。不知道是否能够提供帮助，这个bug是因为我更新 background 插件之后出现的，只是疑似是该插件造成的 bug，不知是否是和我本地机器的环境有关。

**Comment by shalldie** [comment]
好的，有类似的情况，也是存在于 archlinux 中。我会想办法找个环境试试

**Comment by feipiao594** [comment]
gentoo 也遇到了如上的情况
fastfetch信息如下
![图片](https://github.com/user-attachments/assets/6508b8fd-618f-4886-85f1-e9d31ee12c15)
复现方式如上一致，获取部分文件root权限后导致系统文字部分资源错乱
vscode: 版本: 1.95.1

**Comment by feipiao594** [comment]
顺带一提，注意到 aur 已经更新 vscode 1.95.2，但由于 gentoo tree 还未更新，且我暂时没有一个 archlinux 的环境，我不知道新版本(1.95.2)下的 vscode 是否仍然存在该问题

**Comment by shalldie** [comment]
> 顺带一提，注意到 aur 已经更新 vscode 1.95.2，但由于 gentoo tree 还未更新，且我暂时没有一个 archlinux 的环境，我不知道新版本(1.95.2)下的 vscode 是否仍然存在该问题

archlinux可太难装了，，，
不知道是否虚拟机的问题，我尝试了 ubuntu，Fedora，manjaro 均未能复现该问题。

暂时 hang 住了

**Comment by feipiao594** [comment]
> > 顺带一提，注意到 aur 已经更新 vscode 1.95.2，但由于 gentoo tree 还未更新，且我暂时没有一个 archlinux 的环境，我不知道新版本(1.95.2)下的 vscode 是否仍然存在该问题
> 
> archlinux可太难装了，，， 不知道是否虚拟机的问题，我尝试了 ubuntu，Fedora，manjaro 均未能复现该问题。
> 
> 暂时 hang 住了

awa，原谅我看到 “archlinux 太难装了” 忍不住笑出了声，，，
也许你应该使用 archinstall 快速搭建一个可以使用的环境
另外，我想起在早些时候，即使给出 root 权限也不会引发问题，最近我的系统进行了一次大更新，由于编译时间过长我没注意 vscode 的更新，可能在这个过程中由于更新导致了这样的问题
我将尝试拉取整个仓库进行调试，看看在调试环境下能不能给出更多的错误信息

**Comment by shalldie** [comment]
@feipiao594 
纯命令行、archinstall 都尝试过，这是门玄学 😂😂 
总能碰到奇奇怪怪的问题，，，最后选择了 manjaro 的两个发行版测试

> 我将尝试拉取整个仓库进行调试，看看在调试环境下能不能给出更多的错误信息

非常感谢，目前觉得问题出在这里：https://github.com/shalldie/vscode-background/issues/487#issuecomment-2458027258

周末时候我也会拉上能复现的网友一起瞅瞅

**Comment by feipiao594** [comment]
有一点进展了，似乎只要删除一遍 backup 并且重启扩展就不会触发这个问题了，可惜的是我只备份了 js 却没有备份我的 backup 文件，因此我现在貌似已经无法复现这个问题了 QAQ
我怀疑是因为更新版本后的 vscode 改动了 linux 端的  `workbench.desktop.main.js` ？而插件保留了旧版本的`workbench.desktop.main.js.background-backup` 经过一些操作后替换了原本有的正常的  `workbench.desktop.main.js`？
重装有效的原因可能是直接覆盖了 `workbench.desktop.main.js`，但没有覆盖 `workbench.desktop.main.js.background-backup` ？
我还没有来得及仔细看代码的逻辑，上面这只是基于我简单操作测试一下文件，发现删除 backup 文件有效的一些猜测

**Comment by shalldie** [comment]
vscode的更新，会把整个包全都替换掉，不会存在留存旧 backup 的情况

**Comment by feipiao594** [comment]
> vscode的更新，会把整个包全都替换掉，不会存在留存旧 backup 的情况

真的么，我不是很清楚，感觉有待验证，因为我 reinstall 时确实没有删除 backup

**Comment by shalldie** [comment]
@feipiao594
应该不是一码事，你的 reinstall 类似增量文件覆盖
vscode 的更新，类似 remove + install

**Comment by feipiao594** [comment]
> @feipiao594 应该不是一码事，你的 reinstall 类似增量文件覆盖 vscode 的更新，类似 remove + install

正巧今天早上起来滚包时发现 gentoo 官方源更新了 vscode，我测试了一下

**更新前**
![图片](https://github.com/user-attachments/assets/4b73f3db-3266-42a0-95f1-a1255d1a45ec)

注意这次我备份了 backup 到我本地的 ~/Workplace/temp_test_workbench/.

**更新后**
![图片](https://github.com/user-attachments/assets/31786382-37b5-454b-8110-fa10f8000cd7)

**使用 diff 判断两个文件是否相同**
![图片](https://github.com/user-attachments/assets/68d2c13d-8329-4e82-9f60-db639e323415)
没有输出说明确实没有改变

看起来至少在 gentoo 的包管理 portage 下，并不会像你说的 remove + install ，也许这就是问题的根源了

**Comment by shalldie** [comment]
@feipiao594 

啊那看来某些发行版中通过包管理器 upgrade，是直接文件覆盖的方式。跟 vscode 自身的更新功能不一样。
会造成旧版本的backup遗留，新版本vscode使用旧backup肯定会有问题。

那么，出现该问题的场景就是：

- vscode + background, works well.
- vscode upgrade，通过包管理器
- 出现问题
- 后续的重装如果都没有先进行 remove，都会出现问题

**Comment by feipiao594** [comment]
@shalldie 
看起来是这样的逻辑🎉，
也许需要其他能够复现该问题的网友进一步尝试？我因为我无法再次复现只能研究至此了 😇

**Comment by shalldie** [comment]
@feipiao594 已经帮到我很多了，多谢

**Comment by Zylsjsp** [comment]
已经排查到了问题 常见包管理器 至少pacman和portage都是按照文件列表先全部移除再安装更新 这个时候插件留下的backup文件不会被清除 一旦新版vscode对js进行了更新 过期的backup就会导致还原到上一个版本的js 导致文件损坏

**Comment by shalldie** [comment]
Fixed in `v2.0.2`
