### ISSUE TITLE
[Bug Report] mac M1 Pro ：vscode 和 Background 都更新到最新版本后插件无法正常使用并报错

### ISSUE THREAD

**Issue by imleeou** [shalldie/vscode-background#491]
## Summary | 概述

我今天一起更新了vscode 和 Background 插件到最新版本，当我重启vscode后，发现vscode无法正常打开，重启vscode重启电脑均无效，于是我从vscode下载了最新的vscode包，版本如下。
安装最新版本vscode包后，Background插件无法正常使用，提示保存如下文【Additional Context 】
我尝试切换Background版本，v2.0.1、v2.0.0、v1.2.16都尝试了，都还是报如下错误
我目前不清楚是vscode的bug还是Background的bug

报错信息见下方

### Versions

- `OS(Win10 / Mac OSX / Linux)`: macOS M1 PRO 14.6.1 
- `vscode`: 1.95.2

### Background Config | 插件的配置

```json
{
    "background.enabled": true,
	"background.fullscreen": {
		"images": ["https://oss.leeou.cc/vscode-bg.jpg"],
		"opacity": 0.96,
		"size": "cover",
		"position": "center",
		"interval": 0
	},}
```

### Expected Behaviors | 期望的行为

希望可以正常使用

### Screenshots | 截图
![image](https://github.com/user-attachments/assets/8dcbddaf-2747-495c-bc3a-2846cfaa833d)

![image](https://github.com/user-attachments/assets/03d92262-8d79-4227-9378-0d8079432dcd)

### Additional Context | 其它信息

Command failed: mv -f "/var/folders/jj/b6k27v9s6f91lv31s27s630w0000gn/T/vscode-background-bc216212-8f46-4443-9e63-99a27083385e.css" "/private/var/folders/jj/b6k27v9s6f91lv31s27s630w0000gn/T/AppTranslocation/6B7FEB92-9A5A-43B8-A92B-E7564794011F/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css" mv: rename /var/folders/jj/b6k27v9s6f91lv31s27s630w0000gn/T/vscode-background-bc216212-8f46-4443-9e63-99a27083385e.css to /private/var/folders/jj/b6k27v9s6f91lv31s27s630w0000gn/T/AppTranslocation/6B7FEB92-9A5A-43B8-A92B-E7564794011F/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css: Read-only file system

**Comment by shalldie** [comment]
现在像是在「下载」目录，需要拖到「应用」目录。参考[常见问题](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.zh-CN.md#read-only-file-system---%E5%90%84%E7%A7%8D%E6%97%A0%E6%9D%83%E9%99%90%E9%97%AE%E9%A2%98)
感觉你之前更新vscode没有用它自带的更新功能？ 🤔

**Comment by imleeou** [comment]
> 现在像是在「下载」目录，需要拖到「应用」目录。参考[常见问题](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.zh-CN.md#read-only-file-system---%E5%90%84%E7%A7%8D%E6%97%A0%E6%9D%83%E9%99%90%E9%97%AE%E9%A2%98) 感觉你之前更新vscode没有用它自带的更新功能？ 🤔

我之前都是自动更新的，vscode自动下载安装包，然后重启就更新这种，我一般显示下载好包几天都不重启，闲的时候重启更新一下。
我感觉和权限问题有关，重启vscode后，第一个弹窗右下角有一个重试按钮
![image](https://github.com/user-attachments/assets/589ff6ad-f936-4a20-9795-b799ce0aaca7)
我点了重试之后会让我输入电脑密码，然后就会报上面那个错误

**Comment by shalldie** [comment]
先把插件升级到最新，vscode移动到「应用」目录。再试试呢？

**Comment by imleeou** [comment]
> 先把插件升级到最新，vscode移动到「应用」目录。再试试呢？

我忽然发现，我的[应用]目录是有一个vscode，是我之前用的，这个vscode打不开，打开只显示个黑屏窗口

![image](https://github.com/user-attachments/assets/72797b1e-378b-42b4-b5be-0b4285f5d776)

然后我刚才下载个最新的包，在[下载]目录，这个包可以正常打开，但插件无法使用，报上面的错误

我将新的vscode替换过去，从[应用]可以正常打开和使用了

那这样的话我觉得vscode最新的包有问题，更新后就打不开了

**Comment by imleeou** [comment]
感谢回答，可以关闭了
