### ISSUE TITLE
网络图片能否增加本地缓存

### ISSUE THREAD

**Issue by AsahiMoon** [shalldie/vscode-background#492]
网络差的时候有时候加载不出网络图片，能否对加载过的网络图片做缓存

**Comment by shalldie** [comment]
![image](https://github.com/user-attachments/assets/13e2a1a2-fcc5-4496-9f93-f6c55a8c70ef)

这个其实看图片自身的设置，什么都没配是会有缓存的（vscode浏览器自身特性）。
元信息中如果有 cache-control 之类的设置，缓存就会受其影响。

**Comment by shalldie** [comment]
下一个小版本中会对图片进行预加载，并常驻内存。
以应对网络不好，或者图片设置无缓存的情况。

**Comment by AsahiMoon** [comment]
明白了，多谢解答

**Comment by shalldie** [comment]
发布了 `v2.0.2`，添加了图片预加载功能。
