### ISSUE TITLE
[Bug Report] background.editor -> style -> size、position 属性无效

### ISSUE THREAD

**Issue by ajtn123** [shalldie/vscode-background#494]
## Summary | 概述

background.editor -> style -> size、position 属性无效。

但是 background-size、background-position 工作正常。

### Versions

版本: 1.95.2 (system setup)
提交: e8653663e8840adaf45af01eab5c627a5af81807
日期: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

### Background Config | 插件的配置

```json
{
    "background.editor": {
        "useFront": false,
        "images": ["file:///C:/Users/xxxxx/Pictures/_.png"],
        "style": {
            "position": "100% 100%",
            "size": "contain",
            "opacity": 0.2
        }
    }
}

```

**Comment by shalldie** [comment]
是符合预期的。`backgroud.editor` 的 style ，开放了完全自定义css能力，
期望值就是 `background-size`、`background-position` 等原始css内容，更灵活。

其他部分没有开放完全自定义css，限制了 size、position 等key，指向 `background-size`、`background-position`。
