### ISSUE TITLE
[Question] why I can't have full background and panel at the same time

### ISSUE THREAD

**Issue by MrEsmailian** [shalldie/vscode-background#496]
This is the json I changed in settings.json
{
    "background.fullscreen": {
        "images": [
            "file:///C:/Users/Diego/Pictures/Saved%20Pictures/batman-arkham-knight.jpg"
        ],
        "opacity": 0.8,
        "size": "cover",
        "position": "center",
        "interval": 0,
        "random": false
    },

    "background.panel": {
        "images": [
            "file:///C:/Users/Diego/Pictures/Saved%20Pictures/459402.png"
        ],
        "opacity": 0.6,
        "size": "cover",
        "position": "center"
    }
}

![Screenshot (199)](https://github.com/user-attachments/assets/bec425b3-b5c1-4389-999d-98ed41b52bca)

I get the full background but there is no background for panel

**Comment by shalldie** [comment]
Can you confirm if the image path of `background.panel` is correct ?

![image](https://github.com/user-attachments/assets/c9a04d9b-1a23-46a5-854f-05a427b1459e)

And there should be a warning prompt on your opacity, which version of vscode and background are you using?

**Comment by shalldie** [comment]
The issue in the screenshot is likely caused by a low version of the plugin. 
If the problem persists in the latest version, please open the issue again.
