### ISSUE TITLE
[Bug Report] 透明度调整问题

### ISSUE THREAD

**Issue by bulubulugiao** [shalldie/vscode-background#499]
在最近更新（v2.0.2？）后出现了透明度数值问题（我的背景突然变暗了许多）
opacity为0.1→0.6时背景从暗变亮，但在数值大于0.6后无论如何调整都看不出区别，似乎是数值调节范围从0~1缩小为0~0.6了，不知是否是开发者有意为之
 "background.fullscreen": {    
        "images": ["file:///D:/.File/%E9%9B%AA_GKN.png"],
        "opacity": 0.65,
        "size": "cover",
        "position": "center",
        "interval": 0,
        "random": false
    },

**Comment by shalldie** [comment]
![image](https://github.com/user-attachments/assets/84bbffa0-5b2d-4090-bad1-169d80dd71a3)

特意为之的，大部份图片在超过0.4的时候已经非常影响coding了。
有时候误操作将opacity设置太高，会导致vscode被图片覆盖完全看不到其它内容，无法进行任何操作。
