### ISSUE TITLE
建议加双引号和encodeURI

### ISSUE THREAD

**Issue by zsxsoft** [shalldie/vscode-background#5]
```css
[id='workbench.parts.editor']>.content>.one-editor-silo:nth-child(1) .overflow-guard>.monaco-scrollable-element{background-image: url(${img0});}
```

没双引号的话，文件路径带括号或者空格等，会懵逼
没``encodeURI``的话，非ASCII字符会懵逼

![image](https://cloud.githubusercontent.com/assets/2398785/18154122/b7e1ed1e-7034-11e6-8cff-c089f1bd659d.png)

**Comment by zsxsoft** [comment]
顺便吐个槽，还要管理员模式才能改CSS……

**Comment by shalldie** [comment]
明白了 0.0   找个时间改。
，，不过，如果没有修改文件的权限，这个确实装不了啊，木办法

**Comment by shalldie** [comment]
已经加了。
这个issue我就关闭了哈
