### ISSUE TITLE
[Feature] 除了editor之外的部分也增加设置useFront

### ISSUE THREAD

**Issue by ranhengzhang** [shalldie/vscode-background#501]
sidebar等部分在设置背景图后会遮挡文字(如图)，希望能够选择让图片居于文字下方。

![image](https://github.com/user-attachments/assets/6e71dfdf-8f97-4edb-a457-6d3ff986d073)

**Comment by shalldie** [comment]
这些部分布局比editor复杂太多，内容不仅仅是文字，
之前研究过一段时间，效果并不太好。考虑到成本和风险，最后并没有加上这个功能 =。=
