### ISSUE TITLE
[Feature] The opacity levels

### ISSUE THREAD

**Issue by Marcsxd** [shalldie/vscode-background#502]
I would really love it if they returned the option to place a higher level of opacity in the options since it is actually preferable for the background to be there but be more subtle, it is only as a recommendation since that is why I will stop using this extension, I would rather use the opacity at 0.98 or 0.99 where the image could be seen but it was not so excessive

![imagen_2024-11-14_163714579](https://github.com/user-attachments/assets/6f0887d0-a64b-4339-9fbc-7d731a50c5d8)

**Comment by shalldie** [comment]
![image](https://github.com/user-attachments/assets/2eb4d1a4-1ba4-436c-bc5c-306ec3590fac)

Most images have a significant impact on coding when the opacity exceeds 0.4.
The max limit value is `0.6`, you can try to see if it has an impact.

The maximum limit is to prevent someone from mistakenly setting the `opacity` too high, which may result in nothing being visible.
`0.98` is too high, unless the image itself has a lot of transparency, you won't be able to see anything.

**Comment by Marcsxd** [comment]
Oh okay, now I can understand it, but I think minimum opacity doesn't need to be a rule but rather something of a warning and if users can't properly see the image it's just a "skill issue" xd. Here I have an image when I set the opacity to 0.98 (maybe 0.99, I don't remember) and it looks cool and not distracting, thank you for the response btw, I really appreciate it.
![Argument-xd](https://github.com/user-attachments/assets/98be9729-2598-4e0c-b494-d5e5ba2f8258)
