### ISSUE TITLE
vscode自动更新后，背景图不生效，应该怎么解决

### ISSUE THREAD

**Issue by lyliang1216** [shalldie/vscode-background#503]
每一次vscode自动更新后，背景图都会生效，都需要重启一次，但背景透明度都会发生变化，最近一次vscode更新1.95.2版本，background也更新到最新版本（v2.0.3）后，背景图就完全显示不出来了，再不断重启vscode过程中，图片会偶尔显示一下，但透明度也是异常的。这个问题怎么解决呢

以下是配置信息
```
"background.fullscreen": {
    "images": [
      "https://cdn.nlark.com/yuque/0/2023/jpeg/35541362/1687313643200-5750e5ab-8618-4590-b636-7db11bf965c5.jpeg?x-oss-process=image%2Fresize%2Cw_1500%2Climit_0%2Finterlace%2C1"
    ],
    "opacity": 0.6,
    "size": "cover",
    "position": "center",
    "interval": 0,
    "random": false
  }
```
![image](https://github.com/user-attachments/assets/494112b5-7825-466f-b722-e7d170c297c0)

**Comment by shalldie** [comment]
使用了你的配置，图片能正常展示（除了opacity有点高显得太亮）。
该配置在我这里运行良好：

```json
  "background.fullscreen": {
    "images": [
      "https://cdn.nlark.com/yuque/0/2023/jpeg/35541362/1687313643200-5750e5ab-8618-4590-b636-7db11bf965c5.jpeg?x-oss-process=image%2Fresize%2Cw_1500%2Climit_0%2Finterlace%2C1"
    ],
    "opacity": 0.1,
    "size": "cover",
    "position": "center",
    "interval": 0,
    "random": false
  }
```

> 再不断重启vscode过程中，图片会偶尔显示一下，但透明度也是异常的

没想到原因，把所有vscode窗口都退出(mac：command+q)，只打开一个窗口再试试？

**Comment by lyliang1216** [comment]
> 使用了你的配置，图片能正常展示（除了opacity有点高显得太亮）。 该配置在我这里运行良好：
> 
> ```json
>   "background.fullscreen": {
>     "images": [
>       "https://cdn.nlark.com/yuque/0/2023/jpeg/35541362/1687313643200-5750e5ab-8618-4590-b636-7db11bf965c5.jpeg?x-oss-process=image%2Fresize%2Cw_1500%2Climit_0%2Finterlace%2C1"
>     ],
>     "opacity": 0.1,
>     "size": "cover",
>     "position": "center",
>     "interval": 0,
>     "random": false
>   }
> ```
> 
> > 再不断重启vscode过程中，图片会偶尔显示一下，但透明度也是异常的
> 
> 没想到原因，把所有vscode窗口都退出(mac：command+q)，只打开一个窗口再试试？

我再多次启动试了一下，透明度就是这样的，我将opacity也改为0.1
<img width="959" alt="image" src="https://github.com/user-attachments/assets/3041f378-c498-46a5-a5c0-25d8b5861212">

**Comment by lyliang1216** [comment]
背景图太亮了，之前使用透明度0.65的时候效果比较好，当时是1.x版本的时候

**Comment by lyliang1216** [comment]
有时候我禁用掉这个插件，然后重启后发现背景图还是存在的，像是有缓存一样，又要经过多次重启才会生效

**Comment by shalldie** [comment]
![image](https://github.com/user-attachments/assets/57ad9422-d124-4525-8ca9-441b7360dc8c)


「禁用」可以修改配置 `background.enabled: false` 或者点击右下角「background」按钮唤起菜单。
直接删除/禁用插件会有一些限制，参考[常见问题](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.zh-CN.md#%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E6%8F%92%E4%BB%B6)

---

现在还有什么问题吗？

- 图片会偶尔显示一下
- 透明度显示异常

这俩我怀疑有其它插件影响，，，

**Comment by lyliang1216** [comment]
> ![image](https://private-user-images.githubusercontent.com/9987486/386449693-57ad9422-d124-4525-8ca9-441b7360dc8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDI4MjcsIm5iZiI6MTczMTY0MjUyNywicGF0aCI6Ii85OTg3NDg2LzM4NjQ0OTY5My01N2FkOTQyMi1kMTI0LTQ1MjUtOGNhOS00NDFiNzM2MGRjOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDM0ODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIzMWRiOTBiOThhN2FlZWI2MGE2MjY2NjA0NzE1MGViYmNjMjJhODJjYjMxYTVhZGJhMzE3NDlmYWNkZjkyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MKAQ76jSQ9FLjjSO64JhpA9YTXlFJSajST3NUk8DDAI)
> 
> 「禁用」可以修改配置 `background.enabled: false` 或者点击右下角「background」按钮唤起菜单。 直接删除/禁用插件会有一些限制，参考[常见问题](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.zh-CN.md#%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E6%8F%92%E4%BB%B6)
> 
> 现在还有什么问题吗？
> 
> * 图片会偶尔显示一下
> * 透明度显示异常
> 
> 这俩我怀疑有其它插件影响，，，

主要就是这两个问题，其他插件影响不是很清楚，在最近的几次版本更新前是没有出过问题的，可以现在版本回退还是会有问题，就完全不知道怎么解决了。并且现在我删除或禁用插件，都不起作用，刚才尝试了一下，都是直接卸载vscode重新安装才生效的

**Comment by lyliang1216** [comment]
现在我只有暂时先直接修改vscode的css文件，通过样式的方式来添加背景图，但是效果不是很好

**Comment by shalldie** [comment]
> 现在我只有暂时先直接修改vscode的css文件，通过样式的方式来添加背景图，但是效果不是很好，并且也会出现偶尔图片不显示的问题，我怀疑会不会是vscode版本问题。我还是回退了vscode的版本，安装一年前的版本，发现还是存在这个问题。
> 
> 目前已经快开始怀疑我的电脑问题了

@lyliang1216 

hhh 不至于 😂
虽然不明白具体原因，但这种方式（万能）应该可以解决：

1. 卸载 background
2. 重装 vscode
3. 装回 background
