### ISSUE TITLE
[Feature] 可以考虑图片路径支持相对路径吗

### ISSUE THREAD

**Issue by abandonstudy** [shalldie/vscode-background#505]
![image](https://github.com/user-attachments/assets/715b4659-ab51-4fce-9b02-54b25788bfb6)

vscode官方有对便携版进行支持，但是插件似乎只能用绝对路径

**Comment by shalldie** [comment]
![image](https://github.com/user-attachments/assets/73dcd04b-ebe1-4369-b069-27d2b6683718)

之前没用过便携模式，快速了解了一下。
扩展会对路径做校验，如果填相对路径（非https或file协议地址）会有警告，但其实是支持的。

mac下是默认相对于 `<code>/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/`，
即需要添加 9个`../`: `../../../../../../../../../` 前缀，才是相对code同级目录。

windows 下暂时没条件去验证，，，不清楚是否可用

---

使用相对路径存在一些问题，暂时没有打算对根目录的兼容做处理，或者放开警告。
你如果想用的话，，，可以试试类mac那种，加上 8~10(不同系统下根目录层级存在差异)个 `../` 的前缀 😂😂

**Comment by abandonstudy** [comment]
感谢大佬的回复，经过测试，这种办法在win 10工作正常 相对vscode根目录 需要6个 `./`
![image](https://github.com/user-attachments/assets/a6e60b19-5814-4adb-9010-12e9fd4d105d)


我还有个疑惑  似乎图片必须放在`vscode/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/`中才能生效，请问这是electron自带的限制吗
我把图片放在`vscode/data/background`中，尽管路径是对的，但是并没有生效
![image](https://github.com/user-attachments/assets/4e902075-c223-4cf0-a3e6-792b74eefe76)

**Comment by shalldie** [comment]
code.exe 是程序入口，
`vscode/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/` 是html的位置。

html位置跟程序入口是两码事，html内资源的相对路径，是相对于自身目录的。

**Comment by abandonstudy** [comment]
懂了，先`../`到根目录在进到`data/background`就行了，感谢大佬解惑
![image](https://github.com/user-attachments/assets/b42d4df7-d192-4233-8533-bdcf94558c4e)
