### ISSUE TITLE
[Bug Report] Background superposition

### ISSUE THREAD

**Issue by tab342** [shalldie/vscode-background#506]
## Summary | 概述

If I have both an editor background and a fullscreen background, the two will superpose.

### Versions

![image](https://github.com/user-attachments/assets/622f7739-7e2c-4276-bebc-f075efc3129c)

### Expected Behaviors | 期望的行为

It would be nice to make it so fullscreen background can't appear behind other backgrounds, but still appears if I open a separate window

### Screenshots | 截图

with fullscreen bg:
![image](https://github.com/user-attachments/assets/a0146c53-eca2-4b29-a56d-f983845f92cb)

without fullscreen bg:
![image](https://github.com/user-attachments/assets/ae3fc0aa-0b7e-462e-80c3-67d6e3f0240b)

fullscreen bg in another window:
![image](https://github.com/user-attachments/assets/0ee6a75a-ae52-402a-b7d5-fe69382de615)

**Comment by shalldie** [comment]
This is as expected, they can appear simultaneously without any mutually exclusive behavior.
If you set an image for any section, that section will display it. 

The situation of mutual exclusion has been discussed before, and most people believe that if the user sets it, then it should be displayed.

**Comment by tab342** [comment]
so, if I understand well, there is and will be no way to keep a clean editor background and have my fullscreen background in another window?

**Comment by shalldie** [comment]
Yes, `background` will affect all windows and is a global extension.

There're some issues that they hope to be able to use the workspace configuration. (#257, #471) 
It has some technical issues that currently do not seem to be achievable in the short term.

**Comment by tab342** [comment]
understood, thank you for your answer
