### ISSUE TITLE
[Feature] Add shortcut support for manually switching to the next background image

### ISSUE THREAD

**Issue by Morphorxz** [shalldie/vscode-background#507]
请问会考虑快捷键切换背景到下一张图片吗？就是手动的轮播。自动轮播可能会打断思路，background.fullscreen配合快捷键手动切换可能是一个比较实用的需求。谢谢_(:з」∠)_

This feature request is for implementing a manual carousel. While automatic carousel may interrupt users' workflow, a shortcut key for manually switching the background in background.fullscreen mode could be a more practical solution.

**Comment by shalldie** [comment]
和 #488 重复，结论是目前做不了 =。=

「实时性」的交互暂时没有办法去实现，我会一直探索这方面的方案。

**Comment by Ellie-CV** [comment]
我目前是：

设置 `"interval": 3600` 和 `"random": true`，可以设置时间长一点的。
想换图片了就手动 `Ctrl + Shift + P` 调用 **Developer: Reload Window** 重启窗口
