### ISSUE TITLE
大尺寸背景图片出现问题

### ISSUE THREAD

**Issue by cuitl** [shalldie/vscode-background#54]
先添加的 background.style 的特性比较适合，小尺寸的图片(如默认的图片)，而如果换成 填充适应整个工作窗口的大图片来说，会出现一个问题 就是 opacity:1 ,图片覆盖了 整个代码的内容，若设置透明 <1,又感觉比较模糊， 查看代码应该是图片样式 从  .monaco-scrollable-element{} 改成了 .monaco-scrollable-element:nth-child(2)::after{}  造成的， 希望作者可以考虑一下这种情况 ，亦或通过添加新属性来控制，图片 是否在代码等的上方。

PS： 已经通过修改本地插件的代码来达到之前的效果，但也不是长久之计，之前找了几个黑色主题的背景很不错的，但是不适合当前版本 ，图片分享： http://pan.baidu.com/share/link?shareid=2965468559&uk=3945358808

**Comment by shalldie** [comment]
ok，了解了。
这两天我加个配置吧，用来选择是用前景还是背景。

**Comment by shalldie** [comment]
@cuitl 
已经发布了 ver.1.1.13 ，你试试。
添加了 "background.useFront":boolean
用来选择是否启用 图片前置，false为图片后置

**Comment by cuitl** [comment]
已更新到 1.1.13，问题已解决， 这效率还是蛮高的啊 ：）

**Comment by shalldie** [comment]
=。=  刚好有空
