### ISSUE TITLE
背景图后置后有点问题

### ISSUE THREAD

**Issue by iamziyue** [shalldie/vscode-background#55]
不太好描述，我截图了，就是这个设置
~~~
"background.useFront": true,
~~~
## 这是设置为false之后的情况：
![Markdown](http://i2.kiimg.com/1949/952c3c30b42aab7c.png)
代码自动完成提示框也是这个现象，框框的背景颜色没了。
## 这是保持默认true的情况（正常）
![Markdown](http://i2.kiimg.com/1949/33c086f79dee9f82.png)

**Comment by shalldie** [comment]
很感谢，马上修改

**Comment by shalldie** [comment]
周末玩去啦~
今天已经修复，ver.1.1.14
