### ISSUE TITLE
Does not automatically uninstall, modifies VSCode internal resources

### ISSUE THREAD

**Issue by srl295** [shalldie/vscode-background#56]
This extension modified `Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.css`  as per https://github.com/shalldie/vscode-background/blob/master/src/vscodePath.js and  [here](https://github.com/shalldie/vscode-background/blob/master/src/background.js#L150)

This caused VS Code to complain about internal corruption.

Please find another way to implement this.

**Comment by srl295** [comment]
at least, make it prompt before overwriting internal resources.

**Comment by shalldie** [comment]
This is the only way  to custom css i've found,which is not recommended. https://github.com/Microsoft/vscode/issues/13732

It appeard at ver.1.6.1 .Then i show the reason and what i do at readme.md https://github.com/shalldie/vscode-background#warns-警告

The way to uninstall extension is also in readme.md:

> Q:How to uninstall the extension?
> Q:怎么卸载这个插件？
> 
> A:Set the config  {"background.enabled": false}  in settings.json,then uninstall the plugin.
> A:在 settings.json 中设置 {"background.enabled": false} ，然后再删除插件。如果直接删除插件会有遗留，就需要重装vscode了。

Sorry to bring you trouble,hope it may help you. 😄

**Comment by shalldie** [comment]
Next version,i'll add a more more more big Warn to the top of readme,show that what the extension do.
Maybe it brings you a lot of trouble,haha. Sorry for that.
Best wishes.

**Comment by kidkkr** [comment]
Adding warns is not reasonable way. It should not make side effect after uninstall
