### ISSUE TITLE
opacity 会影响到 code?

### ISSUE THREAD

**Issue by Sooongz** [shalldie/vscode-background#57]
改变 image 的 opacity 会 使 code 也跟着变化?

**Comment by shalldie** [comment]
有2种模式：前景，背景。 使用   "background.useFront"  来控制

前景是一个蒙层，位于代码上层，修改opacity与代码无关。

背景与代码同层，是代码层的背景，如果修改 opacity 会影响code。

**Comment by Sooongz** [comment]
thx

**Comment by Yunui** [comment]
@shalldie 使用 "background.useFront" 来控制，实际上图片的颜色有覆盖到code上，只是设置成0.1的话不仔细看不明显，设置成0.9就看不见code了，由此证明此法不妥，在下用ps改图片亮度解决……，放弃了改opacity。

**Comment by Sooongz** [comment]
能否增加 背景 修改opacity与代码无关 的选项?
前景 通过 修改 opacity 对 code 也是有一点影响

**Comment by Sooongz** [comment]
@Yunui 就是这么的 流弊

**Comment by shalldie** [comment]
小图可以用前景，方便控制opacity。
大图还是用背景，避免遮挡code，需要自己选一张合适透明度的图片了。

**Comment by shalldie** [comment]
@Sooongz 
我也想无关啊，，，但是有个问题。
css，修改 background-image 的透明度，但是不影响自身。
这个样式搞不定

**Comment by Sooongz** [comment]
@shalldie 能否 background-image 之上加蒙层 控制蒙层 opacity

**Comment by shalldie** [comment]
@Sooongz 
我不能修改dom。
但是 ， ...... 你说的好有道理，似乎可以。我用伪类试试

**Comment by Sooongz** [comment]
@shalldie 大拇指给你

**Comment by shalldie** [comment]
@Sooongz 
现在已经用的伪类。但是代码层跟右边的 minimap并不是同一层级，还有滚动条。
所以要么最高层(前景)，要么最底层(背景)，中间不行啊。。

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/27846795-41394f0c-616c-11e7-961f-a4cb66e00db7.png)

滚动条，minimap ，区域层。这3个是平级的。
首先区域层必须比其它2个低，但是区域层里面的背景层又要比 minimap 和 滚动条高。
区域层里面的代码层要比背景层高，但是比 minimap 和 滚动条 低。

这里出现了一个驳论，设 背景层 A，minimap和滚动条为 B，代码层为 C：
条件1： A>B
条件2： C>A && C<B
这个就不成立了啊 :rofl: :rofl: 
此方案不成立。

**Comment by Sooongz** [comment]
不考虑 minimap  是否 完美?

**Comment by shalldie** [comment]
不考虑 minimap 和滚动条倒是可以实现。不过这2个是必须的

**Comment by manhong2112** [comment]
我目前是這麼解決的。。
background: linear-gradient(to bottom, rgba(30,30,30,0.4) 0%,rgba(30,30,30,0.4) 100%), url(abc);
感覺効果還是挺不錯的。。
