### ISSUE TITLE
图片缩放尺寸搞不定

### ISSUE THREAD

**Issue by limuyang2** [shalldie/vscode-background#58]
我有个大图，但是只显示一半。各种属性都试了，都没办法缩放。求帮助

**Comment by limuyang2** [comment]
摸索出来了这个属性->"background-size"
可以缩放了，建议作者能在说明中解释下各个属性。对于尔等没有学过CSS的真的是头疼

**Comment by shalldie** [comment]
:rofl: :rofl: 
css 属性太多啦，不可能都列出来啊。关于常见的样式都可以百度到的
