### ISSUE TITLE
更新了vscode之后，远程图片显示不了了

### ISSUE THREAD

**Issue by Ztachi** [shalldie/vscode-background#59]
![image](https://user-images.githubusercontent.com/6995332/28195449-dae907d4-687c-11e7-92bf-b071cdc81c3e.png)

**Comment by Ztachi** [comment]
![image](https://user-images.githubusercontent.com/6995332/28195494-14cb92fa-687d-11e7-89f1-42dd4cad19a7.png)
本地的就能显示

**Comment by shalldie** [comment]
不好意思，这段时间比较忙。

因为安全策略，只能加载https的图片了  0.0
http的不行现在

**Comment by Ztachi** [comment]
![image](https://user-images.githubusercontent.com/6995332/28653065-0f151656-72be-11e7-973a-522d4b31de40.png)
感谢回答
