### ISSUE TITLE
然而ubuntu16.04依然用不了

### ISSUE THREAD

**Issue by nxlalala** [shalldie/vscode-background#6]

**Comment by shalldie** [comment]
请试试开启管理员权限？
插件需要有对vscode安装目录的文件修改权限。

＝。＝  因为我木有用过ubuntu，所以没有什么说服力。但是有朋友在ubuntu上面成功使用过。
所以麻烦再试试。

**Comment by fghpdf** [comment]
#for vs code:
sudo chown -R $(whoami) /usr/share/code
#for vs code insiders:
sudo chown -R $(whoami) /usr/share/code-insiders
#if you want to check your folder's owner:
ls -la /usr/share/code
#if you want to rollback this permissions back to root:
sudo chown -R root /usr/share/code

这样子开启权限，不过，vs更新了，我又用不了了

**Comment by shalldie** [comment]
更新之后，需要重新设置一下 =。=
计划下个版本弄个配置文件，记录用户的选择

**Comment by fghpdf** [comment]
ubuntu每次更新vscode，需要重新拿一下权限，运行
`sudo chown -R $(whoami) /usr/share/code`
就行了，真尴尬。。。。

**Comment by fghpdf** [comment]
要不把这句话加在日志里吧，先让大家直接去拿下权限

**Comment by shalldie** [comment]
汗，，，
下次更新的时候考虑加进去。
目前先不做改动了，更改的话，要跟功能一起上。

**Comment by shalldie** [comment]
我会把这个issue的链接放入readme.md

**Comment by jskyzero** [comment]
感谢w 这边deepin拿了权限也是可用的w 之前win下也有过自己配图片不过还是配的也不好用默认的就很满足了。。

**Comment by glinxx** [comment]
66666

**Comment by Sherlock09** [comment]
更新之后 有时候 vscode 会崩溃-_-

**Comment by shalldie** [comment]
@Sherlock09 
啊？可否描述再详细点呢
进行什么操作后，然后崩溃是卡死吗

**Comment by CracKerMe** [comment]
win10 建议默认以管理员权限打开，不然 修改了 没反应

**Comment by shalldie** [comment]
@CracKerMe 
....... 你如何使用vscode，我控制不了啊。
这个在第一次使用的时候需要权限，以后就没事了

**Comment by YUAN21** [comment]
呐呐呐~    修改透明度的时候为嘛我的代码透明度也变了

**Comment by shalldie** [comment]
@YUAN21 
`background.useFront` 表示是否使用前景图，默认应该是true。你改成false了吧。
前景图适合小图，透明度木事。
背景图适合大图，透明度只能自己改。

**Comment by jameslin3263** [comment]
請問我一安裝完後出現code檔案損毀要怎麼解決?

**Comment by fghpdf** [comment]
@jameslin3263 忽视就好

**Comment by yangfandashuaige** [comment]
大佬  怎么开启mac的权限啊 我的为什么不可以，有具体的方法吗

**Comment by shalldie** [comment]
@yangfandashuaige 
试试这个 https://github.com/shalldie/vscode-background/issues/46

**Comment by GanJiaJia** [comment]
在mac上似乎没有反应咋办

**Comment by lwjcjmx123** [comment]
Arch LInux 改了权限似乎还是不行, DE gnome

**Comment by kcilcarus** [comment]
@lwjcjmx123 我是manjaro， vscode安装路径是 /opt, 直接把 sudo chown -R $(whoami)  /opt/visual-studio-code 
重启vscode就好了

**Comment by treezhou05** [comment]
可以用了，给你点赞

**Comment by realVEct0r** [comment]
@lwjcjmx123 我也是 Archlinux. 插件原理是修改 `/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.css` 这个 css 文件来 work的, 然而这个文件 owner 是 root, 普通用户没权限写.
给普通用户写权限就行了, 也不用 chown 那么麻烦.

```bash
sudo chmod o+x /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.css
```
然后重启 vscode 就可以了.

**Comment by scorpionV** [comment]
为什么我的vscode我每次弄那个背景主题，我都按照步骤来弄了  还是不行，谁能告诉我，他那个路径的file到底怎么回事鸭？我是都是按照他的来弄，找我自己的路径了，可是还没有反应。

**Comment by scorpionV** [comment]
{
  "git.ignoreLegacyWarning": true,
  
  // Plugin background enabled.background 插件是否启用
  "background.enabled": true,

  // Use default images.使用默认图片
    "background.useDefault": false,


  // Your custom Images(Max length is 3). 自己定制背景图，最多3个
  "background.customImages": [
    "file:///I:/Vue/bei.jpg",
  ],
 
    // Custom common style.自定义各项公有样式.
    "background.style": {
    "content": "''",
    "pointer-events": "none",
    "position": "absolute",
    "z-index": "99999",
    "width": "100%",
    "height": "100%",
    "background-position": "100% 100%",
    "background-repeat": "no-repeat",
    "opacity": 1
  },

  // Each style of backgrounds. 每一个背景图的独有样式。
  "background.styles": [
    {},
    {},
    {}
  ],

**Comment by shalldie** [comment]
@scorpionV 默认背景也不行吗？

**Comment by sxyazi** [comment]
Arch Linux 用 pacman 装的话用这个：

```bash
sudo chmod o+w /usr/lib/code/out/vs/workbench/workbench.main.css
```

**Comment by CarsarSky** [comment]
> @lwjcjmx123 我也是 Archlinux. 插件原理是修改 `/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.css` 这个 css 文件来 work的, 然而这个文件 owner 是 root, 普通用户没权限写.
> 给普通用户写权限就行了, 也不用 chown 那么麻烦.
> 
> ```shell
> sudo chmod o+w /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.css
> ```
> 
> 然后重启 vscode 就可以了.

arch党表示十分感谢

**Comment by Core00077** [comment]
更新到vs1.38版本后，需要修改的路径发生了变化。现在的路径是`/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.css`

所以只用执行`sudo chown xxx:xxx /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.css`即可

**Comment by outloudvi** [comment]
Arch Linux 上可以通过 pacman 的 hook 来在每次更新后自动添加写权限。当然之后需要让插件重新改一下 CSS...

对于 `code` (即 Code - OSS)，可以添加类似[这样](https://gist.github.com/outloudvi/bc076062bea7d6c012251e529f6fb219)的 hook。

**Comment by lucasazhang** [comment]
This extension doesn't work and then when i uninstalled it then it stayed there!

**Comment by lingxd** [comment]
插件再ubuntu18.04未生效      权限也修改过

**Comment by LagrangeOranges** [comment]
> Arch Linux 用 pacman 装的话用这个：
> 
> ```shell
> sudo chmod o+w /usr/lib/code/out/vs/workbench/workbench.main.css
> ```

Archlinux党表示非常感谢！
