### ISSUE TITLE
激活插件失败:no such file or directory

### ISSUE THREAD

**Issue by leitingx762** [shalldie/vscode-background#60]
![image](https://user-images.githubusercontent.com/5674953/28239102-33917c26-6996-11e7-8951-798bdc62578e.png)
更新之后用不了了。。。insider-1.15.0

**Comment by shalldie** [comment]
插件本身是没有支持 insider 的打算，没那精力，，，

这个回复的太晚了。。。抱歉。

刚刚测了一哈， insider 在当前版本是可以用的。
