### ISSUE TITLE
怎么在浏览器实现类似效果，比如chrome?

### ISSUE THREAD

**Issue by lovelori** [shalldie/vscode-background#61]
在vscode中原理大致是把图层置于最顶层，然后透明度调高，就不会影响阅读

在浏览器中通过tampermonkey的插件加上js代码实现这样的效果该怎么做？

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/28558549-e3a2f666-7144-11e7-8181-ba21bd6019dc.png)

如图所示，js添加图层后，给这个图层设置一下样式就好。
