### ISSUE TITLE
Remote image not loaded

### ISSUE THREAD

**Issue by HaiUIT** [shalldie/vscode-background#62]
I upload my image into imgur but the extension can not load it, local file work fine.
Here is the link to the imgage : [imgur.com](http://i.imgur.com/zqPitk2.jpg)

**Comment by shalldie** [comment]
Sorry to see this so late.

"it violates the Content Security Policy directive"
Image in vscode can only use "https" protocol,"http" is not allowed now.

I'll add this notice in next version.
