### ISSUE TITLE
mac下自定义图片不显示。。。

### ISSUE THREAD

**Issue by fatlinlin** [shalldie/vscode-background#65]
mac下面默认图片可以显示，但自定义图片显示不出来。。。
![image](https://user-images.githubusercontent.com/3388306/28779099-8668bfc2-7634-11e7-88d4-33e3f373376d.png)
![image](https://user-images.githubusercontent.com/3388306/28779141-b32d4e60-7634-11e7-8bf5-d2387f266b7d.png)
求解，有没有小伙伴遇到同样的问题？

**Comment by fatlinlin** [comment]
background.useDefault有设置成false也不能用

**Comment by shalldie** [comment]
我试了一下，mac可以使用的，这是我的设置：

![image](https://user-images.githubusercontent.com/9987486/28782105-ca63c398-763e-11e7-8964-1a7b4901958d.png)

既然默认图片可以使用，说明权限没问题，，，
确认一下图片路径没问题？把图片拖到浏览器然后复制地址栏地址。

如果还是不行，麻烦请看看控制台：【帮助】-【切换开发人员工具】 是否有报错 0.0

**Comment by fatlinlin** [comment]
图片地址没有问题。

控制台，日志如图下
![c1fe45ea-71e1-4568-9a3c-8ec8acd70655](https://user-images.githubusercontent.com/3388306/28805935-befe3f04-769f-11e7-8c31-f9102c3de7d6.png)

code版本号： 版本 1.14.2 (1.14.2)
mac系统版本号：10.11.6 (15G1611)

**Comment by ccqgithub** [comment]
我添加一个地址
 ```
https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1490596645&di=6da5eef892835daa877e4514fc019a52&imgtype=jpg&er=1&src=http%3A%2F%2Fd.hiphotos.baidu.com%2Fzhidao%2Fpic%2Fitem%2F72f082025aafa40fe871b36bad64034f79f019d4.jpg
```

最后变成这样了

```
<span><span class="mtk1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="mtk27">"</span><span class="mtk12 detected-link">https://timgsa.baidu.com/timg?image&amp;quality=80&amp;siz</span><span class="mtk12 detected-link">e=b9999_10000&amp;sec=1490596645&amp;di=6da5eef892835daa87</span><span class="mtk12 detected-link">7e4514fc019a52&amp;imgtype=jpg&amp;er=1&amp;src=http%3A%2F%2Fd</span><span class="mtk12 detected-link">.hiphotos.baidu.com%2Fzhidao%2Fpic%2Fitem%2F72f082</span><span class="mtk12 detected-link">025aafa40fe871b36bad64034f79f019d4.jpg</span><span class="mtk27">"</span></span>
```

**Comment by ccqgithub** [comment]
好像只支持https

**Comment by shalldie** [comment]
@ccqgithub 
是的，最近3个vscode的版本限制，外部图片只支持 https 的
