### ISSUE TITLE
设置的背景图，遮盖了代码

### ISSUE THREAD

**Issue by raineliu** [shalldie/vscode-background#66]

**Comment by raineliu** [comment]
图片不支持png格式？

**Comment by shalldie** [comment]
可以设置 【前景/背景】图，来控制图片在代码上面还是下面，背景图不支持透明度调节：
"background.useFront":boolean

支持png，目前因为vscode限制，网络图片http协议的不支持

**Comment by raineliu** [comment]
设置后，侧边栏把图片挡了一部分

**Comment by raineliu** [comment]
设置透明度就好了，不必设置【前景/背景】图

**Comment by shalldie** [comment]
嗯，设置了透明度，同样会遮挡代码。。

看来我会错意了
