### ISSUE TITLE
修改"opacity"属性后，文字和图片的透明度被同时修改了

### ISSUE THREAD

**Issue by GrindstoneLZX** [shalldie/vscode-background#67]
作者你好，
你的这个插件很有意思，我很喜欢。
我尝试了一下，希望通过调整"opacity"属性，修改自定义图片的透明度。
但是我发现图片和文字的透明度是同时修改的，比如当我把opacity设置成0.2的时候，文字的透明度也被修改了，就像这样：
![tim 20170809220406](https://user-images.githubusercontent.com/18130064/29125681-fc3c1160-7d4e-11e7-9afd-3c439dcfc610.png)

我的系统是win10，vscode的版本是1.14.2，background版本是1.1.14.
请问这个问题有办法解决吗？谢谢！

**Comment by shalldie** [comment]
可以设置 【前景/背景】图，来控制图片在代码上面还是下面，背景图不支持透明度调节：
"background.useFront":boolean // 默认为true

一般的小图，可以使用【前景】，这个修改透明度不影响code。
如果是大的图，建议自己修改图片透明度，使用【背景】

**Comment by GrindstoneLZX** [comment]
我明白了，谢谢！
