### ISSUE TITLE
I can't use custom image instead of the default one.

### ISSUE THREAD

**Issue by Darfka** [shalldie/vscode-background#69]
There's nothing that show when I try to use custom images.
Maybe it's the last update that broke this functionnality?

#### Things I tried:

- I runned VS Code as administrator.

- I added these to my settings.
`"background.enabled": true,`
 `"background.useFront": true,`
    `"background.useDefault": false,`
    `"background.customImages": [`
        `    "file:///C:/chakram.png",`
        `    "http://chpic.su/_data/stickers/randowis_stickers/randowis_stickers_002.png",`
        `    "http://chpic.su/_data/stickers/randowis_stickers/randowis_stickers_002.png"`
    `],`

- I verified that the paths were correct. And I tried multiple file at different location. I used png file.

### UPDATE:

It's working! You can't see the background if you are in the settings.json. Also, make sure that when you open the file from the link in settings.json that it shows up correctly. I noticed that the, even though the path was correct, vs code wasn't able to load correctly when they were in "Users/***/Pictures/(folder)/*.png". I now have a folder at the root of my C file and it works greatly.

**But**, I still can't load image from an url.

**Comment by shalldie** [comment]
If a locale file，you need a absolute path.

Because of the limit of vscode,the "http" protocol is not available,you can use "https" instead.

Hope it can help you.
