### ISSUE TITLE
VSCODE 1.4.0 Running the contributed command:'extension.background.reset' failed.

### ISSUE THREAD

**Issue by sqchenxiyuan** [shalldie/vscode-background#7]
VSCODE 1.4.0 Running the contributed command:'extension.background.reset' failed.

![image](https://cloud.githubusercontent.com/assets/18110369/18264187/6b973566-7441-11e6-81ac-d3ef3ae68ce2.png)

0,0不知道为嘛用不了

**Comment by shalldie** [comment]
如果是win下，请确保有对vscode安装目录的文件【写入/修改】权限。干脆【右键-管理员权限运行】吧。

ubuntu 貌似有问题，这个还待修复。

**Comment by sqchenxiyuan** [comment]
0,0  好使了诶    谢谢~~

**Comment by qiang19890912** [comment]
解决了问题，不错！顶你

**Comment by shalldie** [comment]
该插件是使用注入css的方式，所以需要有修改文件的权限。
这个issue我就关闭了哈
