### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by cuautorres** [shalldie/vscode-background#72]
I use the version 1.16.0 of Visual Sutdio Code

**Comment by shalldie** [comment]
Hi,i've tested windows and os x of the ver. 1.16.0
Maybe you need the authority at the first time to use this extension.

In windows,click right button on the vscode's icon,then check the [run with the administrator authority].

In ubuntu, https://github.com/shalldie/vscode-background/issues/6.

And os x,also need the authority to edit vscode's file.

This extension works with editing vscode's file(workbench.main.css),make sure you have the authority to edit it.

**Comment by blackbart420** [comment]
It does not work on archlinux.
But it does work if I launch VSCode as root...

@shalldie I cannot read anything you say in the issue #6 ...

Also, you should only write the help file in english.


Solution for me (on archlinux):

chown {username} /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.css

I guess this should be written as important note in the documentation/help ;)

**Comment by blackbart420** [comment]
PS: great plugin! :+

**Comment by shalldie** [comment]
@blackbart420 
Thanks a lot!

I plan to open a issue include the way to get authority in all OS. 
:smile:

**Comment by 5265liu** [comment]
6666

**Comment by kangkai124** [comment]
I meet the trouble too , and I use the version 1.11.1 of Visual Sutdio Code on MacOS Sierra 10.12.6

**Comment by kangkai124** [comment]
[#46](https://github.com/shalldie/vscode-background/issues/46   resolve it

**Comment by sunb0002** [comment]
我的win10 v1.18.1也是不可以
希望能fix不过也不急啦 :)

"background.customImages": [
        "https://ggsubsteam.files.wordpress.com/2016/11/ev_18.jpg"
    ]

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/33979783-e21805d2-e0e0-11e7-9086-a9a9f04e75a2.png)

![image](https://user-images.githubusercontent.com/9987486/33979795-ec7b79d2-e0e0-11e7-9f28-7b6efafd6d96.png)

@sunb0002 
嗨~ 我测试了一下好像木有问题，你看看是否设置了 **background.userDefault:false** 呢

**Comment by sunb0002** [comment]
@shalldie 额，我这边图片还是没有出来。默认图片(魔理沙?)也没有。
可能是跟公司防火墙之类的原因吧，我去别的地方再试试。
多谢了。

**Comment by anran758** [comment]
@shalldie 我的问题就是出现在这里.. 建议在文档中加入提示.. 当使用自定义图片时, 关`background.userDefault`设置为`false`

**Comment by shalldie** [comment]
@anran758 
嗯，，文档确实差点。下个版本理一理

**Comment by thedonquixotic** [comment]
Hi @shalldie   I'm very sorry to bother you but I can't seem to get the extension to work. 

These are what my settings are set as:

```
// Your custom Images(Max length is 3). 自己定制背景图，最多3个
"background.customImages": ["https://imgur.com/QC16IpJ.jpg"],

// Plugin background enabled.background 插件是否启用
"background.enabled": false,

// Custom common style.自定义各项公有样式.
"background.style": {
  "content": "''",
  "pointer-events": "none",
  "position": "absolute",
  "z-index": "99999",
  "width": "100%",
  "height": "100%",
  "background-position": "100% 100%",
  "background-repeat": "no-repeat",
  "opacity": 1
},

// Each style of backgrounds. 每一个背景图的独有样式。
"background.styles": [
  {},
  {},
  {}
],

// Use default images.使用默认图片
"background.useDefault": false,

// If use front image,which means image is placed on the top of your code. 是否使用前景图，这样会使图片放在代码的顶部
"background.useFront": true
``` 

It does not seem to be working though.

**Comment by shalldie** [comment]
@thedonquixotic 
I see your setting: `"background.enabled": false,`

You have to set it true, to enable the extension.  :D

**Comment by thedonquixotic** [comment]
@shalldie Ooh duh! I must have done that by accident. Thank you!

**Comment by Laughing6901** [comment]
I try to config follow you but it does not work 
I install version 1.1.28 in vscode 
I'm using mac OS X
so can you have me to fix this ?
![Screen Shot 2021-09-08 at 11 07 59](https://user-images.githubusercontent.com/60708963/132444999-8563f056-1d0b-45d5-aeba-68b9211f4d77.png)

**Comment by shalldie** [comment]
@Laughing6901 
I tried your image , it works. This is my config.

**Comment by Laughing6901** [comment]
@shalldie  
I dowloaded it
![Screen Shot 2021-09-08 at 13 11 31](https://user-images.githubusercontent.com/60708963/132455734-69ed3b7c-e17f-4699-8966-e4cb8b05ec03.png)

**Comment by Laughing6901** [comment]
thank you so much 
it work ^^
