### ISSUE TITLE
图片大小不能设置吗？

### ISSUE THREAD

**Issue by Imladris** [shalldie/vscode-background#73]
我用自己的图片，改动width和high没有任何变化
![image](https://user-images.githubusercontent.com/11880913/31002919-b7be450a-a51f-11e7-946a-3731125e69ee.png)
![image](https://user-images.githubusercontent.com/11880913/31002939-c88ad538-a51f-11e7-8a38-0a13bb86af27.png)
这张图片一直就这么大。。。
而且透明度居然是连代码也透明了。。

**Comment by shalldie** [comment]
图片大小用 background-size ，不是 size

另，大图建议自己用工具调整透明度

小图用 opacity 来调节透明度，然后设置 background.useFront:true 前景图

**Comment by Imladris** [comment]
抱歉啊，好久没看，谢谢回复。我自己用PS解决了这些问题，非常感谢大佬提供这么有趣的插件
