### ISSUE TITLE
Custom Images doesn't  work

### ISSUE THREAD

**Issue by dannyTorres** [shalldie/vscode-background#75]
The default images work perfectly:
https://i.imgur.com/YHzzhJr.png

but when I add my own images they just doesn't show.
This is my settings.json
`{
    "workbench.iconTheme": "vscode-icons",
    "vsicons.projectDetection.autoReload": true,
    "window.zoomLevel": 0,
    "editor.tabCompletion": true,
    "editor.smoothScrolling": true,
    "emmet.triggerExpansionOnTab": true,
    "background.customImages": [
        "http://i.imgur.com/dJgdzCd.png"
    ],
    "background.useDefault": false,
    "background.enabled": true
}`

This is the result:
https://i.imgur.com/j2iK68s.png

I don't know if I missing something in the configuration.

OS: Win10
VS Code: 1.16.1

PD: I'm running VS Code as admin.

**Comment by shalldie** [comment]
It's the country built holiday in China,sorry to answer u lately.

Only [https] supportted!   Which the [http] is avoid.

**Comment by blackbart420** [comment]
I put these settings in the user parameters file :   
/home/nicolas/.config/Code/User/settings.json

    "background.useDefault": false,
    "background.customImages": [
        "/home/nicolas/Images/fcgb.png"
    ]

But it doesn't change anything, the images are still the default images.
Any idea ? :)

**Comment by shalldie** [comment]
@blackbart420 
It seems there's sth wrong with the path of image.

Drop the file into webbrowser,then copy it in url field.

**Comment by blackbart420** [comment]
You are right @shalldie 
so the correct path is:

    "background.customImages": [
        "file:///home/nicolas/Images/fcgb.png"
    ],

but I still see the default image...

Also I tried this setting:

    "background.style": {
        "opacity": 0.1
    }

but opacity does not change.

Finally I tried this:
"background.enabled": false

but it does not do anything, my settings are not being used, even by restarting vscode

**Comment by shalldie** [comment]
@blackbart420 
It's strange... Seems you've no authority to edit vscode's file.

steps：[help] => [developer tools] => [console]
Is there any error in the console?

**Comment by blackbart420** [comment]
No, nothing :(

**Comment by blackbart420** [comment]
But,
except the file workbench.main.css,
is it another file for which I need write permission ?

**Comment by shalldie** [comment]
@blackbart420 
It's the only file which needs permission.

```js
    "background.enabled": true,
    "background.useDefault": false,
    "background.useFront": true,
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-repeat": "no-repeat",
        "opacity": 1
    },
    "background.customImages": [
        "file:///D:/Users/s_xie/Desktop/lbpc.gif"
    ]
```
This's all my setting about background. 
Edit and try , there should be a tip appear while enter ctrl+s.

**Comment by blackbart420** [comment]
Yes you are right again :)

![background error](https://user-images.githubusercontent.com/15202659/31438244-5be9c356-ae90-11e7-902d-07eb5990e91e.png)

So what does this mean ?

**Comment by blackbart420** [comment]
Wait, this is weird..

Actually, in issue 72, I made a mistake. 

I did chown on file workbench.main.js

Now I did chown on the correct file, workbench.main.css and now the custom images are working!


But this is very weird that the chown on workbench.main.js resolved my issue about the default images.....

**Comment by shalldie** [comment]
@blackbart420 
No...It does nothing on .js,just the .css.
So permission on .css is needed.

... What makes it work with .js... i have no idea  >_<#@!

**Comment by blackbart420** [comment]
Hello shalldie,
I updated VSCode so the bug came back.
So indeed, it works only by changing ownership of file workbench.main.css
I did not need to change ownership of workbench.main.js

**Comment by shalldie** [comment]
@blackbart420 
Yes , just the css file

**Comment by thedonquixotic** [comment]
@blackbart420  Hey I'm sorry to bother you but how exactly did you get it to work. I'm kind of a newbie to code. Does this extension only work if I manually enable permissions after each update?

**Comment by shalldie** [comment]
@thedonquixotic 
In general, it needs to add the permission for the first time u install this extension (or not).

When found it lost , add the permission again.

**Comment by blackbart420** [comment]
@thedonquixotic sometimes I need to enable permissions again after an update but it is quite rare

**Comment by NickWilde263** [comment]
> 

its always  when i update with apt
