### ISSUE TITLE
Version 1.17 自定义图片不好使

### ISSUE THREAD

**Issue by wzs28150** [shalldie/vscode-background#76]
Version 1.17 这个插件兼容吗？ 安装后 vscode 会弹出code安装似乎损坏,请重新安装 默认背景可以显示 自定义的不好使

**Comment by shalldie** [comment]
兼容。
关于提示损坏的原因在readme中有说明，点击不再提示即可。

自定义图片，如果是外链的，需要用https，不能用http协议。这个是vscode添加的限制，所以建议把图片放到本地。

**Comment by wzs28150** [comment]
我写的是本地的图片 但是没加载啊 - -

**Comment by wzs28150** [comment]
好使了 - -

**Comment by shalldie** [comment]
嗯，好使就行，，
