### ISSUE TITLE
无法使用自定义的背景图

### ISSUE THREAD

**Issue by wwervin72** [shalldie/vscode-background#77]
我在setting.json里面这样配置的
"background.useDefault": false,
"background.customImages": [
        "http://pic49.nipic.com/file/20140927/19617624_230415502002_2.jpg"
    ]
但是自定义的图片没出来，还是默认的。

**Comment by shalldie** [comment]
因为 vscode 的限制，最近的几个版本都只能用 https 协议的外链图片。
http 协议的不能用。

建议下到本地，用本地路径吧
