### ISSUE TITLE
自定义的背景图片无法生效

### ISSUE THREAD

**Issue by xiaobin0103** [shalldie/vscode-background#78]

**Comment by shalldie** [comment]
自定义图片，需要设置 **background.useDefault:false**

且外链图片不能使用 **http** 协议的，需要 **https**

**Comment by xiaobin0103** [comment]
`// 将设置放入此文件中以覆盖默认设置
{
    "files.autoSave": "afterDelay",
    "workbench.colorTheme": "One Monokai",
    "workbench.iconTheme": "vscode-icons",
    "guides.enabled": false,
    "workbench.sideBar.location": "left",
    "workbench.activityBar.visible": true,
    "workbench.statusBar.visible": true,
    "editor.fontSize": 20,
    "editor.minimap.enabled": true,
    "window.zoomLevel": -1,
    "editor.wordWrapColumn": 80,
    "editor.wordWrap": "on",
    "vsicons.dontShowNewVersionMessage": true,
    "vetur.validation.template": false,
    "guides.indent.backgrounds": ["https://imgsa.baidu.com/forum/w%3D580/sign=d3c73396b9fb43161a1f7a7210a54642/b339f8faaf51f3de5a25ea399feef01f3b297983.jpg"
       
    ],
    "background.useDefault": false
}
`
这样设置了也没生效

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/32358763-a5f0242c-c083-11e7-84e0-dc56045699e7.png)

**Comment by shalldie** [comment]
```js
    "background.useDefault": false,
    "background.customImages": [
        "https://user-images.githubusercontent.com/9987486/32358763-a5f0242c-c083-11e7-84e0-dc56045699e7.png"
    ]
```
试试这个，自定义图片地址是要放在 **background.customImages** 中。
然后百度的那个外链做了保护，放在github中木问题。

建议把图片放到本地可能更好

**Comment by xiaobin0103** [comment]
感谢大佬  还是用默认的比较舒服  哈哈

**Comment by shalldie** [comment]
:smile:
