### ISSUE TITLE
求图= =

### ISSUE THREAD

**Issue by szmtcjm** [shalldie/vscode-background#8]
你好，有好图也分享下哈哈哈~
比如说readme里的那几张图~

**Comment by szmtcjm** [comment]
默认背景就是。。。 忽略吧。。

**Comment by shalldie** [comment]
＝。＝
骚年我很尴尬啊

**Comment by atian25** [comment]
不谢
![16](https://cloud.githubusercontent.com/assets/227713/18461211/3fb9bfae-79aa-11e6-9e55-6cace8a9bf76.png)
![15](https://cloud.githubusercontent.com/assets/227713/18461213/423061ac-79aa-11e6-9551-200121385310.png)
![17](https://cloud.githubusercontent.com/assets/227713/18461220/4980a390-79aa-11e6-90f1-592b2a8f0cbf.jpg)

**Comment by shalldie** [comment]
那这个issue我就关闭了哈
