### ISSUE TITLE
Ubuntu16.04 code1.18.0 不能使用

### ISSUE THREAD

**Issue by Acceyuriko** [shalldie/vscode-background#81]
11月9日早上更新之后不能用了。
系统版本 Ubuntu16.04
code版本 1.18.0

无论是使用 
`sudo code --user-data-dir="."`
还是
`sudo chmod $(whoami) /usr/share/code`
都无效。

打开code之后，不会提示code安装似乎损坏，看起来是插件没有运行或者是code的css有过修改。
麻烦看一下。

**Comment by lumia70** [comment]
Window 10 InsiderPreview 16299
vscode版本 1.18.0
用管理员权限打开后也backgroud插件也没有正常生效。

**Comment by shalldie** [comment]
win 下，我重新设置 background.enabled:true 之后就可用了。
卸载，重装插件，也没发现问题。 
回家用家里电脑再试试。

linux和mac，公司没这个环境，要等晚上回家才能看。 ，，希望晚上不加班

**Comment by Acceyuriko** [comment]
在setting里设置background.eabled:false，然后再设置为true，就可用了。
感谢_(:з」∠)_

**Comment by lumia70** [comment]
感谢，windows下管理员权限打开重新设置background.enabled可以了。

**Comment by shalldie** [comment]
哈哈，吓一跳。 能用就好 :smile:
