### ISSUE TITLE
1.18版本好像失效了

### ISSUE THREAD

**Issue by sekaiamber** [shalldie/vscode-background#82]
。。今天更新了1.18版本，然后角落里的老婆就消失了。

**Comment by yueyehm** [comment]
好像是也。今天我也更新了1.18. 消失了。vscode也不提示当前的安装有问题了

**Comment by shalldie** [comment]
在 settings.json 里面，把 **background.enabled** 重新设置一下成 **true** 
老婆们就会回来啦~

我也重新卸载、重装过插件。该问题没重现。

至于该问题产生的原因，，， 猜测是刚更新完毕插件未能运行。

**Comment by yueyehm** [comment]
我之前看过那个开关是true....难道要先设置成false在设置成true？

2017-11-10 16:51 GMT+08:00 谢爽 <notifications@github.com>:

**Comment by shalldie** [comment]
一般性的，插件有2个运行时间：
1.vscode启动时
2.配置文件中插件的配置项修改时

我的意思是通过选项2来触发插件的运行。

选项1，在本次vscode刚更新完毕的时候有反馈说没有正常运行。

**Comment by shalldie** [comment]
@yueyehm 
已经确认是我这边代码的问题。
之前用ts重写的时候，遗漏了 **非首次加载&&vscode文件未hack** 的情况。

已经发布了新版本，下次vscode更新就不会有问题了。 😄

**Comment by yueyehm** [comment]
+10086 回头更新试试看。 在user preference设置成true也可以成功enable。

**Comment by shalldie** [comment]
如果木有问题我就关了哈
