### ISSUE TITLE
Linux 无法加载自己的图片

### ISSUE THREAD

**Issue by StarGazerM** [shalldie/vscode-background#85]
同样的配置在win下似乎没有问题，文件路径好像也是对的，不知道是不是因为png图片之类的·「已经用root权限启动了」

"background.enabled": false,
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "100% 100%",
        "background-repeat": "no-repeat",
        "opacity": 0.6
      },
    "background.customImages": ["file:///home/stargazer/zs2.png"]

**Comment by shalldie** [comment]
额，，，你这个，
`"background.enabled":false`
未启用啊老哥 😄

**Comment by StarGazerM** [comment]
啊 尴尬==, 写haskell写的石勒志
