### ISSUE TITLE
完成插件安装之后没有任何效果0.

### ISSUE THREAD

**Issue by dkl520** [shalldie/vscode-background#86]

**Comment by shalldie** [comment]
麻烦告知一下操作系统，以及配置(settings.json)。另：该插件允许是需要权限(文件的读写)的。

**Comment by dkl520** [comment]
window    
{
    "workbench.iconTheme": "vs-minimal",
    "workbench.colorTheme": "Vue Theme",
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "99999",
        "width": "100%",
        "height": "100%",
        "background-position": "100% 100%",
        "background-repeat": "no-repeat",
        "opacity": 0.6
    },
    "background.useDefault": false,
    "background.customImages": [
        "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1517811878994&di=7c8351868ee15fbd697bbd5f55ce617b&imgtype=0&src=http%3A%2F%2Fimg1.gtimg.com%2Fcomic%2Fpics%2Fhv1%2F91%2F52%2F2072%2F134745151.jpg"
    ]
}

**Comment by dkl520** [comment]
该插件允许是需要权限(文件的读写)的   请问怎么给予它权限啊？？？

**Comment by shalldie** [comment]
windows 下直接右键管理员权限运行。

你这个图片地址不行，这个地址做了一些限制。
可以试试这个，我放在这里就没问题：`https://i2.bvimg.com/11593/912339b6b64fa818.jpg`

建议把图片放到本地，有些站点会对自身的图片做些限制。

**Comment by dkl520** [comment]
thank you
