### ISSUE TITLE
背景透明度设置

### ISSUE THREAD

**Issue by dbshch** [shalldie/vscode-background#87]
当useFront true时透明度设置没问题，但图片会遮挡代码。当设置false使用背景图片时，设置透明度会连着编辑器里的代码一起透明了 。

PS 顺便能不能调节图片大小的缩放
PPS 前面调了半天把整个vsc界面全调崩了

**Comment by shalldie** [comment]
缩放在 `background.style` 里面设置 `background-size` 就好，纯css样式。

useFront 是前景图，原理是有个遮罩。觉得影响代码可以设置透明度。

如果使用背景图，我不知道 `添加背景图，且背景透明容器不透明` 的css怎么写，，，应该是木有吧。
这时候就建议自己把图片p成半透明的了。

蹦的话，，，我确实遇到过，但是无法重现问题。抱歉了，，，需要重装一下hh

**Comment by dbshch** [comment]
感谢。还是直接p透明了。是不是可以给背景加::after实现

**Comment by shalldie** [comment]
`useFront:true` 前景图，是通过 ::after 实现的

**Comment by Using1174** [comment]
@shalldie @dbshch 
背景图可以用 `::before` 实现，不影响容器的透明度，亲测可用。
```
let frontContent = useFront ? '::after' : '::before';
```
但是这样做背景图会被minimap遮挡，可以再添加minimap的样式。
```
.monaco-editor .minimap.slider-mouseover {
    opacity: 0.5;
}

.monaco-editor .minimap.slider-mouseover:hover {
    opacity: 1;
}
```
