### ISSUE TITLE
mac下激活background失败

### ISSUE THREAD

**Issue by woshixiaoqianbi** [shalldie/vscode-background#90]
很久之前就失效了。。。现在想搞点背景图，然后切换到开发者工具控制台报这个错
```
workbench.main.js:sourcemap:4183 激活扩展“shalldie.background”失败: EROFS: read-only file system, open '/private/var/folders/cr/lm2gmxz11n557h64g_rz85x00000gn/T/AppTranslocation/6E15575E-0C64-4B04-8677-676FD07C34BB/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css'。
```

**Comment by shalldie** [comment]
嗨，这个是木有权限。需要手动添加一下，请参照：https://github.com/shalldie/vscode-background/issues/46

**Comment by woshixiaoqianbi** [comment]
@shalldie 爽哥，那个我看过才发的issue，那个简介里本来就有读写权限的。。。但是又说是只读app，我也很无奈。。。

**Comment by shalldie** [comment]
权限修改完后，随意修改一下配置试试。

`background.*`  的任意配置修改，都会触发插件启动。

**Comment by woshixiaoqianbi** [comment]
放弃了。。读写权限改过。background和vscode都重装过。。。还是报上面 read-only错=。=

**Comment by shalldie** [comment]
,,, 你这种情况我见人反馈过。

那人是有2个vscode，改的跟用的不是同一个。 hhh 你要不确认下，或者晚点我们qq上看看。

**Comment by Yshihan** [comment]
我设置完了，但还是设置失败，也激活了，就是没生效，这是啥原因

**Comment by shalldie** [comment]
@Yshihan 
应该是需要权限，可以参考：https://github.com/shalldie/vscode-background/issues/120
