### ISSUE TITLE
Works on mac, but on windows never loads custom images

### ISSUE THREAD

**Issue by ilmam** [shalldie/vscode-background#92]
on Windows 10, it only shows default images. Can't load custom images whether from local machine or from the web. Even if I set `"background.useDefault": false`
I managed to make it work fine on Mac.

**Comment by shalldie** [comment]
Try thease:
1. same setting between mac and win10
2. local images start with `file:///`,web images start with `https://`, `http://` is forbidden
3. make sure you have the authority.

I'll try again after work, reply my result tonight.Thank u 😸

**Comment by ilmam** [comment]
Thanks for the quick response, as a matter of fact, I did the same settings. After many many trials, I was able to make the custom images appear. The funny thing is that I didn't change anything really. Just keep saving the settings file till it worked.

**Comment by shalldie** [comment]
You mean that works on win10 now?

Extension may work every time you save the `settings.json`, if the config has changed, it'll run.

**Comment by ilmam** [comment]
Yes it worked, but I can't say why and when. I did change `settings.json` several times before it could take effect.
I think what really made the difference is that the password (prompt to hit enter or cancel). It didn't show up every time, and I think it only worked after it appeared and I clicked enter.

**Comment by thedonquixotic** [comment]
@ilmam  You ever figure out what you did that got it to work?
