### ISSUE TITLE
如何查看VSCode编辑器的样式结构

### ISSUE THREAD

**Issue by Using1174** [shalldie/vscode-background#97]
我希望单独修改一部分样式，比如minimap出现的时候会让滚动条变得不透明。但是我不清楚VS Code编辑器的样式层次，比如`.overflow-guard>.monaco-scrollable-element:nth-child`这种层级结构是怎么发现的呢？希望能够解答。

**Comment by shalldie** [comment]
【帮助】-【切换开发人员工具】，就可以在  【Elements】里面看到dom结构了

**Comment by Using1174** [comment]
非常感谢！！
